"""
Track C end-to-end PoC: snapped EML tree -> netlist -> fixed-point error report -> Verilog.

Targets are the two canonical valid forms from the released v2 data:
  exp d=2 : eml(x,1)                  on x in [-2, 2]
  ln  d=4 : eml(1,eml(eml(1,x),1))    on x in [0.1, 10]

The trees are constructed via the warm-start primitive (initialize_to_target)
and hard-snapped -- bit-identical in symbol space to the forms recovered by
training in snapping_v2_final.csv / basin_warmstart_v2.4_postfix.csv, so the
quantization error measured here is the error of the *actual* recovered
solutions, not random weights.

Run from repo root:  python -m hardware.run_poc
Outputs: hardware/rtl/*.v + *.hex, results/hardware_poc_report.md
"""

import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from eml_layer_v2 import EMLTree
from hardware.fixed_point import FixedPointFormat, FixedEML
from hardware.converter import extract_netlist, eval_netlist_float, eval_netlist_fixed
from hardware.verilog_gen import emit_verilog

HERE = os.path.dirname(os.path.abspath(__file__))
RTL_DIR = os.path.join(HERE, "rtl")
REPORT = os.path.join(os.path.dirname(HERE), "results", "hardware_poc_report.md")

N_GRID = 2001


def build_snapped(func: str, depth: int, expected_form: str) -> EMLTree:
    tree = EMLTree(depth=depth)
    tree.initialize_to_target(func, noise=0.0)
    tree.snap_all()
    form = tree.verify_embedding(expected_form, warn=False)
    return tree


def error_table(net, fe, xs, true_fn):
    """Returns dict of MAE/max vs true function and vs float64 netlist."""
    sum_t = max_t = sum_n = max_n = 0.0
    for x in xs:
        yf = eval_netlist_fixed(net, fe, x)
        yt = true_fn(x)
        yn = eval_netlist_float(net, x)
        et, en = abs(yf - yt), abs(yf - yn)
        sum_t += et; max_t = max(max_t, et)
        sum_n += en; max_n = max(max_n, en)
    n = len(xs)
    return {"mae_true": sum_t / n, "max_true": max_t,
            "mae_net": sum_n / n, "max_net": max_n}


def grid(a, b, n=N_GRID):
    return [a + i * (b - a) / (n - 1) for i in range(n)]


def main():
    cases = [
        ("exp_d2", "exp", 2, "eml(x,1)", math.exp, grid(-2.0, 2.0)),
        ("ln_d4", "ln", 4, "eml(1,eml(eml(1,x),1))", math.log, grid(0.1, 10.0)),
    ]
    formats = [FixedPointFormat(8, 8), FixedPointFormat(10, 8), FixedPointFormat(10, 12)]

    lines = []
    lines.append("# Track C hardware PoC: fixed-point error on real recovered forms\n")
    lines.append("Generated by `hardware/run_poc.py`. Bit-exact integer model "
                 "(`hardware/fixed_point.py`) mirrors the emitted Verilog operation-for-operation.\n")
    lines.append("- exp LUT: 257 entries, direct-indexed over the gate clamp domain [-8,8], "
                 "linear interpolation using all input bits below the index (up to 8).")
    lines.append("- ln: range reduction `ln(m*2^k) = ln_lut[m] + k*ln2` "
                 "(leading-one detect + 257-entry mantissa LUT + interp).")
    lines.append("- `vs true` = fixed-point output vs the target function (total error incl. "
                 "the symbolic form itself); `vs float netlist` = vs float64 eval of the same "
                 "snapped expression (pure quantization error).\n")

    emitted = []
    for name, func, depth, form, true_fn, xs in cases:
        tree = build_snapped(func, depth, form)
        net = extract_netlist(tree)
        n_act = len(net.active_gates())
        print(f"{name}: form={form}  gates={len(net.gates)} total, {n_act} active after folding")
        lines.append(f"## {name}: `{form}` (depth {depth}, domain "
                     f"[{xs[0]:g}, {xs[-1]:g}], {N_GRID} points)\n")
        lines.append(f"Netlist: {len(net.gates)} gates total, **{n_act} active** after "
                     f"constant folding (off-path/constant gates cost zero LUTs).\n")
        lines.append("| Format | MAE vs true | max vs true | MAE vs float netlist | max vs float netlist |")
        lines.append("|---|---|---|---|---|")
        for fmt in formats:
            fe = FixedEML(fmt)
            r = error_table(net, fe, xs, true_fn)
            tag = f"Q{fmt.int_bits}.{fmt.frac_bits}"
            print(f"  {tag}: MAE_true={r['mae_true']:.6f} max_true={r['max_true']:.6f} "
                  f"MAE_net={r['mae_net']:.6f} max_net={r['max_net']:.6f}")
            lines.append(f"| {tag} ({fmt.total_bits}b) | {r['mae_true']:.6f} | {r['max_true']:.6f} "
                         f"| {r['mae_net']:.6f} | {r['max_net']:.6f} |")
        lines.append("")

        # Emit Verilog with a format that fits the intermediates and meets the
        # paper's 0.01 threshold pointwise (the ln chain's intermediate reaches
        # e^e/0.1 = 151.5, which overflows Q8.8; Q10.12 also fixes edge precision).
        emit_fmt = FixedPointFormat(8, 8) if name == "exp_d2" else FixedPointFormat(10, 12)
        info = emit_verilog(net, FixedEML(emit_fmt), name, RTL_DIR)
        emitted.append((name, emit_fmt, info))
        lines.append(f"Emitted RTL (`Q{emit_fmt.int_bits}.{emit_fmt.frac_bits}`): "
                     f"`hardware/rtl/{name}.v` ({info['active_gates']} eml_gate instances) "
                     f"+ LUT hex images + sweep testbench.\n")

    lines.append("## Resource estimate (per eml_gate, iCE40)\n")
    lines.append("- 2 ROMs x 257 x W bits. At W=16/18 each fits in one 4Kbit EBR "
                 "(256x16) plus a couple of fabric LUTs for the endpoint entry; "
                 "**~2 EBR per gate** (of 30 on an iCE40 UP5K / 32 on HX8K).")
    lines.append("- Interpolation: one (W+1)x4 multiply per LUT -> small fabric or "
                 "shared SB_MAC16 slice; leading-one detect ~W LUT4s; k*ln2 one small multiply.")
    lines.append("- exp_d2 after folding is **1 gate** (~2 EBR); ln_d4 is **3 gates** "
                 "(~6 EBR) -- both comfortably fit even the UP5K.")
    lines.append("- PoC RTL is combinational; production version registers the EBR reads "
                 "and pipelines one stage per gate level (numerics unchanged).\n")
    lines.append("## Caveats\n")
    lines.append("- Q8.8 saturates the ln_d4 intermediate exp output (e^e/x reaches "
                 "151.5 at x=0.1, > 127.996); the table shows the resulting edge error. "
                 "Q10.8 removes the overflow; Q10.12 shows the precision-limited floor.")
    lines.append("- Synthesis (yosys/nextpnr) not run -- toolchain not assumed present; "
                 "estimation-first per ROADMAP Track C staging.\n")

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as f:
        f.write("\n".join(lines))
    print(f"\nReport written to {REPORT}")
    for name, fmt, info in emitted:
        print(f"RTL: {info['rtl']}")


if __name__ == "__main__":
    main()
