"""
CSV-driven Track C flow: every unique valid symbolic form in the released data
-> fixed-point error report -> RTL.

Reads the canonical CSVs (snapping_v2_final.csv and
results/basin_warmstart_v2.4_postfix.csv -- NOT the pre-fix diagnostic
results/basin_warmstart.csv), collects unique (function, symbolic_form) pairs
among valid_snap==1 rows, parses each form into a netlist, evaluates the
bit-exact fixed-point model against the target function over the training
domain, and emits RTL per unique form.

Run from repo root:  python -m hardware.run_csv
Outputs: hardware/rtl/csv_<function>_f<k>.v etc., results/hardware_csv_forms_report.md
"""

import csv
import math
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hardware.fixed_point import FixedPointFormat, FixedEML
from hardware.converter import eval_netlist_float, eval_netlist_fixed
from hardware.form_parser import parse_form
from hardware.verilog_gen import emit_verilog

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RTL_DIR = os.path.join(HERE, "rtl")
REPORT = os.path.join(ROOT, "results", "hardware_csv_forms_report.md")

# Canonical data only (basin_warmstart.csv is the pre-fix diagnostic corpus).
CSVS = ["snapping_v2_final.csv", os.path.join("results", "basin_warmstart_v2.4_postfix.csv")]

# Training domains from experiment_v2.py make_data()
DOMAINS = {"exp": (-2.0, 2.0), "ln": (0.1, 10.0), "sqrt": (0.1, 10.0)}
TARGETS = {"exp": math.exp, "ln": math.log, "sqrt": math.sqrt}

N_GRID = 2001
FORMATS = [FixedPointFormat(8, 8), FixedPointFormat(10, 12)]


def collect_valid_forms():
    """-> {(function, form): n_valid_rows} across the canonical CSVs."""
    forms = Counter()
    for path in CSVS:
        with open(os.path.join(ROOT, path)) as f:
            for r in csv.DictReader(f):
                if r.get("valid_snap") == "1" and r.get("symbolic_form"):
                    forms[(r["function"], r["symbolic_form"])] += 1
    return forms


def main():
    forms = collect_valid_forms()
    lines = ["# Track C: fixed-point error for every valid form in the canonical CSVs\n",
             f"Generated by `hardware/run_csv.py` from {', '.join(f'`{c}`' for c in CSVS)}. "
             f"Netlists parsed directly from `symbolic_form` (no tree reconstruction).\n"]

    for fi, ((func, form), n_rows) in enumerate(sorted(forms.items())):
        net = parse_form(form)
        lo, hi = DOMAINS[func]
        xs = [lo + i * (hi - lo) / (N_GRID - 1) for i in range(N_GRID)]
        true_fn = TARGETS[func]
        n_act = len(net.active_gates())

        print(f"{func}: {form}  ({n_rows} valid rows; {n_act} active gates)")
        lines.append(f"## `{form}` ({func}, {n_rows} valid rows across CSVs, "
                     f"domain [{lo:g}, {hi:g}])\n")
        lines.append(f"{len(net.gates)} gates, **{n_act} active** after folding.\n")
        lines.append("| Format | MAE vs target | max vs target | MAE vs float netlist | max vs float netlist |")
        lines.append("|---|---|---|---|---|")
        best_fmt = None
        for fmt in FORMATS:
            fe = FixedEML(fmt)
            st = mt = sn = mn = 0.0
            for x in xs:
                yf = eval_netlist_fixed(net, fe, x)
                et = abs(yf - true_fn(x))
                en = abs(yf - eval_netlist_float(net, x))
                st += et; mt = max(mt, et)
                sn += en; mn = max(mn, en)
            n = len(xs)
            tag = f"Q{fmt.int_bits}.{fmt.frac_bits}"
            lines.append(f"| {tag} ({fmt.total_bits}b) | {st/n:.6f} | {mt:.6f} "
                         f"| {sn/n:.6f} | {mn:.6f} |")
            print(f"  {tag}: MAE={st/n:.6f} max={mt:.6f}")
            if mt < 0.01 and best_fmt is None:
                best_fmt = fmt
        emit_fmt = best_fmt or FORMATS[-1]
        name = f"csv_{func}_f{fi}"
        info = emit_verilog(net, FixedEML(emit_fmt), name, RTL_DIR)
        lines.append(f"\nEmitted `hardware/rtl/{name}.v` at "
                     f"Q{emit_fmt.int_bits}.{emit_fmt.frac_bits} "
                     f"({info['active_gates']} eml_gate instances)."
                     + ("" if best_fmt else "  **No evaluated format met max<0.01.**") + "\n")

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as f:
        f.write("\n".join(lines))
    print(f"\n{len(forms)} unique valid form(s). Report: {REPORT}")


if __name__ == "__main__":
    main()
