"""
Byte-serial streaming wrapper (Track C stage 5).

Wraps a pipelined core (<name> from verilog_gen_pipelined.py) in a byte-wide
streaming interface so the design fits real package pin budgets: the bare
port-per-bit PoC tops need 2W+1 pins (45 for Q10.12 -- more than the UP5K
sg48's 39); the wrapper needs 19 regardless of W.

Interface (one clock domain):
  in_data[7:0] + in_valid   -- x samples, N_IN = ceil(W/8) bytes, little-endian
  out_data[7:0] + out_valid -- y results, N_IN bytes, little-endian, sign-extended

Feed at most one byte per cycle; a new sample completes every N_IN cycles,
which exactly matches the serializer drain rate (N_OUT == N_IN), so output
can never be overrun. The core keeps streaming every cycle; a sample_valid
shift register LATENCY deep marks which core outputs are real.
"""

import os
from .fixed_point import FixedPointFormat

def emit_stream_wrapper(core_name: str, fmt: FixedPointFormat, latency: int, out_dir: str) -> dict:
    # Core-agnostic: only needs the Q-format (total bits) of the wrapped core,
    # so it wraps any clocked (.clk,.x_in,.y_out) core -- snapped-EML or MLP.
    W = fmt.total_bits
    n = (W + 7) // 8          # bytes per sample, in and out
    wb = 8 * n
    name = f"{core_name}_stream"
    os.makedirs(out_dir, exist_ok=True)

    rtl = f"""// Generated by hardware/verilog_gen_stream.py -- do not edit by hand.
// Byte-serial streaming wrapper around {core_name} (W={W}, {n} bytes/sample,
// core latency {latency} cycles). 19 I/O pins total.

module {name} (
    input clk,
    input [7:0] in_data,
    input in_valid,
    output [7:0] out_data,
    output out_valid
);
    localparam W = {W}, NIN = {n}, WB = {wb}, LATENCY = {latency};

    // ---- deserializer: NIN bytes little-endian -> one x sample ----
    reg [WB-1:0] in_shift = 0;
    reg [3:0] in_cnt = 0;
    reg sample_valid = 0;
    reg signed [W-1:0] x_s = 0;
    wire [WB-1:0] next_shift = {{in_data, in_shift[WB-1:8]}};
    always @(posedge clk) begin
        sample_valid <= 1'b0;
        if (in_valid) begin
            in_shift <= next_shift;
            if (in_cnt == NIN - 1) begin
                in_cnt <= 0;
                x_s <= next_shift[W-1:0];
                sample_valid <= 1'b1;
            end else
                in_cnt <= in_cnt + 1;
        end
    end

    // ---- core (streams every cycle; only sample_valid slots are real) ----
    wire signed [W-1:0] y_core;
    {core_name} u_core (.clk(clk), .x_in(x_s), .y_out(y_core));

    reg [LATENCY-1:0] vpipe = 0;
    always @(posedge clk)
        vpipe <= {{vpipe[LATENCY-2:0], sample_valid}};
    wire result_valid = vpipe[LATENCY-1];

    // ---- serializer: NIN bytes little-endian, sign-extended ----
    reg [WB-1:0] out_shift = 0;
    reg [3:0] out_cnt = 0;
    wire [WB-1:0] y_ext = {{{{(WB-W){{y_core[W-1]}}}}, y_core}};
    always @(posedge clk) begin
        if (result_valid) begin
            out_shift <= y_ext;
            out_cnt <= NIN;
        end else if (out_cnt != 0) begin
            out_shift <= {{8'd0, out_shift[WB-1:8]}};
            out_cnt <= out_cnt - 1;
        end
    end
    assign out_data = out_shift[7:0];
    assign out_valid = (out_cnt != 0);
endmodule
"""

    f_shift = fmt.frac_bits - 6
    tb = f"""// Streaming testbench for {name}: byte-feeds the 256-point sweep,
// reassembles output bytes, prints x_raw,y_raw CSV (same format as other tbs).
`timescale 1ns/1ps
module {name}_tb;
    localparam W = {W}, NIN = {n};
    reg clk = 0;
    always #5 clk = ~clk;
    reg [7:0] in_data = 0;
    reg in_valid = 0;
    wire [7:0] out_data;
    wire out_valid;
    {name} dut (.clk(clk), .in_data(in_data), .in_valid(in_valid),
                .out_data(out_data), .out_valid(out_valid));

    reg signed [W-1:0] xq [0:255];
    reg [{wb}-1:0] acc = 0;
    integer acc_n = 0;
    integer recv = 0;
    reg signed [W-1:0] yv;
    always @(posedge clk) begin
        #1;
        if (out_valid) begin
            acc = {{out_data, acc[{wb}-1:8]}};
            acc_n = acc_n + 1;
            if (acc_n == NIN) begin
                yv = acc[W-1:0];
                $display("%0d,%0d", xq[recv], yv);
                recv = recv + 1;
                acc_n = 0;
                if (recv == 256) $finish;
            end
        end
    end

    integer i, b;
    reg signed [W-1:0] xv;
    reg [{wb}-1:0] xext;
    initial begin
        for (i = 0; i < 256; i = i + 1) begin
            xv = $signed(i - 128) <<< {f_shift};
            xq[i] = xv;
            xext = {{{{({wb}-W){{xv[W-1]}}}}, xv}};
            for (b = 0; b < NIN; b = b + 1) begin
                @(negedge clk);
                in_data = xext[8*b +: 8];
                in_valid = 1;
            end
        end
        @(negedge clk);
        in_valid = 0;
        repeat (200) @(posedge clk);
        $display("TIMEOUT: only %0d results", recv);
        $finish;
    end
endmodule
"""

    rtl_path = os.path.join(out_dir, f"{name}.v")
    tb_path = os.path.join(out_dir, f"{name}_tb.v")
    with open(rtl_path, "w") as f:
        f.write(rtl)
    with open(tb_path, "w") as f:
        f.write(tb)
    return {"rtl": rtl_path, "tb": tb_path, "name": name,
            "bytes_per_sample": n, "latency": latency}


def emit_stream_wrapper_2in(core_name: str, fmt: FixedPointFormat, out_dir: str,
                            core_latency: int = 0) -> dict:
    """Byte-serial wrapper for a 2-input core (.x_in,.y_in,.y_out), 19 I/O pins.

    A result consumes 2*NIN input bytes: NIN little-endian bytes for x, then NIN
    for y. x and y are latched and held; the core then evaluates while its inputs
    are stable. `core_latency` = 0 for a combinational core (.x_in,.y_in,.y_out;
    captured one cycle after the sample), or N for a clocked pipelined core
    (.clk,.x_in,.y_in,.y_out; captured N cycles later). Since inputs are held for
    2*NIN cycles, any core_latency < 2*NIN settles in time. Used by the arity
    experiment so the 2-input symbolic unit and the 2-input MLP are synthesized at
    the same pin budget as every other stream row (see the note, sec 4.4).
    """
    W = fmt.total_bits
    n = (W + 7) // 8
    wb = 8 * n
    name = f"{core_name}_stream"
    D = max(1, core_latency)        # strobe delay from sample_valid to a settled output
    os.makedirs(out_dir, exist_ok=True)

    if core_latency == 0:
        inst = f"    {core_name} u_core (.x_in(x_s), .y_in(y_s), .y_out(y_core));"
    else:
        inst = f"    {core_name} u_core (.clk(clk), .x_in(x_s), .y_in(y_s), .y_out(y_core));"
    vpipe_shift = ("sample_valid" if D == 1
                   else "{vpipe[D-2:0], sample_valid}")

    rtl = f"""// Generated by hardware/verilog_gen_stream.py -- do not edit by hand.
// 2-input byte-serial wrapper around {core_name} (W={W}, {n} bytes/sample,
// 2 samples x then y per result, core_latency={core_latency}). 19 I/O pins total.

module {name} (
    input clk,
    input [7:0] in_data,
    input in_valid,
    output [7:0] out_data,
    output out_valid
);
    localparam W = {W}, NIN = {n}, WB = {wb}, D = {D};

    // ---- deserializer: 2*NIN bytes little-endian -> (x, y) ----
    reg [WB-1:0] in_shift = 0;
    reg [4:0] in_cnt = 0;            // 0 .. 2*NIN-1
    reg signed [W-1:0] x_s = 0, y_s = 0;
    reg sample_valid = 0;
    wire [WB-1:0] next_shift = {{in_data, in_shift[WB-1:8]}};
    always @(posedge clk) begin
        sample_valid <= 1'b0;
        if (in_valid) begin
            in_shift <= next_shift;
            if (in_cnt == NIN - 1) begin            // x complete
                x_s <= next_shift[W-1:0];
                in_cnt <= in_cnt + 1;
            end else if (in_cnt == 2*NIN - 1) begin // y complete -> sample ready
                y_s <= next_shift[W-1:0];
                in_cnt <= 0;
                sample_valid <= 1'b1;
            end else
                in_cnt <= in_cnt + 1;
        end
    end

    // ---- core (inputs held; capture D cycles after the sample completes) ----
    wire signed [W-1:0] y_core;
{inst}
    reg [D-1:0] vpipe = 0;
    always @(posedge clk) vpipe <= {vpipe_shift};
    wire result_valid = vpipe[D-1];

    // ---- serializer: NIN bytes little-endian, sign-extended ----
    reg [WB-1:0] out_shift = 0;
    reg [3:0] out_cnt = 0;
    wire [WB-1:0] y_ext = {{{{(WB-W){{y_core[W-1]}}}}, y_core}};
    always @(posedge clk) begin
        if (result_valid) begin
            out_shift <= y_ext;
            out_cnt <= NIN;
        end else if (out_cnt != 0) begin
            out_shift <= {{8'd0, out_shift[WB-1:8]}};
            out_cnt <= out_cnt - 1;
        end
    end
    assign out_data = out_shift[7:0];
    assign out_valid = (out_cnt != 0);
endmodule
"""

    rtl_path = os.path.join(out_dir, f"{name}.v")
    with open(rtl_path, "w") as f:
        f.write(rtl)
    return {"rtl": rtl_path, "name": name, "bytes_per_sample": n,
            "latency": core_latency}
