"""
Verilog emission for a snapped EML netlist (iCE40 target, estimation-first).

Emits:
  <name>_exp_lut.hex / <name>_ln_lut.hex : 257-entry ROM images (two's complement)
  <name>.v                               : eml_exp / eml_ln / eml_gate + top module
  <name>_tb.v                            : self-checking-ish sweep testbench (dumps CSV)

The arithmetic mirrors hardware/fixed_point.py operation-for-operation:
direct-indexed exp LUT over [-8,8] with 4-bit interpolation, and range-reduced
ln (leading-one detect + mantissa LUT + k*ln2). Combinational PoC -- for timing
closure on a real iCE40 the ROM reads would be registered (1-cycle EBR) and the
tree pipelined per gate level; that does not change the numerics validated here.

Constant-folded gates from the netlist are baked as localparams; off-path gates
are not emitted at all.
"""

import os
from .fixed_point import FixedEML, LUT_BITS
from .converter import Netlist


def _hex_lines(values, width_bits):
    mask = (1 << width_bits) - 1
    return "\n".join(f"{v & mask:0{(width_bits + 3) // 4}X}" for v in values) + "\n"


def emit_verilog(net: Netlist, fe: FixedEML, name: str, out_dir: str) -> dict:
    fmt = fe.fmt
    W, F = fmt.total_bits, fmt.frac_bits
    os.makedirs(out_dir, exist_ok=True)

    exp_hex = f"{name}_exp_lut.hex"
    ln_hex = f"{name}_ln_lut.hex"
    with open(os.path.join(out_dir, exp_hex), "w") as f:
        f.write(_hex_lines(fe.exp_lut, W))
    with open(os.path.join(out_dir, ln_hex), "w") as f:
        f.write(_hex_lines(fe.ln_lut, W))

    active = net.active_gates()

    def src_expr(kind_child):
        kind, child = kind_child
        if kind == 'const1':
            return f"{W}'sd{fe.one}"
        if kind == 'x':
            return "x_in"
        g = net.gates[child]
        if g.const_val is not None:
            raw = fmt.quantize(g.const_val)
            return f"const_g{child}"
        return f"g{child}_out"

    # localparams for folded constants actually referenced
    const_decls = []
    referenced_consts = set()
    for g in active:
        for kind, child in (g.left, g.right):
            if kind == 'gate' and net.gates[child].const_val is not None:
                referenced_consts.add(child)
    for ci in sorted(referenced_consts):
        raw = fmt.quantize(net.gates[ci].const_val)
        const_decls.append(
            f"    localparam signed [{W-1}:0] const_g{ci} = {W}'sd{raw};"
            f"  // folded gate {ci} = {net.gates[ci].const_val:.6f}")

    # Fully-constant netlist (root folded): output is a literal, no gates emitted.
    root = net.gates[net.out_idx]
    if root.const_val is not None:
        out_expr = f"{W}'sd{fmt.quantize(root.const_val)}"
    else:
        out_expr = f"g{net.out_idx}_out"

    gate_insts = []
    for g in active:
        gate_insts.append(f"""    wire signed [{W-1}:0] g{g.idx}_out;
    eml_gate #(.W({W}), .F({F})) u_g{g.idx} (
        .a({src_expr(g.left)}),
        .b({src_expr(g.right)}),
        .y(g{g.idx}_out)
    );""")

    rtl = f"""// Generated by hardware/verilog_gen.py -- do not edit by hand.
// Snapped EML tree '{name}': {len(active)} active gate(s) of {len(net.gates)} total
// Format Q{fmt.int_bits}.{F} ({W} bits). eml(a,b) = exp(clamp(a,-8,8)) - ln(b).

// ---------------------------------------------------------------- exp(a) ----
module eml_exp #(parameter W = {W}, parameter F = {F}) (
    input  signed [W-1:0] a,
    output signed [W-1:0] y
);
    localparam LUTB = {LUT_BITS}, IB = {fe.interp_bits};
    localparam signed [W-1:0] XMIN = -(8 <<< F), XMAX = (8 <<< F);

    reg signed [W-1:0] lut [0:(1<<LUTB)];
    initial $readmemh("{exp_hex}", lut);

    wire signed [W-1:0] r = (a < XMIN) ? XMIN : (a > XMAX) ? XMAX : a;
    wire [W:0] u = r - XMIN;                       // 0 .. 2^(F+4), needs W+1 bits
    wire [LUTB:0] idx = u >> (F - 4);              // 0 .. 256
    wire [IB-1:0] fr = u >> (F - 4 - IB);
    wire signed [W-1:0] y0 = lut[idx];
    wire signed [W-1:0] y1 = (idx >= (1 << LUTB)) ? lut[1 << LUTB] : lut[idx + 1];
    wire signed [W+IB:0] d = (y1 - y0) * $signed({{1'b0, fr}});
    assign y = (idx >= (1 << LUTB)) ? lut[1 << LUTB] : y0 + (d >>> IB);
endmodule

// ----------------------------------------------------------------- ln(b) ----
// ln(m * 2^k) = ln_lut[m] + k*ln2, m in [1,2) via leading-one detect.
module eml_ln #(parameter W = {W}, parameter F = {F}) (
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    localparam LUTB = {LUT_BITS}, IB = {fe.interp_bits};
    localparam signed [W-1:0] LN2 = {W}'sd{fe.ln2_fix};

    reg signed [W-1:0] lut [0:(1<<LUTB)];
    initial $readmemh("{ln_hex}", lut);

    wire [W-1:0] r = (b <= 0) ? {W}'d1 : b[W-1:0];   // clamp to smallest positive

    // leading-one position p
    integer i;
    reg [$clog2(W)-1:0] p;
    always @* begin
        p = 0;
        for (i = 0; i < W; i = i + 1)
            if (r[i]) p = i[$clog2(W)-1:0];
    end

    // top LUTB+IB mantissa bits below the leading one
    wire [2*W-1:0] rext = r;
    wire [2*W-1:0] shifted = (rext << W) >> p;       // mantissa fraction in bits [W-1:0]
    wire [LUTB+IB-1:0] mant = shifted[W-1 -: LUTB+IB];
    wire [LUTB-1:0] idx = mant[LUTB+IB-1:IB];
    wire [IB-1:0] fr = mant[IB-1:0];

    wire signed [W-1:0] y0 = lut[idx];
    wire signed [W-1:0] y1 = lut[idx + 1];
    wire signed [W+IB:0] d = (y1 - y0) * $signed({{1'b0, fr}});
    wire signed [W-1:0] ln_m = y0 + (d >>> IB);

    wire signed [$clog2(W):0] k = $signed({{1'b0, p}}) - F;
    assign y = ln_m + k * LN2;
endmodule

// -------------------------------------------------------------- eml gate ----
module eml_gate #(parameter W = {W}, parameter F = {F}) (
    input  signed [W-1:0] a,
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    wire signed [W-1:0] ea, lb;
    eml_exp #(.W(W), .F(F)) u_exp (.a(a), .y(ea));
    eml_ln  #(.W(W), .F(F)) u_ln  (.b(b), .y(lb));
    wire signed [W:0] s = ea - lb;
    localparam signed [W:0] SMAX = (1 <<< (W-1)) - 1, SMIN = -(1 <<< (W-1));
    assign y = (s > SMAX) ? SMAX[W-1:0] : (s < SMIN) ? SMIN[W-1:0] : s[W-1:0];
endmodule

// ------------------------------------------------------------- top level ----
module {name} (
    input  signed [{W-1}:0] x_in,    // Q{fmt.int_bits}.{F}
    output signed [{W-1}:0] y_out    // Q{fmt.int_bits}.{F}
);
{chr(10).join(const_decls) if const_decls else "    // (no folded constants referenced)"}

{chr(10).join(gate_insts)}

    assign y_out = {out_expr};
endmodule
"""

    tb = f"""// Sweep testbench for {name}: prints x_raw,y_raw CSV to stdout.
`timescale 1ns/1ps
module {name}_tb;
    reg  signed [{W-1}:0] x;
    wire signed [{W-1}:0] y;
    {name} dut (.x_in(x), .y_out(y));
    integer i;
    initial begin
        for (i = 0; i < 256; i = i + 1) begin
            x = $signed(i - 128) <<< ({F} - 6);   // sweep ~[-2, 2)
            #1 $display("%0d,%0d", x, y);
        end
        $finish;
    end
endmodule
"""

    rtl_path = os.path.join(out_dir, f"{name}.v")
    tb_path = os.path.join(out_dir, f"{name}_tb.v")
    with open(rtl_path, "w") as f:
        f.write(rtl)
    with open(tb_path, "w") as f:
        f.write(tb)

    return {"rtl": rtl_path, "tb": tb_path,
            "exp_hex": os.path.join(out_dir, exp_hex),
            "ln_hex": os.path.join(out_dir, ln_hex),
            "active_gates": len(active), "total_gates": len(net.gates)}
