"""
Emit an iCEstick board top for a chosen MLP cell (symbolic-vs-MLP study).

Mirrors hardware/rtl/icestick_exp_top.v but bridges the FT2232H UART to an MLP
stream core. The chosen cell is emitted under the fixed module name
`mlp_board_core` (+ `mlp_board_core_stream`) so hardware/build_icestick.py can
keep a static BUILDS entry. The selected cell is recorded in
hardware/rtl/mlp_board_cell.txt for host_demo.py.

MEASURED: *no* exp MLP fits the iCEstick HX1K (~1280 LCs). Even the smallest,
least-accurate cell (1->4->1) places at 1358 LCs (106%). This emitter is therefore
mainly for a UP5K board (iCEBreaker/UPduino, 5280 LCs); on the HX1K the build is
expected to overflow placement -- that non-fit is itself the §5 finding, not a bug.
exp cells use Q8.8 (2 bytes/sample, like exp_d2); the UART bridge is byte-generic.

    python -m mlp.board --func exp --h 8 --depth 1
    python -m hardware.build_icestick --top icestick_mlp_top --flash
    python -m hardware.host_demo --port COMx --model mlp
"""

import argparse
import os

from hardware.verilog_gen_stream import emit_stream_wrapper
from mlp.fixed_point_mlp import QuantMLP, FUNC_FMT, load_cell
from mlp.verilog_gen_mlp import emit_verilog_mlp

HERE = os.path.dirname(os.path.abspath(__file__))
RTL_DIR = os.path.join(os.path.dirname(HERE), "hardware", "rtl")
CORE = "mlp_board_core"
CELL_FILE = os.path.join(RTL_DIR, "mlp_board_cell.txt")

TOP_TEMPLATE = """// Generated by mlp/board.py -- do not edit by hand.
// iCEstick (iCE40-HX1K) board top for an MLP function core ({cell}).
// Same FT2232H channel-B UART bridge as icestick_exp_top.v, instantiating the
// {core}_stream core. Protocol: {nbytes} byte(s) little-endian per sample, both
// directions (Q{intb}.{fracb} codes, output sign-extended). LED toggles per result.
// 12 MHz oscillator, 115200 baud => CLKS_PER_BIT = 104.
module icestick_mlp_top #(parameter CPB = 104) (
    input  wire clk,
    input  wire rx,
    output wire tx,
    output wire led
);
    wire [7:0] rx_byte;
    wire       rx_valid;
    uart_rx #(.CLKS_PER_BIT(CPB)) u_rx (
        .clk(clk), .rx(rx), .data(rx_byte), .valid(rx_valid)
    );

    wire [7:0] core_out;
    wire       core_out_valid;
    {core}_stream u_core (
        .clk(clk),
        .in_data(rx_byte), .in_valid(rx_valid),
        .out_data(core_out), .out_valid(core_out_valid)
    );

    reg [7:0] fifo [0:3];
    reg [1:0] wr_ptr = 2'd0;
    reg [1:0] rd_ptr = 2'd0;
    always @(posedge clk)
        if (core_out_valid) begin fifo[wr_ptr] <= core_out; wr_ptr <= wr_ptr + 1'b1; end

    wire       tx_busy;
    reg        tx_start = 1'b0;
    reg  [7:0] tx_data  = 8'd0;
    always @(posedge clk) begin
        tx_start <= 1'b0;
        if (!tx_busy && !tx_start && (rd_ptr != wr_ptr)) begin
            tx_data  <= fifo[rd_ptr];
            tx_start <= 1'b1;
            rd_ptr   <= rd_ptr + 1'b1;
        end
    end
    uart_tx #(.CLKS_PER_BIT(CPB)) u_tx (
        .clk(clk), .start(tx_start), .data(tx_data), .tx(tx), .busy(tx_busy)
    );

    reg led_r = 1'b0;
    always @(posedge clk) if (core_out_valid) led_r <= ~led_r;
    assign led = led_r;
endmodule
"""


def emit_board(func: str, hidden: int, depth: int) -> dict:
    layers, _ = load_cell(func, hidden, depth)
    fmt = FUNC_FMT[func]
    qm = QuantMLP(layers, fmt)
    info = emit_verilog_mlp(qm, CORE, RTL_DIR)             # fixed name mlp_board_core
    winfo = emit_stream_wrapper(CORE, fmt, info["latency"], RTL_DIR)
    cell = f"{func}_h{hidden}_d{depth}"
    top = TOP_TEMPLATE.format(cell=cell, core=CORE, nbytes=winfo["bytes_per_sample"],
                              intb=fmt.int_bits, fracb=fmt.frac_bits)
    with open(os.path.join(RTL_DIR, "icestick_mlp_top.v"), "w") as f:
        f.write(top)
    with open(CELL_FILE, "w") as f:
        f.write(f"{func} {hidden} {depth}\n")
    print(f"board top -> icestick_mlp_top.v  core={cell}  "
          f"{winfo['bytes_per_sample']} B/sample, latency {info['latency']}")
    print("next: python -m hardware.build_icestick --top icestick_mlp_top --flash")
    return {"cell": cell, "bytes_per_sample": winfo["bytes_per_sample"]}


def main():
    ap = argparse.ArgumentParser(description="Emit iCEstick board top for an MLP cell")
    ap.add_argument("--func", default="exp", choices=list(FUNC_FMT))
    ap.add_argument("--h", type=int, default=8)
    ap.add_argument("--depth", type=int, default=1)
    args = ap.parse_args()
    emit_board(args.func, args.h, args.depth)


if __name__ == "__main__":
    main()
