"""
Synthesis half of the arity experiment: drive the 2-input symbolic unit through
the SAME golden-model -> Icarus -> yosys/nextpnr pipeline as every other Track C
function unit, so its placed area is comparable to the single-input stream rows.

Steps (requires OSS CAD Suite: iverilog, yosys, nextpnr-ice40 on PATH):
  1. emit the combinational core (mlp/symbolic_2in.py) + a 2-input byte-serial
     stream wrapper (hardware/verilog_gen_stream.py::emit_stream_wrapper_2in);
  2. bit-exact check: feed a 256-point (x,y) sweep through Icarus and diff every
     output against hardware/fixed_point.py::FixedEML.eml_fix;
  3. synth: yosys synth_ice40 -> nextpnr-ice40 UP5K sg48 (19-pin wrapper), parse
     ICESTORM_LC / RAM / routed Fmax.

    python -m mlp.run_2in            # emit + sim-check + synth, print a result row
    python -m mlp.run_2in --no-synth # emit + sim-check only (no yosys/nextpnr)
"""

import argparse
import os
import re
import subprocess
import sys

from hardware.fixed_point import FixedEML
from hardware.verilog_gen_stream import emit_stream_wrapper_2in
from mlp.symbolic_2in import (DEFAULT_FMT, emit_symbolic_2in_verilog,
                              error_report, X_DOMAIN, Y_DOMAIN)

HERE = os.path.dirname(os.path.abspath(__file__))
RTL_DIR = os.path.join(os.path.dirname(HERE), "hardware", "rtl")
DEVICE = ("--up5k", "--package", "sg48")
CORE = "symbolic_exp_ln_2in"


def _sweep_raws(fmt, n=256):
    """Deterministic 256-point (x_raw, y_raw) sweep spanning both domains."""
    f6 = fmt.frac_bits - 6
    raws = []
    for i in range(n):
        x_raw = (i - 128) << f6                 # ~[-2, 2)
        y_raw = ((i >> 1) + 7) << f6            # ~[0.1, 10), strictly > 0
        raws.append((fmt.saturate(x_raw), fmt.saturate(y_raw)))
    return raws


def _emit_stream_tb(name, fmt, raws):
    """2-input stream tb: feed NIN bytes x then NIN bytes y per result, print CSV."""
    W = fmt.total_bits
    n = (W + 7) // 8
    wb = 8 * n
    lines = "\n".join(f"        xq[{i}]={x}; yq[{i}]={y};" for i, (x, y) in enumerate(raws))
    tb = f"""// Generated by mlp/run_2in.py -- 2-input stream bit-exact tb.
`timescale 1ns/1ps
module {name}_tb;
    localparam W = {W}, NIN = {n};
    reg clk = 0;
    always #5 clk = ~clk;
    reg [7:0] in_data = 0;
    reg in_valid = 0;
    wire [7:0] out_data;
    wire out_valid;
    {name} dut (.clk(clk), .in_data(in_data), .in_valid(in_valid),
                .out_data(out_data), .out_valid(out_valid));

    reg signed [W-1:0] xq [0:255];
    reg signed [W-1:0] yq [0:255];
    reg [{wb}-1:0] acc = 0;
    integer acc_n = 0, recv = 0;
    reg signed [W-1:0] yv;
    always @(posedge clk) begin
        #1;
        if (out_valid) begin
            acc = {{out_data, acc[{wb}-1:8]}};
            acc_n = acc_n + 1;
            if (acc_n == NIN) begin
                yv = acc[W-1:0];
                $display("%0d,%0d,%0d", xq[recv], yq[recv], yv);
                recv = recv + 1; acc_n = 0;
                if (recv == 256) $finish;
            end
        end
    end

    integer i, b;
    reg [{wb}-1:0] xext, yext;
    initial begin
{lines}
        for (i = 0; i < 256; i = i + 1) begin
            xext = {{{{({wb}-W){{xq[i][W-1]}}}}, xq[i]}};
            yext = {{{{({wb}-W){{yq[i][W-1]}}}}, yq[i]}};
            for (b = 0; b < NIN; b = b + 1) begin
                @(negedge clk); in_data = xext[8*b +: 8]; in_valid = 1;
            end
            for (b = 0; b < NIN; b = b + 1) begin
                @(negedge clk); in_data = yext[8*b +: 8]; in_valid = 1;
            end
        end
        @(negedge clk); in_valid = 0;
        repeat (400) @(posedge clk);
        $display("TIMEOUT: only %0d results", recv);
        $finish;
    end
endmodule
"""
    with open(os.path.join(RTL_DIR, f"{name}_tb.v"), "w") as f:
        f.write(tb)


def sim_check(fmt=DEFAULT_FMT) -> int:
    """Bit-exact: 256-point (x,y) sweep through Icarus vs FixedEML.eml_fix."""
    fe = FixedEML(fmt)
    raws = _sweep_raws(fmt)
    stream = f"{CORE}_stream"
    emit_stream_wrapper_2in(CORE, fmt, RTL_DIR)
    _emit_stream_tb(stream, fmt, raws)

    sim = os.path.join(RTL_DIR, f"{stream}_sim")
    subprocess.run(["iverilog", "-g2012", "-o", sim, f"{stream}.v", f"{stream}_tb.v",
                    f"{CORE}.v"], cwd=RTL_DIR, check=True)
    out = subprocess.run(["vvp", sim], cwd=RTL_DIR, check=True,
                         capture_output=True, text=True).stdout
    mismatches = n = 0
    for line in out.strip().splitlines():
        parts = line.split(",")
        if len(parts) != 3:
            continue
        x_raw, y_raw, y_rtl = int(parts[0]), int(parts[1]), int(parts[2])
        y_py = fe.eml_fix(x_raw, y_raw)
        n += 1
        if y_rtl != y_py:
            mismatches += 1
            if mismatches <= 5:
                print(f"  MISMATCH: x={x_raw} y={y_raw} rtl={y_rtl} py={y_py}")
    status = "BIT-EXACT" if mismatches == 0 and n == 256 else f"{mismatches} mismatch / {n} pts"
    print(f"{stream}: {n} points, {status}")
    return mismatches + (256 - n)


def _grep_int(pat, text, default=0):
    m = re.search(pat, text)
    return int(m.group(1)) if m else default


def synth(fmt=DEFAULT_FMT) -> dict:
    """yosys synth_ice40 -> nextpnr-ice40 UP5K sg48 on the 19-pin stream wrapper."""
    top = f"{CORE}_stream"
    subprocess.run(["yosys", "-q", "-p", f"synth_ice40 -top {top} -json {top}.json; stat",
                    f"{CORE}.v", f"{top}.v"], cwd=RTL_DIR, check=True,
                   capture_output=True, text=True, timeout=3600)
    pnr = subprocess.run(["nextpnr-ice40", *DEVICE, "--json", f"{top}.json", "--freq", "12"],
                         cwd=RTL_DIR, capture_output=True, text=True, timeout=600)
    log = pnr.stdout + pnr.stderr
    lcs = _grep_int(r"ICESTORM_LC:\s*(\d+)/", log, default=None)
    ebr = _grep_int(r"ICESTORM_RAM:\s*(\d+)/", log)
    fm = re.search(r"Max frequency for clock '[^']*':\s*([\d.]+)\s*MHz", log)
    fmax = round(float(fm.group(1)), 1) if fm else None
    return {"lcs": lcs, "ebr": ebr, "fmax_mhz": fmax}


    # ----------------------------------------------------------------------- #
    # 2-input MLP baseline (third corner of the arity comparison)
    # ----------------------------------------------------------------------- #


def train_mlp_2in(hidden, depth, fmt=DEFAULT_FMT, seeds=8, epochs=3000, n_side=64):
    """Train a 2-input MLP for f(x,y)=exp(x)-ln(y); best-of-seeds by grid max-err.

    Returns (layers, float_maxerr). Mirrors mlp/train_mlp.py (Adam + cosine LR,
    best-of-N), but with input dim 2 on a 2-D training grid over the same domains.
    """
    import numpy as np
    import torch
    import torch.nn as nn

    (xlo, xhi), (ylo, yhi) = X_DOMAIN, Y_DOMAIN
    gx = torch.linspace(xlo, xhi, n_side)
    gy = torch.linspace(ylo, yhi, n_side)
    XX, YY = torch.meshgrid(gx, gy, indexing="ij")
    inp = torch.stack([XX.reshape(-1), YY.reshape(-1)], dim=1)
    tgt = (torch.exp(inp[:, 0]) - torch.log(inp[:, 1])).unsqueeze(1)

    def build():
        layers = [nn.Linear(2, hidden), nn.ReLU()]
        for _ in range(depth - 1):
            layers += [nn.Linear(hidden, hidden), nn.ReLU()]
        layers += [nn.Linear(hidden, 1)]
        return nn.Sequential(*layers)

    best = None
    for seed in range(seeds):
        torch.manual_seed(seed)
        net = build()
        opt = torch.optim.Adam(net.parameters(), lr=5e-3)
        sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, epochs)
        lossf = nn.MSELoss()
        for _ in range(epochs):
            opt.zero_grad(); loss = lossf(net(inp), tgt); loss.backward()
            opt.step(); sched.step()
        with torch.no_grad():
            maxerr = (net(inp) - tgt).abs().max().item()
        if best is None or maxerr < best[0]:
            layers = [(m.weight.detach().numpy().astype(np.float64),
                       m.bias.detach().numpy().astype(np.float64))
                      for m in net if isinstance(m, nn.Linear)]
            best = (maxerr, layers)
    return best[1], best[0]


def mlp_2in_fp_maxerr(qm, npts=129):
    (xlo, xhi), (ylo, yhi) = X_DOMAIN, Y_DOMAIN
    import math
    worst = 0.0
    for i in range(npts):
        x = xlo + i * (xhi - xlo) / (npts - 1)
        xr = qm.fmt.quantize(x)
        for j in range(npts):
            y = ylo + j * (yhi - ylo) / (npts - 1)
            got = qm.fmt.dequantize(qm.forward_raw(xr, qm.fmt.quantize(y)))
            worst = max(worst, abs(got - (math.exp(x) - math.log(y))))
    return worst


def run_mlp_2in(hidden, depth, fmt=DEFAULT_FMT, do_synth=True):
    """Train, emit, bit-exact check, and synthesize a 2-input MLP cell."""
    from mlp.fixed_point_mlp import QuantMLP
    from mlp.verilog_gen_mlp import emit_verilog_mlp

    layers, fmaxerr = train_mlp_2in(hidden, depth, fmt)
    qm = QuantMLP(layers, fmt)
    name = f"mlp2_exp_ln_h{hidden}_d{depth}"
    emit_verilog_mlp(qm, name, RTL_DIR, inputs=("x_in", "y_in"), emit_tb=False)

    # bit-exact check on the stream wrapper (core_latency = #Linear layers)
    lat = len(qm.layers)
    emit_stream_wrapper_2in(name, fmt, RTL_DIR, core_latency=lat)
    raws = _sweep_raws(fmt)
    stream = f"{name}_stream"
    _emit_stream_tb(stream, fmt, raws)
    sim = os.path.join(RTL_DIR, f"{stream}_sim")
    subprocess.run(["iverilog", "-g2012", "-o", sim, f"{stream}.v", f"{stream}_tb.v",
                    f"{name}.v"], cwd=RTL_DIR, check=True)
    out = subprocess.run(["vvp", sim], cwd=RTL_DIR, check=True,
                         capture_output=True, text=True).stdout
    mm = n = 0
    for line in out.strip().splitlines():
        p = line.split(",")
        if len(p) != 3:
            continue
        n += 1
        if int(p[2]) != qm.forward_raw(int(p[0]), int(p[1])):
            mm += 1
    fpmax = mlp_2in_fp_maxerr(qm)
    print(f"{stream}: {n}/256 {'BIT-EXACT' if mm == 0 and n == 256 else f'{mm} mism'}, "
          f"fp max-err {fpmax:.4f} (float {fmaxerr:.4f})")
    res = {"name": name, "hidden": hidden, "depth": depth, "fp_maxerr": fpmax,
           "bit_exact": mm == 0 and n == 256}
    if do_synth:
        top = stream
        subprocess.run(["yosys", "-q", "-p",
                        f"synth_ice40 -top {top} -json {top}.json; stat",
                        f"{name}.v", f"{top}.v"], cwd=RTL_DIR, check=True,
                       capture_output=True, text=True, timeout=3600)
        pnr = subprocess.run(["nextpnr-ice40", *DEVICE, "--json", f"{top}.json",
                              "--freq", "12"], cwd=RTL_DIR, capture_output=True,
                             text=True, timeout=600)
        log = pnr.stdout + pnr.stderr
        res["lcs"] = _grep_int(r"ICESTORM_LC:\s*(\d+)/", log, default=None)
        res["fmax_mhz"] = (lambda m: round(float(m.group(1)), 1) if m else None)(
            re.search(r"Max frequency for clock '[^']*':\s*([\d.]+)\s*MHz", log))
        print(f"  PLACED: {res['lcs']} LC, {res['fmax_mhz']} MHz (UP5K sg48)")
    return res


def main():
    ap = argparse.ArgumentParser(description="Synthesis half of the 2-input arity experiment")
    ap.add_argument("--no-synth", action="store_true", help="emit + sim-check only")
    ap.add_argument("--mlp", action="store_true",
                    help="also train+synth 2-input MLP baselines (h8/h16 d1)")
    args = ap.parse_args()

    info = emit_symbolic_2in_verilog(out_dir=RTL_DIR)
    er = error_report()
    print(f"2-input symbolic unit exp(x)-ln(y) on x{X_DOMAIN} y{Y_DOMAIN}")
    print(f"  emitted: {os.path.relpath(info['rtl'])}")
    print(f"  fp max-err: {er['fp_maxerr']:.5f}  storage: {er['lut_entries']} entries")

    mm = sim_check()
    if mm:
        sys.exit(f"FAILED: {mm} mismatch(es) -- RTL diverges from the golden model")

    if not args.no_synth:
        r = synth()
        fits = {"hx1k": 1280, "up5k": 5280, "hx8k": 7680}
        smallest = next((d for d, c in fits.items() if r["lcs"] and r["lcs"] <= c), "none")
        print(f"  PLACED: {r['lcs']} LC, {r['ebr']} EBR, {r['fmax_mhz']} MHz "
              f"(UP5K sg48); smallest iCE40 = {smallest}")

    if args.mlp:
        print("\n2-input MLP baselines f(x,y)=exp(x)-ln(y):")
        for h, d in ((8, 1), (16, 1)):
            run_mlp_2in(h, d, do_synth=not args.no_synth)


if __name__ == "__main__":
    main()
