"""
2-input symbolic function unit for the arity experiment (referee hole #2, scope).

The native EML operator is itself a 2-input function: eml(a, b) = exp(a) - ln(b).
A depth-1 snapped tree that routes BOTH external inputs -- x to the exp leg, y to
the ln leg -- computes f(x, y) = exp(x) - ln(y) with no soft mixing left. So the
"2-input symbolic unit" needs no new symbolic-regression run: it is the raw gate,
and its datapath is exactly the two already-verified single-input LUT legs (the
257-entry interpolated exp LUT and the range-reduced ln) plus one saturating
subtract. hardware/fixed_point.py::FixedEML.eml_fix already IS the bit-exact golden
model; this module wraps it for a 2-D error report and emits a 2-input top that
reuses hardware/verilog_gen.py::emit_core_modules (one source for the exp/ln RTL).

The point of the experiment (see notes/symbolic_function_units_note.md sec 4.3/7):
the symbolic unit's cost is ADDITIVE in arity -- it is the sum of the per-input
legs, independent of the input wordlength's contribution to a table -- whereas a
direct ROM over the same two inputs is MULTIPLICATIVE (entries = 2^(Wx+Wy)). This
file produces the symbolic side of that comparison; mlp/rom_baseline.py (2-D) the
ROM side. No FPGA toolchain is needed for the golden models, error reports, or RTL
emission here; only the later synthesis sweep needs yosys/nextpnr.
"""

import math
import os

from hardware.fixed_point import FixedEML, FixedPointFormat, LUT_BITS
from hardware.verilog_gen import emit_core_modules, _hex_lines

# Same scalar domains the single-input units were recovered/measured on.
X_DOMAIN = (-2.0, 2.0)      # exp leg
Y_DOMAIN = (0.1, 10.0)      # ln leg

# One unified Q-format for the fused datapath (the native gate uses a single
# format throughout). Q8.8 matches the exp unit; the ln leg gives up its Q10.12
# precision -- the honest cost of a single shared wordlength, reported as such.
DEFAULT_FMT = FixedPointFormat(8, 8)


def true_fn(x: float, y: float) -> float:
    return math.exp(x) - math.log(y)


def error_report(fmt: FixedPointFormat = DEFAULT_FMT, npts: int = 129) -> dict:
    """Fixed-point max-err / MAE of exp(x)-ln(y) vs truth over the 2-D grid."""
    fe = FixedEML(fmt)
    xs = [X_DOMAIN[0] + i * (X_DOMAIN[1] - X_DOMAIN[0]) / (npts - 1) for i in range(npts)]
    ys = [Y_DOMAIN[0] + i * (Y_DOMAIN[1] - Y_DOMAIN[0]) / (npts - 1) for i in range(npts)]
    errs = []
    for x in xs:
        xr = fmt.quantize(x)
        for y in ys:
            yr = fmt.quantize(y)
            got = fmt.dequantize(fe.eml_fix(xr, yr))
            errs.append(abs(got - true_fn(x, y)))
    return {"unit": "symbolic exp(x)-ln(y)", "fmt": repr(fmt),
            "fp_mae": sum(errs) / len(errs), "fp_maxerr": max(errs),
            "n_grid": npts * npts,
            # the symbolic unit stores two 257-entry LUTs regardless of input width
            "lut_entries": 2 * ((1 << LUT_BITS) + 1)}


def emit_symbolic_2in_verilog(fmt: FixedPointFormat = DEFAULT_FMT,
                              name: str = "symbolic_exp_ln_2in",
                              out_dir: str = None) -> dict:
    """Emit the 2-input symbolic core (.v + two .hex + delay-matched tb).

    Top port shape mirrors the ROM/MLP 2-input cores so the same wrapper and
    sim_check drive all three: (.x_in, .y_in, .y_out), combinational core.
    """
    fe = FixedEML(fmt)
    W, F = fmt.total_bits, fmt.frac_bits
    out_dir = out_dir or os.path.join(os.path.dirname(os.path.dirname(__file__)),
                                      "hardware", "rtl")
    os.makedirs(out_dir, exist_ok=True)

    exp_hex = f"{name}_exp_lut.hex"
    ln_hex = f"{name}_ln_lut.hex"
    with open(os.path.join(out_dir, exp_hex), "w") as f:
        f.write(_hex_lines(fe.exp_lut, W))
    with open(os.path.join(out_dir, ln_hex), "w") as f:
        f.write(_hex_lines(fe.ln_lut, W))

    rtl = f"""// Generated by mlp/symbolic_2in.py -- do not edit by hand.
// 2-input symbolic unit: f(x,y) = exp(x) - ln(y), the native EML gate at arity 2.
// Format Q{fmt.int_bits}.{F} ({W} bits). Datapath = two interpolated LUT legs +
// saturating subtract (ADDITIVE in arity; cf. the 2-D ROM in mlp/rom_baseline.py,
// whose size is MULTIPLICATIVE: 2^(Wx+Wy) entries).

{emit_core_modules(fe, exp_hex, ln_hex)}
// ------------------------------------------------------------- top level ----
module {name} (
    input  signed [{W-1}:0] x_in,    // Q{fmt.int_bits}.{F}, exp leg
    input  signed [{W-1}:0] y_in,    // Q{fmt.int_bits}.{F}, ln  leg
    output signed [{W-1}:0] y_out    // Q{fmt.int_bits}.{F}
);
    eml_gate #(.W({W}), .F({F})) u_gate (.a(x_in), .b(y_in), .y(y_out));
endmodule
"""

    tb = f"""// Diagonal sweep tb for {name}: prints x_raw,y_raw,out_raw CSV.
`timescale 1ns/1ps
module {name}_tb;
    reg  signed [{W-1}:0] x, y;
    wire signed [{W-1}:0] o;
    {name} dut (.x_in(x), .y_in(y), .y_out(o));
    integer i;
    initial begin
        for (i = 0; i < 256; i = i + 1) begin
            x = $signed(i - 128) <<< ({F} - 6);          // ~[-2, 2)
            y = $signed((i >> 1) + 7) <<< ({F} - 6);     // ~[0.1, 10), strictly > 0
            #1 $display("%0d,%0d,%0d", x, y, o);
        end
        $finish;
    end
endmodule
"""

    rtl_path = os.path.join(out_dir, f"{name}.v")
    tb_path = os.path.join(out_dir, f"{name}_tb.v")
    with open(rtl_path, "w") as f:
        f.write(rtl)
    with open(tb_path, "w") as f:
        f.write(tb)
    return {"rtl": rtl_path, "tb": tb_path, "exp_hex": exp_hex, "ln_hex": ln_hex,
            "name": name, "latency": 0, "fmt": fmt}


if __name__ == "__main__":
    r = error_report()
    print("2-input symbolic unit  f(x,y) = exp(x) - ln(y)")
    print(f"  format     : {r['fmt']}")
    print(f"  grid       : {r['n_grid']} points")
    print(f"  fp MAE     : {r['fp_mae']:.6f}")
    print(f"  fp max-err : {r['fp_maxerr']:.6f}")
    print(f"  storage    : {r['lut_entries']} LUT entries (2 x 257), "
          f"independent of input wordlength")
    info = emit_symbolic_2in_verilog()
    print(f"  emitted    : {os.path.relpath(info['rtl'])} "
          f"(+ {info['exp_hex']}, {info['ln_hex']}, tb)")
