"""
Pipelined fixed-point MLP -> iCE40 RTL (symbolic-vs-MLP study).

Emits a fully-parallel, fully-streaming core: weights are RTL constants (the
MLPs are tiny -- no ROM/EBR needed), each Linear layer is one pipeline stage
(parallel signed MACs -> arithmetic requant shift -> bias -> saturate, plus
ReLU on hidden layers). Port shape matches the snapped-EML pipelined cores
(.clk, .x_in[W-1:0], .y_out[W-1:0]) so hardware/verilog_gen_stream.py wraps it
unchanged and hardware/sim_check.py diffs it the same way.

The per-neuron integer arithmetic is operation-identical to
mlp/fixed_point_mlp.py::QuantMLP, so sim_check verifies RTL == that golden
model bit-for-bit (one sample per clock, latency = #Linear layers).
"""

import os

from hardware.fixed_point import FixedPointFormat
from mlp.fixed_point_mlp import QuantMLP


def emit_verilog_mlp(qm: QuantMLP, name: str, out_dir: str) -> dict:
    fmt = qm.fmt
    W, F = fmt.total_bits, fmt.frac_bits
    ACC = 2 * W + 8                       # wide enough: no overflow before requant
    rawmax = (1 << (W - 1)) - 1
    rawmin = -(1 << (W - 1))
    os.makedirs(out_dir, exist_ok=True)
    n_layers = len(qm.layers)
    latency = n_layers

    body = []
    prev = ["x_in"]                        # layer 0 fans in from the single input
    for li, (w_raw, b_raw) in enumerate(qm.layers):
        relu = li < n_layers - 1
        nout = len(b_raw)
        body.append(f"    // ---- layer {li} ({'ReLU' if relu else 'linear out'}): "
                    f"{len(prev)} -> {nout} ----")
        outs = []
        for j in range(nout):
            terms = " + ".join(
                f"$signed({W}'sd{w_raw[j][k]}) * $signed({prev[k]})"
                if w_raw[j][k] >= 0 else
                f"$signed(-{W}'sd{-w_raw[j][k]}) * $signed({prev[k]})"
                for k in range(len(prev)))
            acc = f"acc{li}_{j}"
            pre = f"pre{li}_{j}"
            reg = f"a{li}_{j}"
            body.append(f"    wire signed [{ACC-1}:0] {acc} = {terms};")
            body.append(f"    wire signed [{ACC-1}:0] {pre} = ({acc} >>> {F}) "
                        f"+ $signed({W}'sd{b_raw[j]});" if b_raw[j] >= 0 else
                        f"    wire signed [{ACC-1}:0] {pre} = ({acc} >>> {F}) "
                        f"+ $signed(-{W}'sd{-b_raw[j]});")
            body.append(f"    reg signed [{W-1}:0] {reg};")
            # Saturation bounds as plain (unsized, 32-bit signed) decimals: this
            # avoids the W'sd<2^(W-1)> width-overflow trap for rawmin, and the
            # truncating assignment to the W-bit reg yields the right two's complement.
            if relu:
                body.append(
                    f"    always @(posedge clk) {reg} <= "
                    f"({pre} <= 0) ? {W}'sd0 : "
                    f"({pre} > {rawmax}) ? {rawmax} : {pre}[{W-1}:0];")
            else:
                body.append(
                    f"    always @(posedge clk) {reg} <= "
                    f"({pre} > {rawmax}) ? {rawmax} : "
                    f"({pre} < {rawmin}) ? {rawmin} : {pre}[{W-1}:0];")
            outs.append(reg)
        body.append("")
        prev = outs

    rtl = f"""// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP '{name}': {n_layers} Linear layers, latency {latency} cycles,
// fully streaming (one sample per clock). Format Q{fmt.int_bits}.{F} ({W} bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module {name} (
    input clk,
    input  signed [{W-1}:0] x_in,    // Q{fmt.int_bits}.{F}, one sample per clock
    output signed [{W-1}:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = {latency};

{chr(10).join(body)}    assign y_out = {prev[0]};
endmodule
"""

    # Same delay-matched testbench shape as the pipelined EML cores so sim_check
    # parses identical "x_raw,y_raw" CSV lines.
    tb = f"""// Streaming testbench for {name}: prints x_raw,y_raw CSV (delay-matched).
`timescale 1ns/1ps
module {name}_tb;
    localparam LAT = {latency};
    reg clk = 0;
    always #5 clk = ~clk;
    reg signed [{W-1}:0] x = 0;
    wire signed [{W-1}:0] y;
    {name} dut (.clk(clk), .x_in(x), .y_out(y));

    reg signed [{W-1}:0] xd [0:LAT-1];
    integer j;
    always @(posedge clk) begin
        xd[0] <= x;
        for (j = LAT-1; j > 0; j = j - 1) xd[j] <= xd[j-1];
    end

    integer i;
    initial begin
        for (i = 0; i < 256 + LAT; i = i + 1) begin
            x = $signed((i < 256 ? i : 255) - 128) <<< ({F} - 6);
            @(posedge clk); #1;
            if (i >= LAT - 1 && i <= 255 + LAT - 1)
                $display("%0d,%0d", xd[LAT-1], y);
        end
        $finish;
    end
endmodule
"""

    rtl_path = os.path.join(out_dir, f"{name}.v")
    tb_path = os.path.join(out_dir, f"{name}_tb.v")
    with open(rtl_path, "w") as f:
        f.write(rtl)
    with open(tb_path, "w") as f:
        f.write(tb)
    return {"rtl": rtl_path, "tb": tb_path, "name": name,
            "latency": latency, "n_layers": n_layers}
