// Generated by hardware/verilog_gen.py -- do not edit by hand.
// Snapped EML tree 'csv_ln_f1': 3 active gate(s) of 3 total
// Format Q10.12 (22 bits). eml(a,b) = exp(clamp(a,-8,8)) - ln(b).

// ---------------------------------------------------------------- exp(a) ----
module eml_exp #(parameter W = 22, parameter F = 12) (
    input  signed [W-1:0] a,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 8;
    localparam signed [W-1:0] XMIN = -(8 <<< F), XMAX = (8 <<< F);

    reg signed [W-1:0] lut [0:(1<<LUTB)];
    initial $readmemh("csv_ln_f1_exp_lut.hex", lut);

    wire signed [W-1:0] r = (a < XMIN) ? XMIN : (a > XMAX) ? XMAX : a;
    wire [W:0] u = r - XMIN;                       // 0 .. 2^(F+4), needs W+1 bits
    wire [LUTB:0] idx = u >> (F - 4);              // 0 .. 256
    wire [IB-1:0] fr = u >> (F - 4 - IB);
    wire signed [W-1:0] y0 = lut[idx];
    wire signed [W-1:0] y1 = (idx >= (1 << LUTB)) ? lut[1 << LUTB] : lut[idx + 1];
    wire signed [W+IB:0] d = (y1 - y0) * $signed({1'b0, fr});
    assign y = (idx >= (1 << LUTB)) ? lut[1 << LUTB] : y0 + (d >>> IB);
endmodule

// ----------------------------------------------------------------- ln(b) ----
// ln(m * 2^k) = ln_lut[m] + k*ln2, m in [1,2) via leading-one detect.
module eml_ln #(parameter W = 22, parameter F = 12) (
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 8;
    localparam signed [W-1:0] LN2 = 22'sd2839;

    reg signed [W-1:0] lut [0:(1<<LUTB)];
    initial $readmemh("csv_ln_f1_ln_lut.hex", lut);

    wire [W-1:0] r = (b <= 0) ? 22'd1 : b[W-1:0];   // clamp to smallest positive

    // leading-one position p
    integer i;
    reg [$clog2(W)-1:0] p;
    always @* begin
        p = 0;
        for (i = 0; i < W; i = i + 1)
            if (r[i]) p = i[$clog2(W)-1:0];
    end

    // top LUTB+IB mantissa bits below the leading one
    wire [2*W-1:0] rext = r;
    wire [2*W-1:0] shifted = (rext << W) >> p;       // mantissa fraction in bits [W-1:0]
    wire [LUTB+IB-1:0] mant = shifted[W-1 -: LUTB+IB];
    wire [LUTB-1:0] idx = mant[LUTB+IB-1:IB];
    wire [IB-1:0] fr = mant[IB-1:0];

    wire signed [W-1:0] y0 = lut[idx];
    wire signed [W-1:0] y1 = lut[idx + 1];
    wire signed [W+IB:0] d = (y1 - y0) * $signed({1'b0, fr});
    wire signed [W-1:0] ln_m = y0 + (d >>> IB);

    wire signed [$clog2(W):0] k = $signed({1'b0, p}) - F;
    assign y = ln_m + k * LN2;
endmodule

// -------------------------------------------------------------- eml gate ----
module eml_gate #(parameter W = 22, parameter F = 12) (
    input  signed [W-1:0] a,
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    wire signed [W-1:0] ea, lb;
    eml_exp #(.W(W), .F(F)) u_exp (.a(a), .y(ea));
    eml_ln  #(.W(W), .F(F)) u_ln  (.b(b), .y(lb));
    wire signed [W:0] s = ea - lb;
    localparam signed [W:0] SMAX = (1 <<< (W-1)) - 1, SMIN = -(1 <<< (W-1));
    assign y = (s > SMAX) ? SMAX[W-1:0] : (s < SMIN) ? SMIN[W-1:0] : s[W-1:0];
endmodule

// ------------------------------------------------------------- top level ----
module csv_ln_f1 (
    input  signed [21:0] x_in,    // Q10.12
    output signed [21:0] y_out    // Q10.12
);
    // (no folded constants referenced)

    wire signed [21:0] g0_out;
    eml_gate #(.W(22), .F(12)) u_g0 (
        .a(22'sd4096),
        .b(x_in),
        .y(g0_out)
    );
    wire signed [21:0] g1_out;
    eml_gate #(.W(22), .F(12)) u_g1 (
        .a(g0_out),
        .b(22'sd4096),
        .y(g1_out)
    );
    wire signed [21:0] g2_out;
    eml_gate #(.W(22), .F(12)) u_g2 (
        .a(22'sd4096),
        .b(g1_out),
        .y(g2_out)
    );

    assign y_out = g2_out;
endmodule
