// Generated by hardware/verilog_gen_pipelined.py -- do not edit by hand.
// Pipelined snapped EML tree 'exp_d2_pipe': 1 gate(s), latency 3 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// ROM reads are registered so yosys synth_ice40 infers EBR (sync read required).

// ------------------------------------------------- exp(a), 2-cycle latency ----
module eml_exp_p #(parameter W = 16, parameter F = 8) (
    input clk,
    input  signed [W-1:0] a,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 4;
    localparam signed [W-1:0] XMIN = -(8 <<< F), XMAX = (8 <<< F);
    localparam signed [W-1:0] EP = 16'sd32767;  // exp(8) endpoint (entry 256)

    reg signed [W-1:0] lutA [0:255];  // entries 0..255
    reg signed [W-1:0] lutB [0:255];  // entries 1..256 (y1 = lutB[idx])
    initial $readmemh("exp_d2_pipe_exp_lut_a.hex", lutA);
    initial $readmemh("exp_d2_pipe_exp_lut_b.hex", lutB);

    wire signed [W-1:0] r = (a < XMIN) ? XMIN : (a > XMAX) ? XMAX : a;
    wire [W:0] u = r - XMIN;
    wire [LUTB:0] idx = u >> (F - 4);
    wire [IB-1:0] fr = u >> (F - 4 - IB);
    wire top = (idx >= (1 << LUTB));

    // stage 1: synchronous ROM read (EBR)
    reg signed [W-1:0] qA, qB;
    reg [IB-1:0] fr_r;
    reg top_r;
    always @(posedge clk) begin
        qA <= lutA[idx[LUTB-1:0]];
        qB <= lutB[idx[LUTB-1:0]];
        fr_r <= fr;
        top_r <= top;
    end

    // stage 2: interpolate (+ saturate, mirroring fixed_point.exp_fix)
    wire signed [W+IB:0] d = (qB - qA) * $signed({1'b0, fr_r});
    wire signed [W+1:0] s = qA + (d >>> IB);
    localparam signed [W+1:0] PMAX = (1 <<< (W-1)) - 1, PMIN = -(1 <<< (W-1));
    reg signed [W-1:0] y_r;
    always @(posedge clk)
        y_r <= top_r ? EP :
               (s > PMAX) ? PMAX[W-1:0] : (s < PMIN) ? PMIN[W-1:0] : s[W-1:0];
    assign y = y_r;
endmodule

// -------------------------------------------------- ln(b), 2-cycle latency ----
module eml_ln_p #(parameter W = 16, parameter F = 8) (
    input clk,
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 4;
    localparam signed [W-1:0] LN2 = 16'sd177;

    reg signed [W-1:0] lutA [0:255];  // ln(1 + i/256), entries 0..255
    reg signed [W-1:0] lutB [0:255];  // entries 1..256 (entry 256 = ln(2))
    initial $readmemh("exp_d2_pipe_ln_lut_a.hex", lutA);
    initial $readmemh("exp_d2_pipe_ln_lut_b.hex", lutB);

    wire [W-1:0] r = (b <= 0) ? 16'd1 : b[W-1:0];

    integer i;
    reg [$clog2(W)-1:0] p;
    always @* begin
        p = 0;
        for (i = 0; i < W; i = i + 1)
            if (r[i]) p = i[$clog2(W)-1:0];
    end

    wire [2*W-1:0] rext = r;
    wire [2*W-1:0] shifted = (rext << W) >> p;
    wire [LUTB+IB-1:0] mant = shifted[W-1 -: LUTB+IB];
    wire [LUTB-1:0] idx = mant[LUTB+IB-1:IB];
    wire [IB-1:0] fr = mant[IB-1:0];
    wire signed [$clog2(W):0] k = $signed({1'b0, p}) - F;

    // stage 1: synchronous ROM read (EBR)
    reg signed [W-1:0] qA, qB;
    reg [IB-1:0] fr_r;
    reg signed [$clog2(W):0] k_r;
    always @(posedge clk) begin
        qA <= lutA[idx];
        qB <= lutB[idx];
        fr_r <= fr;
        k_r <= k;
    end

    // stage 2: interpolate + k*ln2 (+ saturate, mirroring fixed_point.ln_fix)
    wire signed [W+IB:0] d = (qB - qA) * $signed({1'b0, fr_r});
    wire signed [W-1:0] ln_m = qA + (d >>> IB);
    wire signed [W+6:0] s = ln_m + k_r * LN2;
    localparam signed [W+6:0] PMAX = (1 <<< (W-1)) - 1, PMIN = -(1 <<< (W-1));
    reg signed [W-1:0] y_r;
    always @(posedge clk)
        y_r <= (s > PMAX) ? PMAX[W-1:0] : (s < PMIN) ? PMIN[W-1:0] : s[W-1:0];
    assign y = y_r;
endmodule

// --------------------------------------------- eml gate, 3-cycle latency ----
module eml_gate_p #(parameter W = 16, parameter F = 8) (
    input clk,
    input  signed [W-1:0] a,
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    wire signed [W-1:0] ea, lb;
    eml_exp_p #(.W(W), .F(F)) u_exp (.clk(clk), .a(a), .y(ea));
    eml_ln_p  #(.W(W), .F(F)) u_ln  (.clk(clk), .b(b), .y(lb));
    wire signed [W:0] s = ea - lb;
    localparam signed [W:0] SMAX = (1 <<< (W-1)) - 1, SMIN = -(1 <<< (W-1));
    reg signed [W-1:0] y_r;
    always @(posedge clk)
        y_r <= (s > SMAX) ? SMAX[W-1:0] : (s < SMIN) ? SMIN[W-1:0] : s[W-1:0];
    assign y = y_r;
endmodule

// ------------------------------------------------------------- top level ----
module exp_d2_pipe (
    input clk,
    input  signed [15:0] x_in,    // Q8.8, one sample per clock
    output signed [15:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 3;
    // (no folded constants referenced)


    wire signed [15:0] g0_out;
    eml_gate_p #(.W(16), .F(8)) u_g0 (
        .clk(clk),
        .a(x_in),
        .b(16'sd256),
        .y(g0_out)
    );  // t_in=0 t_out=3

    assign y_out = g0_out;
endmodule
