// Generated by mlp/board.py -- do not edit by hand.
// iCEstick (iCE40-HX1K) board top for an MLP function core (exp_h4_d1).
// Same FT2232H channel-B UART bridge as icestick_exp_top.v, instantiating the
// mlp_board_core_stream core. Protocol: 2 byte(s) little-endian per sample, both
// directions (Q8.8 codes, output sign-extended). LED toggles per result.
// 12 MHz oscillator, 115200 baud => CLKS_PER_BIT = 104.
module icestick_mlp_top #(parameter CPB = 104) (
    input  wire clk,
    input  wire rx,
    output wire tx,
    output wire led
);
    wire [7:0] rx_byte;
    wire       rx_valid;
    uart_rx #(.CLKS_PER_BIT(CPB)) u_rx (
        .clk(clk), .rx(rx), .data(rx_byte), .valid(rx_valid)
    );

    wire [7:0] core_out;
    wire       core_out_valid;
    mlp_board_core_stream u_core (
        .clk(clk),
        .in_data(rx_byte), .in_valid(rx_valid),
        .out_data(core_out), .out_valid(core_out_valid)
    );

    reg [7:0] fifo [0:3];
    reg [1:0] wr_ptr = 2'd0;
    reg [1:0] rd_ptr = 2'd0;
    always @(posedge clk)
        if (core_out_valid) begin fifo[wr_ptr] <= core_out; wr_ptr <= wr_ptr + 1'b1; end

    wire       tx_busy;
    reg        tx_start = 1'b0;
    reg  [7:0] tx_data  = 8'd0;
    always @(posedge clk) begin
        tx_start <= 1'b0;
        if (!tx_busy && !tx_start && (rd_ptr != wr_ptr)) begin
            tx_data  <= fifo[rd_ptr];
            tx_start <= 1'b1;
            rd_ptr   <= rd_ptr + 1'b1;
        end
    end
    uart_tx #(.CLKS_PER_BIT(CPB)) u_tx (
        .clk(clk), .start(tx_start), .data(tx_data), .tx(tx), .busy(tx_busy)
    );

    reg led_r = 1'b0;
    always @(posedge clk) if (core_out_valid) led_r <= ~led_r;
    assign led = led_r;
endmodule
