// Generated by hardware/verilog_gen_pipelined.py -- do not edit by hand.
// Pipelined snapped EML tree 'ln_d4_pipe': 3 gate(s), latency 9 cycles,
// fully streaming (one sample per clock). Format Q10.12 (22 bits).
// ROM reads are registered so yosys synth_ice40 infers EBR (sync read required).

// ------------------------------------------------- exp(a), 2-cycle latency ----
module eml_exp_p #(parameter W = 22, parameter F = 12) (
    input clk,
    input  signed [W-1:0] a,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 8;
    localparam signed [W-1:0] XMIN = -(8 <<< F), XMAX = (8 <<< F);
    localparam signed [W-1:0] EP = 22'sd2097151;  // exp(8) endpoint (entry 256)

    reg signed [W-1:0] lutA [0:255];  // entries 0..255
    reg signed [W-1:0] lutB [0:255];  // entries 1..256 (y1 = lutB[idx])
    initial $readmemh("ln_d4_pipe_exp_lut_a.hex", lutA);
    initial $readmemh("ln_d4_pipe_exp_lut_b.hex", lutB);

    wire signed [W-1:0] r = (a < XMIN) ? XMIN : (a > XMAX) ? XMAX : a;
    wire [W:0] u = r - XMIN;
    wire [LUTB:0] idx = u >> (F - 4);
    wire [IB-1:0] fr = u >> (F - 4 - IB);
    wire top = (idx >= (1 << LUTB));

    // stage 1: synchronous ROM read (EBR)
    reg signed [W-1:0] qA, qB;
    reg [IB-1:0] fr_r;
    reg top_r;
    always @(posedge clk) begin
        qA <= lutA[idx[LUTB-1:0]];
        qB <= lutB[idx[LUTB-1:0]];
        fr_r <= fr;
        top_r <= top;
    end

    // stage 2: interpolate (+ saturate, mirroring fixed_point.exp_fix)
    wire signed [W+IB:0] d = (qB - qA) * $signed({1'b0, fr_r});
    wire signed [W+1:0] s = qA + (d >>> IB);
    localparam signed [W+1:0] PMAX = (1 <<< (W-1)) - 1, PMIN = -(1 <<< (W-1));
    reg signed [W-1:0] y_r;
    always @(posedge clk)
        y_r <= top_r ? EP :
               (s > PMAX) ? PMAX[W-1:0] : (s < PMIN) ? PMIN[W-1:0] : s[W-1:0];
    assign y = y_r;
endmodule

// -------------------------------------------------- ln(b), 2-cycle latency ----
module eml_ln_p #(parameter W = 22, parameter F = 12) (
    input clk,
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 8;
    localparam signed [W-1:0] LN2 = 22'sd2839;

    reg signed [W-1:0] lutA [0:255];  // ln(1 + i/256), entries 0..255
    reg signed [W-1:0] lutB [0:255];  // entries 1..256 (entry 256 = ln(2))
    initial $readmemh("ln_d4_pipe_ln_lut_a.hex", lutA);
    initial $readmemh("ln_d4_pipe_ln_lut_b.hex", lutB);

    wire [W-1:0] r = (b <= 0) ? 22'd1 : b[W-1:0];

    integer i;
    reg [$clog2(W)-1:0] p;
    always @* begin
        p = 0;
        for (i = 0; i < W; i = i + 1)
            if (r[i]) p = i[$clog2(W)-1:0];
    end

    wire [2*W-1:0] rext = r;
    wire [2*W-1:0] shifted = (rext << W) >> p;
    wire [LUTB+IB-1:0] mant = shifted[W-1 -: LUTB+IB];
    wire [LUTB-1:0] idx = mant[LUTB+IB-1:IB];
    wire [IB-1:0] fr = mant[IB-1:0];
    wire signed [$clog2(W):0] k = $signed({1'b0, p}) - F;

    // stage 1: synchronous ROM read (EBR)
    reg signed [W-1:0] qA, qB;
    reg [IB-1:0] fr_r;
    reg signed [$clog2(W):0] k_r;
    always @(posedge clk) begin
        qA <= lutA[idx];
        qB <= lutB[idx];
        fr_r <= fr;
        k_r <= k;
    end

    // stage 2: interpolate + k*ln2 (+ saturate, mirroring fixed_point.ln_fix)
    wire signed [W+IB:0] d = (qB - qA) * $signed({1'b0, fr_r});
    wire signed [W-1:0] ln_m = qA + (d >>> IB);
    wire signed [W+6:0] s = ln_m + k_r * LN2;
    localparam signed [W+6:0] PMAX = (1 <<< (W-1)) - 1, PMIN = -(1 <<< (W-1));
    reg signed [W-1:0] y_r;
    always @(posedge clk)
        y_r <= (s > PMAX) ? PMAX[W-1:0] : (s < PMIN) ? PMIN[W-1:0] : s[W-1:0];
    assign y = y_r;
endmodule

// --------------------------------------------- eml gate, 3-cycle latency ----
module eml_gate_p #(parameter W = 22, parameter F = 12) (
    input clk,
    input  signed [W-1:0] a,
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    wire signed [W-1:0] ea, lb;
    eml_exp_p #(.W(W), .F(F)) u_exp (.clk(clk), .a(a), .y(ea));
    eml_ln_p  #(.W(W), .F(F)) u_ln  (.clk(clk), .b(b), .y(lb));
    wire signed [W:0] s = ea - lb;
    localparam signed [W:0] SMAX = (1 <<< (W-1)) - 1, SMIN = -(1 <<< (W-1));
    reg signed [W-1:0] y_r;
    always @(posedge clk)
        y_r <= (s > SMAX) ? SMAX[W-1:0] : (s < SMIN) ? SMIN[W-1:0] : s[W-1:0];
    assign y = y_r;
endmodule

// ------------------------------------------------------------- top level ----
module ln_d4_pipe (
    input clk,
    input  signed [21:0] x_in,    // Q10.12, one sample per clock
    output signed [21:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 9;
    // (no folded constants referenced)


    wire signed [21:0] g0_out;
    eml_gate_p #(.W(22), .F(12)) u_g0 (
        .clk(clk),
        .a(22'sd4096),
        .b(x_in),
        .y(g0_out)
    );  // t_in=0 t_out=3
    wire signed [21:0] g1_out;
    eml_gate_p #(.W(22), .F(12)) u_g1 (
        .clk(clk),
        .a(g0_out),
        .b(22'sd4096),
        .y(g1_out)
    );  // t_in=3 t_out=6
    wire signed [21:0] g2_out;
    eml_gate_p #(.W(22), .F(12)) u_g2 (
        .clk(clk),
        .a(22'sd4096),
        .b(g1_out),
        .y(g2_out)
    );  // t_in=6 t_out=9

    assign y_out = g2_out;
endmodule
