// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp2_exp_ln_h8_d1': 2 Linear layers, latency 2 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp2_exp_ln_h8_d1 (
    input clk,
    input  signed [15:0] x_in,
    input  signed [15:0] y_in,
    output signed [15:0] y_out    // valid LATENCY cycles after its inputs
);
    localparam LATENCY = 2;

    // ---- layer 0 (ReLU): 2 -> 8 ----
    wire signed [39:0] acc0_0 = $signed(16'sd284) * $signed(x_in) + $signed(-16'sd3) * $signed(y_in);
    wire signed [39:0] pre0_0 = (acc0_0 >>> 8) + $signed(16'sd144);
    reg signed [15:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 16'sd0 : (pre0_0 > 32767) ? 32767 : pre0_0[15:0];
    wire signed [39:0] acc0_1 = $signed(16'sd15) * $signed(x_in) + $signed(-16'sd470) * $signed(y_in);
    wire signed [39:0] pre0_1 = (acc0_1 >>> 8) + $signed(16'sd362);
    reg signed [15:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 16'sd0 : (pre0_1 > 32767) ? 32767 : pre0_1[15:0];
    wire signed [39:0] acc0_2 = $signed(-16'sd15) * $signed(x_in) + $signed(-16'sd88) * $signed(y_in);
    wire signed [39:0] pre0_2 = (acc0_2 >>> 8) + $signed(16'sd321);
    reg signed [15:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 16'sd0 : (pre0_2 > 32767) ? 32767 : pre0_2[15:0];
    wire signed [39:0] acc0_3 = $signed(-16'sd174) * $signed(x_in) + $signed(16'sd188) * $signed(y_in);
    wire signed [39:0] pre0_3 = (acc0_3 >>> 8) + $signed(-16'sd79);
    reg signed [15:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 16'sd0 : (pre0_3 > 32767) ? 32767 : pre0_3[15:0];
    wire signed [39:0] acc0_4 = $signed(16'sd155) * $signed(x_in) + $signed(16'sd111) * $signed(y_in);
    wire signed [39:0] pre0_4 = (acc0_4 >>> 8) + $signed(-16'sd27);
    reg signed [15:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 16'sd0 : (pre0_4 > 32767) ? 32767 : pre0_4[15:0];
    wire signed [39:0] acc0_5 = $signed(-16'sd41) * $signed(x_in) + $signed(-16'sd126) * $signed(y_in);
    wire signed [39:0] pre0_5 = (acc0_5 >>> 8) + $signed(-16'sd89);
    reg signed [15:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 16'sd0 : (pre0_5 > 32767) ? 32767 : pre0_5[15:0];
    wire signed [39:0] acc0_6 = $signed(16'sd472) * $signed(x_in) + $signed(-16'sd11) * $signed(y_in);
    wire signed [39:0] pre0_6 = (acc0_6 >>> 8) + $signed(-16'sd374);
    reg signed [15:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 16'sd0 : (pre0_6 > 32767) ? 32767 : pre0_6[15:0];
    wire signed [39:0] acc0_7 = $signed(16'sd171) * $signed(x_in) + $signed(16'sd20) * $signed(y_in);
    wire signed [39:0] pre0_7 = (acc0_7 >>> 8) + $signed(-16'sd228);
    reg signed [15:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 16'sd0 : (pre0_7 > 32767) ? 32767 : pre0_7[15:0];

    // ---- layer 1 (linear out): 8 -> 1 ----
    wire signed [39:0] acc1_0 = $signed(16'sd239) * $signed(a0_0) + $signed(16'sd368) * $signed(a0_1) + $signed(16'sd261) * $signed(a0_2) + $signed(-16'sd63) * $signed(a0_3) + $signed(16'sd30) * $signed(a0_4) + $signed(-16'sd16) * $signed(a0_5) + $signed(16'sd394) * $signed(a0_6) + $signed(16'sd65) * $signed(a0_7);
    wire signed [39:0] pre1_0 = (acc1_0 >>> 8) + $signed(-16'sd118);
    reg signed [15:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 > 32767) ? 32767 : (pre1_0 < -32768) ? -32768 : pre1_0[15:0];
    assign y_out = a1_0;
endmodule
