// Generated by hardware/verilog_gen_stream.py -- do not edit by hand.
// 2-input byte-serial wrapper around mlp2_exp_ln_h8_d1 (W=16, 2 bytes/sample,
// 2 samples x then y per result, core_latency=2). 19 I/O pins total.

module mlp2_exp_ln_h8_d1_stream (
    input clk,
    input [7:0] in_data,
    input in_valid,
    output [7:0] out_data,
    output out_valid
);
    localparam W = 16, NIN = 2, WB = 16, D = 2;

    // ---- deserializer: 2*NIN bytes little-endian -> (x, y) ----
    reg [WB-1:0] in_shift = 0;
    reg [4:0] in_cnt = 0;            // 0 .. 2*NIN-1
    reg signed [W-1:0] x_s = 0, y_s = 0;
    reg sample_valid = 0;
    wire [WB-1:0] next_shift = {in_data, in_shift[WB-1:8]};
    always @(posedge clk) begin
        sample_valid <= 1'b0;
        if (in_valid) begin
            in_shift <= next_shift;
            if (in_cnt == NIN - 1) begin            // x complete
                x_s <= next_shift[W-1:0];
                in_cnt <= in_cnt + 1;
            end else if (in_cnt == 2*NIN - 1) begin // y complete -> sample ready
                y_s <= next_shift[W-1:0];
                in_cnt <= 0;
                sample_valid <= 1'b1;
            end else
                in_cnt <= in_cnt + 1;
        end
    end

    // ---- core (inputs held; capture D cycles after the sample completes) ----
    wire signed [W-1:0] y_core;
    mlp2_exp_ln_h8_d1 u_core (.clk(clk), .x_in(x_s), .y_in(y_s), .y_out(y_core));
    reg [D-1:0] vpipe = 0;
    always @(posedge clk) vpipe <= {vpipe[D-2:0], sample_valid};
    wire result_valid = vpipe[D-1];

    // ---- serializer: NIN bytes little-endian, sign-extended ----
    reg [WB-1:0] out_shift = 0;
    reg [3:0] out_cnt = 0;
    wire [WB-1:0] y_ext = {{(WB-W){y_core[W-1]}}, y_core};
    always @(posedge clk) begin
        if (result_valid) begin
            out_shift <= y_ext;
            out_cnt <= NIN;
        end else if (out_cnt != 0) begin
            out_shift <= {8'd0, out_shift[WB-1:8]};
            out_cnt <= out_cnt - 1;
        end
    end
    assign out_data = out_shift[7:0];
    assign out_valid = (out_cnt != 0);
endmodule
