// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_exp_h4_d1': 2 Linear layers, latency 2 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_exp_h4_d1 (
    input clk,
    input  signed [15:0] x_in,    // Q8.8, one sample per clock
    output signed [15:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 2;

    // ---- layer 0 (ReLU): 1 -> 4 ----
    wire signed [39:0] acc0_0 = $signed(16'sd433) * $signed(x_in);
    wire signed [39:0] pre0_0 = (acc0_0 >>> 8) + $signed(-16'sd460);
    reg signed [15:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 16'sd0 : (pre0_0 > 32767) ? 32767 : pre0_0[15:0];
    wire signed [39:0] acc0_1 = $signed(16'sd145) * $signed(x_in);
    wire signed [39:0] pre0_1 = (acc0_1 >>> 8) + $signed(16'sd227);
    reg signed [15:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 16'sd0 : (pre0_1 > 32767) ? 32767 : pre0_1[15:0];
    wire signed [39:0] acc0_2 = $signed(-16'sd22) * $signed(x_in);
    wire signed [39:0] pre0_2 = (acc0_2 >>> 8) + $signed(-16'sd61);
    reg signed [15:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 16'sd0 : (pre0_2 > 32767) ? 32767 : pre0_2[15:0];
    wire signed [39:0] acc0_3 = $signed(16'sd425) * $signed(x_in);
    wire signed [39:0] pre0_3 = (acc0_3 >>> 8) + $signed(16'sd87);
    reg signed [15:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 16'sd0 : (pre0_3 > 32767) ? 32767 : pre0_3[15:0];

    // ---- layer 1 (linear out): 4 -> 1 ----
    wire signed [39:0] acc1_0 = $signed(16'sd479) * $signed(a0_0) + $signed(16'sd172) * $signed(a0_1) + $signed(-16'sd8) * $signed(a0_2) + $signed(16'sd175) * $signed(a0_3);
    wire signed [39:0] pre1_0 = (acc1_0 >>> 8) + $signed(16'sd44);
    reg signed [15:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 > 32767) ? 32767 : (pre1_0 < -32768) ? -32768 : pre1_0[15:0];
    assign y_out = a1_0;
endmodule
