// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_exp_h8_d2': 3 Linear layers, latency 3 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_exp_h8_d2 (
    input clk,
    input  signed [15:0] x_in,    // Q8.8, one sample per clock
    output signed [15:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 3;

    // ---- layer 0 (ReLU): 1 -> 8 ----
    wire signed [39:0] acc0_0 = $signed(16'sd159) * $signed(x_in);
    wire signed [39:0] pre0_0 = (acc0_0 >>> 8) + $signed(16'sd22);
    reg signed [15:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 16'sd0 : (pre0_0 > 32767) ? 32767 : pre0_0[15:0];
    wire signed [39:0] acc0_1 = $signed(16'sd28) * $signed(x_in);
    wire signed [39:0] pre0_1 = (acc0_1 >>> 8) + $signed(-16'sd170);
    reg signed [15:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 16'sd0 : (pre0_1 > 32767) ? 32767 : pre0_1[15:0];
    wire signed [39:0] acc0_2 = $signed(16'sd336) * $signed(x_in);
    wire signed [39:0] pre0_2 = (acc0_2 >>> 8) + $signed(-16'sd226);
    reg signed [15:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 16'sd0 : (pre0_2 > 32767) ? 32767 : pre0_2[15:0];
    wire signed [39:0] acc0_3 = $signed(16'sd196) * $signed(x_in);
    wire signed [39:0] pre0_3 = (acc0_3 >>> 8) + $signed(-16'sd71);
    reg signed [15:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 16'sd0 : (pre0_3 > 32767) ? 32767 : pre0_3[15:0];
    wire signed [39:0] acc0_4 = $signed(-16'sd152) * $signed(x_in);
    wire signed [39:0] pre0_4 = (acc0_4 >>> 8) + $signed(16'sd319);
    reg signed [15:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 16'sd0 : (pre0_4 > 32767) ? 32767 : pre0_4[15:0];
    wire signed [39:0] acc0_5 = $signed(16'sd40) * $signed(x_in);
    wire signed [39:0] pre0_5 = (acc0_5 >>> 8) + $signed(16'sd289);
    reg signed [15:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 16'sd0 : (pre0_5 > 32767) ? 32767 : pre0_5[15:0];
    wire signed [39:0] acc0_6 = $signed(16'sd69) * $signed(x_in);
    wire signed [39:0] pre0_6 = (acc0_6 >>> 8) + $signed(-16'sd166);
    reg signed [15:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 16'sd0 : (pre0_6 > 32767) ? 32767 : pre0_6[15:0];
    wire signed [39:0] acc0_7 = $signed(16'sd208) * $signed(x_in);
    wire signed [39:0] pre0_7 = (acc0_7 >>> 8) + $signed(16'sd195);
    reg signed [15:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 16'sd0 : (pre0_7 > 32767) ? 32767 : pre0_7[15:0];

    // ---- layer 1 (ReLU): 8 -> 8 ----
    wire signed [39:0] acc1_0 = $signed(16'sd54) * $signed(a0_0) + $signed(16'sd19) * $signed(a0_1) + $signed(-16'sd36) * $signed(a0_2) + $signed(-16'sd56) * $signed(a0_3) + $signed(-16'sd61) * $signed(a0_4) + $signed(-16'sd51) * $signed(a0_5) + $signed(-16'sd32) * $signed(a0_6) + $signed(16'sd49) * $signed(a0_7);
    wire signed [39:0] pre1_0 = (acc1_0 >>> 8) + $signed(-16'sd83);
    reg signed [15:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 <= 0) ? 16'sd0 : (pre1_0 > 32767) ? 32767 : pre1_0[15:0];
    wire signed [39:0] acc1_1 = $signed(16'sd21) * $signed(a0_0) + $signed(-16'sd19) * $signed(a0_1) + $signed(-16'sd57) * $signed(a0_2) + $signed(16'sd61) * $signed(a0_3) + $signed(-16'sd52) * $signed(a0_4) + $signed(-16'sd13) * $signed(a0_5) + $signed(16'sd0) * $signed(a0_6) + $signed(-16'sd84) * $signed(a0_7);
    wire signed [39:0] pre1_1 = (acc1_1 >>> 8) + $signed(-16'sd21);
    reg signed [15:0] a1_1;
    always @(posedge clk) a1_1 <= (pre1_1 <= 0) ? 16'sd0 : (pre1_1 > 32767) ? 32767 : pre1_1[15:0];
    wire signed [39:0] acc1_2 = $signed(16'sd144) * $signed(a0_0) + $signed(-16'sd73) * $signed(a0_1) + $signed(16'sd179) * $signed(a0_2) + $signed(16'sd160) * $signed(a0_3) + $signed(-16'sd226) * $signed(a0_4) + $signed(-16'sd141) * $signed(a0_5) + $signed(16'sd99) * $signed(a0_6) + $signed(16'sd27) * $signed(a0_7);
    wire signed [39:0] pre1_2 = (acc1_2 >>> 8) + $signed(-16'sd29);
    reg signed [15:0] a1_2;
    always @(posedge clk) a1_2 <= (pre1_2 <= 0) ? 16'sd0 : (pre1_2 > 32767) ? 32767 : pre1_2[15:0];
    wire signed [39:0] acc1_3 = $signed(16'sd94) * $signed(a0_0) + $signed(16'sd0) * $signed(a0_1) + $signed(16'sd249) * $signed(a0_2) + $signed(16'sd185) * $signed(a0_3) + $signed(-16'sd467) * $signed(a0_4) + $signed(-16'sd246) * $signed(a0_5) + $signed(-16'sd14) * $signed(a0_6) + $signed(16'sd51) * $signed(a0_7);
    wire signed [39:0] pre1_3 = (acc1_3 >>> 8) + $signed(-16'sd165);
    reg signed [15:0] a1_3;
    always @(posedge clk) a1_3 <= (pre1_3 <= 0) ? 16'sd0 : (pre1_3 > 32767) ? 32767 : pre1_3[15:0];
    wire signed [39:0] acc1_4 = $signed(16'sd117) * $signed(a0_0) + $signed(-16'sd39) * $signed(a0_1) + $signed(16'sd132) * $signed(a0_2) + $signed(16'sd166) * $signed(a0_3) + $signed(-16'sd84) * $signed(a0_4) + $signed(16'sd83) * $signed(a0_5) + $signed(-16'sd33) * $signed(a0_6) + $signed(16'sd26) * $signed(a0_7);
    wire signed [39:0] pre1_4 = (acc1_4 >>> 8) + $signed(16'sd127);
    reg signed [15:0] a1_4;
    always @(posedge clk) a1_4 <= (pre1_4 <= 0) ? 16'sd0 : (pre1_4 > 32767) ? 32767 : pre1_4[15:0];
    wire signed [39:0] acc1_5 = $signed(-16'sd24) * $signed(a0_0) + $signed(16'sd51) * $signed(a0_1) + $signed(16'sd125) * $signed(a0_2) + $signed(16'sd100) * $signed(a0_3) + $signed(-16'sd301) * $signed(a0_4) + $signed(-16'sd156) * $signed(a0_5) + $signed(-16'sd19) * $signed(a0_6) + $signed(16'sd33) * $signed(a0_7);
    wire signed [39:0] pre1_5 = (acc1_5 >>> 8) + $signed(-16'sd56);
    reg signed [15:0] a1_5;
    always @(posedge clk) a1_5 <= (pre1_5 <= 0) ? 16'sd0 : (pre1_5 > 32767) ? 32767 : pre1_5[15:0];
    wire signed [39:0] acc1_6 = $signed(-16'sd11) * $signed(a0_0) + $signed(16'sd23) * $signed(a0_1) + $signed(16'sd64) * $signed(a0_2) + $signed(-16'sd17) * $signed(a0_3) + $signed(-16'sd28) * $signed(a0_4) + $signed(-16'sd28) * $signed(a0_5) + $signed(16'sd25) * $signed(a0_6) + $signed(-16'sd46) * $signed(a0_7);
    wire signed [39:0] pre1_6 = (acc1_6 >>> 8) + $signed(-16'sd40);
    reg signed [15:0] a1_6;
    always @(posedge clk) a1_6 <= (pre1_6 <= 0) ? 16'sd0 : (pre1_6 > 32767) ? 32767 : pre1_6[15:0];
    wire signed [39:0] acc1_7 = $signed(16'sd187) * $signed(a0_0) + $signed(16'sd48) * $signed(a0_1) + $signed(16'sd44) * $signed(a0_2) + $signed(16'sd134) * $signed(a0_3) + $signed(-16'sd33) * $signed(a0_4) + $signed(16'sd29) * $signed(a0_5) + $signed(-16'sd61) * $signed(a0_6) + $signed(16'sd141) * $signed(a0_7);
    wire signed [39:0] pre1_7 = (acc1_7 >>> 8) + $signed(16'sd54);
    reg signed [15:0] a1_7;
    always @(posedge clk) a1_7 <= (pre1_7 <= 0) ? 16'sd0 : (pre1_7 > 32767) ? 32767 : pre1_7[15:0];

    // ---- layer 2 (linear out): 8 -> 1 ----
    wire signed [39:0] acc2_0 = $signed(-16'sd20) * $signed(a1_0) + $signed(-16'sd22) * $signed(a1_1) + $signed(16'sd168) * $signed(a1_2) + $signed(16'sd147) * $signed(a1_3) + $signed(16'sd151) * $signed(a1_4) + $signed(16'sd100) * $signed(a1_5) + $signed(-16'sd71) * $signed(a1_6) + $signed(16'sd199) * $signed(a1_7);
    wire signed [39:0] pre2_0 = (acc2_0 >>> 8) + $signed(16'sd39);
    reg signed [15:0] a2_0;
    always @(posedge clk) a2_0 <= (pre2_0 > 32767) ? 32767 : (pre2_0 < -32768) ? -32768 : pre2_0[15:0];
    assign y_out = a2_0;
endmodule
