// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_ln_h16_d2': 3 Linear layers, latency 3 cycles,
// fully streaming (one sample per clock). Format Q10.12 (22 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_ln_h16_d2 (
    input clk,
    input  signed [21:0] x_in,    // Q10.12, one sample per clock
    output signed [21:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 3;

    // ---- layer 0 (ReLU): 1 -> 16 ----
    wire signed [51:0] acc0_0 = $signed(22'sd2129) * $signed(x_in);
    wire signed [51:0] pre0_0 = (acc0_0 >>> 12) + $signed(22'sd1331);
    reg signed [21:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 22'sd0 : (pre0_0 > 2097151) ? 2097151 : pre0_0[21:0];
    wire signed [51:0] acc0_1 = $signed(-22'sd1808) * $signed(x_in);
    wire signed [51:0] pre0_1 = (acc0_1 >>> 12) + $signed(-22'sd16);
    reg signed [21:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 22'sd0 : (pre0_1 > 2097151) ? 2097151 : pre0_1[21:0];
    wire signed [51:0] acc0_2 = $signed(-22'sd994) * $signed(x_in);
    wire signed [51:0] pre0_2 = (acc0_2 >>> 12) + $signed(22'sd4504);
    reg signed [21:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 22'sd0 : (pre0_2 > 2097151) ? 2097151 : pre0_2[21:0];
    wire signed [51:0] acc0_3 = $signed(22'sd1407) * $signed(x_in);
    wire signed [51:0] pre0_3 = (acc0_3 >>> 12) + $signed(22'sd1665);
    reg signed [21:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 22'sd0 : (pre0_3 > 2097151) ? 2097151 : pre0_3[21:0];
    wire signed [51:0] acc0_4 = $signed(-22'sd3856) * $signed(x_in);
    wire signed [51:0] pre0_4 = (acc0_4 >>> 12) + $signed(-22'sd1525);
    reg signed [21:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 22'sd0 : (pre0_4 > 2097151) ? 2097151 : pre0_4[21:0];
    wire signed [51:0] acc0_5 = $signed(22'sd2081) * $signed(x_in);
    wire signed [51:0] pre0_5 = (acc0_5 >>> 12) + $signed(-22'sd1739);
    reg signed [21:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 22'sd0 : (pre0_5 > 2097151) ? 2097151 : pre0_5[21:0];
    wire signed [51:0] acc0_6 = $signed(-22'sd843) * $signed(x_in);
    wire signed [51:0] pre0_6 = (acc0_6 >>> 12) + $signed(-22'sd687);
    reg signed [21:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 22'sd0 : (pre0_6 > 2097151) ? 2097151 : pre0_6[21:0];
    wire signed [51:0] acc0_7 = $signed(22'sd1777) * $signed(x_in);
    wire signed [51:0] pre0_7 = (acc0_7 >>> 12) + $signed(-22'sd1485);
    reg signed [21:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 22'sd0 : (pre0_7 > 2097151) ? 2097151 : pre0_7[21:0];
    wire signed [51:0] acc0_8 = $signed(22'sd359) * $signed(x_in);
    wire signed [51:0] pre0_8 = (acc0_8 >>> 12) + $signed(-22'sd2072);
    reg signed [21:0] a0_8;
    always @(posedge clk) a0_8 <= (pre0_8 <= 0) ? 22'sd0 : (pre0_8 > 2097151) ? 2097151 : pre0_8[21:0];
    wire signed [51:0] acc0_9 = $signed(-22'sd4665) * $signed(x_in);
    wire signed [51:0] pre0_9 = (acc0_9 >>> 12) + $signed(22'sd1114);
    reg signed [21:0] a0_9;
    always @(posedge clk) a0_9 <= (pre0_9 <= 0) ? 22'sd0 : (pre0_9 > 2097151) ? 2097151 : pre0_9[21:0];
    wire signed [51:0] acc0_10 = $signed(22'sd1232) * $signed(x_in);
    wire signed [51:0] pre0_10 = (acc0_10 >>> 12) + $signed(22'sd3142);
    reg signed [21:0] a0_10;
    always @(posedge clk) a0_10 <= (pre0_10 <= 0) ? 22'sd0 : (pre0_10 > 2097151) ? 2097151 : pre0_10[21:0];
    wire signed [51:0] acc0_11 = $signed(-22'sd105) * $signed(x_in);
    wire signed [51:0] pre0_11 = (acc0_11 >>> 12) + $signed(22'sd2087);
    reg signed [21:0] a0_11;
    always @(posedge clk) a0_11 <= (pre0_11 <= 0) ? 22'sd0 : (pre0_11 > 2097151) ? 2097151 : pre0_11[21:0];
    wire signed [51:0] acc0_12 = $signed(22'sd1663) * $signed(x_in);
    wire signed [51:0] pre0_12 = (acc0_12 >>> 12) + $signed(-22'sd3601);
    reg signed [21:0] a0_12;
    always @(posedge clk) a0_12 <= (pre0_12 <= 0) ? 22'sd0 : (pre0_12 > 2097151) ? 2097151 : pre0_12[21:0];
    wire signed [51:0] acc0_13 = $signed(-22'sd3120) * $signed(x_in);
    wire signed [51:0] pre0_13 = (acc0_13 >>> 12) + $signed(22'sd2585);
    reg signed [21:0] a0_13;
    always @(posedge clk) a0_13 <= (pre0_13 <= 0) ? 22'sd0 : (pre0_13 > 2097151) ? 2097151 : pre0_13[21:0];
    wire signed [51:0] acc0_14 = $signed(-22'sd2710) * $signed(x_in);
    wire signed [51:0] pre0_14 = (acc0_14 >>> 12) + $signed(22'sd1284);
    reg signed [21:0] a0_14;
    always @(posedge clk) a0_14 <= (pre0_14 <= 0) ? 22'sd0 : (pre0_14 > 2097151) ? 2097151 : pre0_14[21:0];
    wire signed [51:0] acc0_15 = $signed(-22'sd396) * $signed(x_in);
    wire signed [51:0] pre0_15 = (acc0_15 >>> 12) + $signed(22'sd5038);
    reg signed [21:0] a0_15;
    always @(posedge clk) a0_15 <= (pre0_15 <= 0) ? 22'sd0 : (pre0_15 > 2097151) ? 2097151 : pre0_15[21:0];

    // ---- layer 1 (ReLU): 16 -> 16 ----
    wire signed [51:0] acc1_0 = $signed(22'sd518) * $signed(a0_0) + $signed(-22'sd933) * $signed(a0_1) + $signed(-22'sd1177) * $signed(a0_2) + $signed(-22'sd652) * $signed(a0_3) + $signed(22'sd899) * $signed(a0_4) + $signed(-22'sd325) * $signed(a0_5) + $signed(22'sd438) * $signed(a0_6) + $signed(-22'sd630) * $signed(a0_7) + $signed(22'sd858) * $signed(a0_8) + $signed(-22'sd433) * $signed(a0_9) + $signed(22'sd607) * $signed(a0_10) + $signed(-22'sd152) * $signed(a0_11) + $signed(-22'sd687) * $signed(a0_12) + $signed(22'sd652) * $signed(a0_13) + $signed(-22'sd724) * $signed(a0_14) + $signed(22'sd114) * $signed(a0_15);
    wire signed [51:0] pre1_0 = (acc1_0 >>> 12) + $signed(-22'sd364);
    reg signed [21:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 <= 0) ? 22'sd0 : (pre1_0 > 2097151) ? 2097151 : pre1_0[21:0];
    wire signed [51:0] acc1_1 = $signed(-22'sd417) * $signed(a0_0) + $signed(-22'sd112) * $signed(a0_1) + $signed(22'sd1236) * $signed(a0_2) + $signed(-22'sd602) * $signed(a0_3) + $signed(22'sd556) * $signed(a0_4) + $signed(-22'sd334) * $signed(a0_5) + $signed(22'sd1020) * $signed(a0_6) + $signed(22'sd707) * $signed(a0_7) + $signed(22'sd670) * $signed(a0_8) + $signed(22'sd5225) * $signed(a0_9) + $signed(22'sd622) * $signed(a0_10) + $signed(22'sd425) * $signed(a0_11) + $signed(-22'sd406) * $signed(a0_12) + $signed(22'sd2487) * $signed(a0_13) + $signed(22'sd4355) * $signed(a0_14) + $signed(22'sd1586) * $signed(a0_15);
    wire signed [51:0] pre1_1 = (acc1_1 >>> 12) + $signed(22'sd497);
    reg signed [21:0] a1_1;
    always @(posedge clk) a1_1 <= (pre1_1 <= 0) ? 22'sd0 : (pre1_1 > 2097151) ? 2097151 : pre1_1[21:0];
    wire signed [51:0] acc1_2 = $signed(-22'sd1152) * $signed(a0_0) + $signed(-22'sd169) * $signed(a0_1) + $signed(22'sd1045) * $signed(a0_2) + $signed(-22'sd84) * $signed(a0_3) + $signed(-22'sd777) * $signed(a0_4) + $signed(-22'sd1379) * $signed(a0_5) + $signed(22'sd557) * $signed(a0_6) + $signed(-22'sd911) * $signed(a0_7) + $signed(22'sd500) * $signed(a0_8) + $signed(22'sd4530) * $signed(a0_9) + $signed(22'sd495) * $signed(a0_10) + $signed(22'sd1002) * $signed(a0_11) + $signed(22'sd3051) * $signed(a0_12) + $signed(22'sd2003) * $signed(a0_13) + $signed(22'sd1440) * $signed(a0_14) + $signed(22'sd1367) * $signed(a0_15);
    wire signed [51:0] pre1_2 = (acc1_2 >>> 12) + $signed(22'sd798);
    reg signed [21:0] a1_2;
    always @(posedge clk) a1_2 <= (pre1_2 <= 0) ? 22'sd0 : (pre1_2 > 2097151) ? 2097151 : pre1_2[21:0];
    wire signed [51:0] acc1_3 = $signed(-22'sd720) * $signed(a0_0) + $signed(-22'sd773) * $signed(a0_1) + $signed(22'sd62) * $signed(a0_2) + $signed(-22'sd174) * $signed(a0_3) + $signed(22'sd601) * $signed(a0_4) + $signed(-22'sd593) * $signed(a0_5) + $signed(-22'sd910) * $signed(a0_6) + $signed(22'sd745) * $signed(a0_7) + $signed(-22'sd152) * $signed(a0_8) + $signed(22'sd576) * $signed(a0_9) + $signed(22'sd329) * $signed(a0_10) + $signed(-22'sd768) * $signed(a0_11) + $signed(22'sd206) * $signed(a0_12) + $signed(22'sd246) * $signed(a0_13) + $signed(-22'sd686) * $signed(a0_14) + $signed(-22'sd486) * $signed(a0_15);
    wire signed [51:0] pre1_3 = (acc1_3 >>> 12) + $signed(-22'sd653);
    reg signed [21:0] a1_3;
    always @(posedge clk) a1_3 <= (pre1_3 <= 0) ? 22'sd0 : (pre1_3 > 2097151) ? 2097151 : pre1_3[21:0];
    wire signed [51:0] acc1_4 = $signed(22'sd393) * $signed(a0_0) + $signed(22'sd183) * $signed(a0_1) + $signed(-22'sd1322) * $signed(a0_2) + $signed(-22'sd199) * $signed(a0_3) + $signed(22'sd938) * $signed(a0_4) + $signed(-22'sd321) * $signed(a0_5) + $signed(22'sd577) * $signed(a0_6) + $signed(22'sd321) * $signed(a0_7) + $signed(-22'sd1352) * $signed(a0_8) + $signed(-22'sd5220) * $signed(a0_9) + $signed(22'sd1184) * $signed(a0_10) + $signed(22'sd758) * $signed(a0_11) + $signed(22'sd155) * $signed(a0_12) + $signed(-22'sd1035) * $signed(a0_13) + $signed(-22'sd1602) * $signed(a0_14) + $signed(22'sd2246) * $signed(a0_15);
    wire signed [51:0] pre1_4 = (acc1_4 >>> 12) + $signed(22'sd1407);
    reg signed [21:0] a1_4;
    always @(posedge clk) a1_4 <= (pre1_4 <= 0) ? 22'sd0 : (pre1_4 > 2097151) ? 2097151 : pre1_4[21:0];
    wire signed [51:0] acc1_5 = $signed(22'sd1085) * $signed(a0_0) + $signed(-22'sd680) * $signed(a0_1) + $signed(-22'sd588) * $signed(a0_2) + $signed(22'sd928) * $signed(a0_3) + $signed(22'sd742) * $signed(a0_4) + $signed(22'sd616) * $signed(a0_5) + $signed(-22'sd741) * $signed(a0_6) + $signed(-22'sd746) * $signed(a0_7) + $signed(-22'sd983) * $signed(a0_8) + $signed(-22'sd3707) * $signed(a0_9) + $signed(22'sd1254) * $signed(a0_10) + $signed(-22'sd70) * $signed(a0_11) + $signed(22'sd191) * $signed(a0_12) + $signed(-22'sd1733) * $signed(a0_13) + $signed(-22'sd2686) * $signed(a0_14) + $signed(22'sd1084) * $signed(a0_15);
    wire signed [51:0] pre1_5 = (acc1_5 >>> 12) + $signed(22'sd1280);
    reg signed [21:0] a1_5;
    always @(posedge clk) a1_5 <= (pre1_5 <= 0) ? 22'sd0 : (pre1_5 > 2097151) ? 2097151 : pre1_5[21:0];
    wire signed [51:0] acc1_6 = $signed(22'sd293) * $signed(a0_0) + $signed(22'sd951) * $signed(a0_1) + $signed(-22'sd919) * $signed(a0_2) + $signed(-22'sd65) * $signed(a0_3) + $signed(22'sd884) * $signed(a0_4) + $signed(22'sd387) * $signed(a0_5) + $signed(22'sd638) * $signed(a0_6) + $signed(22'sd441) * $signed(a0_7) + $signed(22'sd385) * $signed(a0_8) + $signed(22'sd264) * $signed(a0_9) + $signed(-22'sd998) * $signed(a0_10) + $signed(-22'sd1127) * $signed(a0_11) + $signed(-22'sd777) * $signed(a0_12) + $signed(-22'sd119) * $signed(a0_13) + $signed(-22'sd825) * $signed(a0_14) + $signed(22'sd54) * $signed(a0_15);
    wire signed [51:0] pre1_6 = (acc1_6 >>> 12) + $signed(-22'sd235);
    reg signed [21:0] a1_6;
    always @(posedge clk) a1_6 <= (pre1_6 <= 0) ? 22'sd0 : (pre1_6 > 2097151) ? 2097151 : pre1_6[21:0];
    wire signed [51:0] acc1_7 = $signed(22'sd47) * $signed(a0_0) + $signed(-22'sd232) * $signed(a0_1) + $signed(22'sd174) * $signed(a0_2) + $signed(22'sd65) * $signed(a0_3) + $signed(22'sd625) * $signed(a0_4) + $signed(22'sd422) * $signed(a0_5) + $signed(-22'sd347) * $signed(a0_6) + $signed(22'sd734) * $signed(a0_7) + $signed(-22'sd376) * $signed(a0_8) + $signed(-22'sd35) * $signed(a0_9) + $signed(-22'sd1237) * $signed(a0_10) + $signed(-22'sd915) * $signed(a0_11) + $signed(-22'sd873) * $signed(a0_12) + $signed(-22'sd438) * $signed(a0_13) + $signed(22'sd575) * $signed(a0_14) + $signed(-22'sd612) * $signed(a0_15);
    wire signed [51:0] pre1_7 = (acc1_7 >>> 12) + $signed(-22'sd846);
    reg signed [21:0] a1_7;
    always @(posedge clk) a1_7 <= (pre1_7 <= 0) ? 22'sd0 : (pre1_7 > 2097151) ? 2097151 : pre1_7[21:0];
    wire signed [51:0] acc1_8 = $signed(-22'sd1639) * $signed(a0_0) + $signed(22'sd394) * $signed(a0_1) + $signed(22'sd1281) * $signed(a0_2) + $signed(-22'sd38) * $signed(a0_3) + $signed(-22'sd530) * $signed(a0_4) + $signed(-22'sd377) * $signed(a0_5) + $signed(-22'sd373) * $signed(a0_6) + $signed(-22'sd794) * $signed(a0_7) + $signed(-22'sd947) * $signed(a0_8) + $signed(22'sd4147) * $signed(a0_9) + $signed(-22'sd682) * $signed(a0_10) + $signed(22'sd782) * $signed(a0_11) + $signed(-22'sd383) * $signed(a0_12) + $signed(22'sd1773) * $signed(a0_13) + $signed(22'sd3525) * $signed(a0_14) + $signed(22'sd1465) * $signed(a0_15);
    wire signed [51:0] pre1_8 = (acc1_8 >>> 12) + $signed(-22'sd90);
    reg signed [21:0] a1_8;
    always @(posedge clk) a1_8 <= (pre1_8 <= 0) ? 22'sd0 : (pre1_8 > 2097151) ? 2097151 : pre1_8[21:0];
    wire signed [51:0] acc1_9 = $signed(22'sd494) * $signed(a0_0) + $signed(22'sd33) * $signed(a0_1) + $signed(-22'sd854) * $signed(a0_2) + $signed(22'sd597) * $signed(a0_3) + $signed(-22'sd256) * $signed(a0_4) + $signed(-22'sd287) * $signed(a0_5) + $signed(-22'sd882) * $signed(a0_6) + $signed(-22'sd406) * $signed(a0_7) + $signed(-22'sd863) * $signed(a0_8) + $signed(22'sd941) * $signed(a0_9) + $signed(-22'sd1089) * $signed(a0_10) + $signed(-22'sd999) * $signed(a0_11) + $signed(-22'sd241) * $signed(a0_12) + $signed(-22'sd554) * $signed(a0_13) + $signed(22'sd243) * $signed(a0_14) + $signed(-22'sd597) * $signed(a0_15);
    wire signed [51:0] pre1_9 = (acc1_9 >>> 12) + $signed(-22'sd188);
    reg signed [21:0] a1_9;
    always @(posedge clk) a1_9 <= (pre1_9 <= 0) ? 22'sd0 : (pre1_9 > 2097151) ? 2097151 : pre1_9[21:0];
    wire signed [51:0] acc1_10 = $signed(-22'sd588) * $signed(a0_0) + $signed(22'sd58) * $signed(a0_1) + $signed(22'sd634) * $signed(a0_2) + $signed(-22'sd827) * $signed(a0_3) + $signed(22'sd481) * $signed(a0_4) + $signed(22'sd658) * $signed(a0_5) + $signed(22'sd1002) * $signed(a0_6) + $signed(-22'sd717) * $signed(a0_7) + $signed(22'sd248) * $signed(a0_8) + $signed(-22'sd864) * $signed(a0_9) + $signed(22'sd767) * $signed(a0_10) + $signed(-22'sd504) * $signed(a0_11) + $signed(22'sd617) * $signed(a0_12) + $signed(-22'sd77) * $signed(a0_13) + $signed(-22'sd187) * $signed(a0_14) + $signed(-22'sd140) * $signed(a0_15);
    wire signed [51:0] pre1_10 = (acc1_10 >>> 12) + $signed(-22'sd692);
    reg signed [21:0] a1_10;
    always @(posedge clk) a1_10 <= (pre1_10 <= 0) ? 22'sd0 : (pre1_10 > 2097151) ? 2097151 : pre1_10[21:0];
    wire signed [51:0] acc1_11 = $signed(-22'sd101) * $signed(a0_0) + $signed(22'sd483) * $signed(a0_1) + $signed(-22'sd150) * $signed(a0_2) + $signed(22'sd39) * $signed(a0_3) + $signed(-22'sd921) * $signed(a0_4) + $signed(22'sd475) * $signed(a0_5) + $signed(22'sd893) * $signed(a0_6) + $signed(22'sd575) * $signed(a0_7) + $signed(22'sd495) * $signed(a0_8) + $signed(-22'sd739) * $signed(a0_9) + $signed(-22'sd657) * $signed(a0_10) + $signed(22'sd626) * $signed(a0_11) + $signed(-22'sd1049) * $signed(a0_12) + $signed(22'sd806) * $signed(a0_13) + $signed(-22'sd1015) * $signed(a0_14) + $signed(-22'sd1020) * $signed(a0_15);
    wire signed [51:0] pre1_11 = (acc1_11 >>> 12) + $signed(-22'sd855);
    reg signed [21:0] a1_11;
    always @(posedge clk) a1_11 <= (pre1_11 <= 0) ? 22'sd0 : (pre1_11 > 2097151) ? 2097151 : pre1_11[21:0];
    wire signed [51:0] acc1_12 = $signed(22'sd215) * $signed(a0_0) + $signed(-22'sd736) * $signed(a0_1) + $signed(-22'sd510) * $signed(a0_2) + $signed(22'sd464) * $signed(a0_3) + $signed(22'sd811) * $signed(a0_4) + $signed(22'sd687) * $signed(a0_5) + $signed(-22'sd208) * $signed(a0_6) + $signed(-22'sd1076) * $signed(a0_7) + $signed(22'sd741) * $signed(a0_8) + $signed(-22'sd218) * $signed(a0_9) + $signed(-22'sd707) * $signed(a0_10) + $signed(-22'sd23) * $signed(a0_11) + $signed(-22'sd1004) * $signed(a0_12) + $signed(22'sd543) * $signed(a0_13) + $signed(22'sd442) * $signed(a0_14) + $signed(-22'sd1112) * $signed(a0_15);
    wire signed [51:0] pre1_12 = (acc1_12 >>> 12) + $signed(-22'sd435);
    reg signed [21:0] a1_12;
    always @(posedge clk) a1_12 <= (pre1_12 <= 0) ? 22'sd0 : (pre1_12 > 2097151) ? 2097151 : pre1_12[21:0];
    wire signed [51:0] acc1_13 = $signed(-22'sd970) * $signed(a0_0) + $signed(-22'sd90) * $signed(a0_1) + $signed(22'sd300) * $signed(a0_2) + $signed(-22'sd159) * $signed(a0_3) + $signed(-22'sd519) * $signed(a0_4) + $signed(22'sd23) * $signed(a0_5) + $signed(-22'sd962) * $signed(a0_6) + $signed(-22'sd724) * $signed(a0_7) + $signed(-22'sd682) * $signed(a0_8) + $signed(22'sd712) * $signed(a0_9) + $signed(22'sd773) * $signed(a0_10) + $signed(-22'sd477) * $signed(a0_11) + $signed(22'sd46) * $signed(a0_12) + $signed(22'sd327) * $signed(a0_13) + $signed(-22'sd7) * $signed(a0_14) + $signed(-22'sd643) * $signed(a0_15);
    wire signed [51:0] pre1_13 = (acc1_13 >>> 12) + $signed(-22'sd425);
    reg signed [21:0] a1_13;
    always @(posedge clk) a1_13 <= (pre1_13 <= 0) ? 22'sd0 : (pre1_13 > 2097151) ? 2097151 : pre1_13[21:0];
    wire signed [51:0] acc1_14 = $signed(22'sd701) * $signed(a0_0) + $signed(22'sd629) * $signed(a0_1) + $signed(-22'sd457) * $signed(a0_2) + $signed(22'sd35) * $signed(a0_3) + $signed(22'sd931) * $signed(a0_4) + $signed(22'sd872) * $signed(a0_5) + $signed(-22'sd581) * $signed(a0_6) + $signed(22'sd991) * $signed(a0_7) + $signed(-22'sd103) * $signed(a0_8) + $signed(-22'sd4951) * $signed(a0_9) + $signed(22'sd793) * $signed(a0_10) + $signed(-22'sd178) * $signed(a0_11) + $signed(22'sd599) * $signed(a0_12) + $signed(-22'sd1624) * $signed(a0_13) + $signed(-22'sd1204) * $signed(a0_14) + $signed(22'sd1576) * $signed(a0_15);
    wire signed [51:0] pre1_14 = (acc1_14 >>> 12) + $signed(22'sd964);
    reg signed [21:0] a1_14;
    always @(posedge clk) a1_14 <= (pre1_14 <= 0) ? 22'sd0 : (pre1_14 > 2097151) ? 2097151 : pre1_14[21:0];
    wire signed [51:0] acc1_15 = $signed(22'sd304) * $signed(a0_0) + $signed(22'sd849) * $signed(a0_1) + $signed(-22'sd1171) * $signed(a0_2) + $signed(-22'sd300) * $signed(a0_3) + $signed(-22'sd887) * $signed(a0_4) + $signed(-22'sd165) * $signed(a0_5) + $signed(-22'sd485) * $signed(a0_6) + $signed(-22'sd73) * $signed(a0_7) + $signed(-22'sd907) * $signed(a0_8) + $signed(-22'sd5072) * $signed(a0_9) + $signed(22'sd1120) * $signed(a0_10) + $signed(22'sd1042) * $signed(a0_11) + $signed(-22'sd907) * $signed(a0_12) + $signed(-22'sd1575) * $signed(a0_13) + $signed(-22'sd2881) * $signed(a0_14) + $signed(22'sd2568) * $signed(a0_15);
    wire signed [51:0] pre1_15 = (acc1_15 >>> 12) + $signed(22'sd642);
    reg signed [21:0] a1_15;
    always @(posedge clk) a1_15 <= (pre1_15 <= 0) ? 22'sd0 : (pre1_15 > 2097151) ? 2097151 : pre1_15[21:0];

    // ---- layer 2 (linear out): 16 -> 1 ----
    wire signed [51:0] acc2_0 = $signed(22'sd16) * $signed(a1_0) + $signed(-22'sd2057) * $signed(a1_1) + $signed(-22'sd2611) * $signed(a1_2) + $signed(22'sd893) * $signed(a1_3) + $signed(22'sd537) * $signed(a1_4) + $signed(22'sd1125) * $signed(a1_5) + $signed(22'sd83) * $signed(a1_6) + $signed(-22'sd16) * $signed(a1_7) + $signed(-22'sd2839) * $signed(a1_8) + $signed(-22'sd212) * $signed(a1_9) + $signed(22'sd565) * $signed(a1_10) + $signed(-22'sd743) * $signed(a1_11) + $signed(-22'sd110) * $signed(a1_12) + $signed(22'sd500) * $signed(a1_13) + $signed(22'sd683) * $signed(a1_14) + $signed(22'sd1097) * $signed(a1_15);
    wire signed [51:0] pre2_0 = (acc2_0 >>> 12) + $signed(22'sd458);
    reg signed [21:0] a2_0;
    always @(posedge clk) a2_0 <= (pre2_0 > 2097151) ? 2097151 : (pre2_0 < -2097152) ? -2097152 : pre2_0[21:0];
    assign y_out = a2_0;
endmodule
