// Generated by hardware/verilog_gen_stream.py -- do not edit by hand.
// Byte-serial streaming wrapper around mlp_exp_h8_d2 (W=16, 2 bytes/sample,
// core latency 3 cycles). 19 I/O pins total.

module mlp_exp_h8_d2_stream (
    input clk,
    input [7:0] in_data,
    input in_valid,
    output [7:0] out_data,
    output out_valid
);
    localparam W = 16, NIN = 2, WB = 16, LATENCY = 3;

    // ---- deserializer: NIN bytes little-endian -> one x sample ----
    reg [WB-1:0] in_shift = 0;
    reg [3:0] in_cnt = 0;
    reg sample_valid = 0;
    reg signed [W-1:0] x_s = 0;
    wire [WB-1:0] next_shift = {in_data, in_shift[WB-1:8]};
    always @(posedge clk) begin
        sample_valid <= 1'b0;
        if (in_valid) begin
            in_shift <= next_shift;
            if (in_cnt == NIN - 1) begin
                in_cnt <= 0;
                x_s <= next_shift[W-1:0];
                sample_valid <= 1'b1;
            end else
                in_cnt <= in_cnt + 1;
        end
    end

    // ---- core (streams every cycle; only sample_valid slots are real) ----
    wire signed [W-1:0] y_core;
    mlp_exp_h8_d2 u_core (.clk(clk), .x_in(x_s), .y_out(y_core));

    reg [LATENCY-1:0] vpipe = 0;
    always @(posedge clk)
        vpipe <= {vpipe[LATENCY-2:0], sample_valid};
    wire result_valid = vpipe[LATENCY-1];

    // ---- serializer: NIN bytes little-endian, sign-extended ----
    reg [WB-1:0] out_shift = 0;
    reg [3:0] out_cnt = 0;
    wire [WB-1:0] y_ext = {{(WB-W){y_core[W-1]}}, y_core};
    always @(posedge clk) begin
        if (result_valid) begin
            out_shift <= y_ext;
            out_cnt <= NIN;
        end else if (out_cnt != 0) begin
            out_shift <= {8'd0, out_shift[WB-1:8]};
            out_cnt <= out_cnt - 1;
        end
    end
    assign out_data = out_shift[7:0];
    assign out_valid = (out_cnt != 0);
endmodule
