// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_exp_h16_d2': 3 Linear layers, latency 3 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_exp_h16_d2 (
    input clk,
    input  signed [15:0] x_in,    // Q8.8, one sample per clock
    output signed [15:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 3;

    // ---- layer 0 (ReLU): 1 -> 16 ----
    wire signed [39:0] acc0_0 = $signed(16'sd79) * $signed(x_in);
    wire signed [39:0] pre0_0 = (acc0_0 >>> 8) + $signed(16'sd84);
    reg signed [15:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 16'sd0 : (pre0_0 > 32767) ? 32767 : pre0_0[15:0];
    wire signed [39:0] acc0_1 = $signed(-16'sd61) * $signed(x_in);
    wire signed [39:0] pre0_1 = (acc0_1 >>> 8) + $signed(-16'sd151);
    reg signed [15:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 16'sd0 : (pre0_1 > 32767) ? 32767 : pre0_1[15:0];
    wire signed [39:0] acc0_2 = $signed(16'sd141) * $signed(x_in);
    wire signed [39:0] pre0_2 = (acc0_2 >>> 8) + $signed(-16'sd102);
    reg signed [15:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 16'sd0 : (pre0_2 > 32767) ? 32767 : pre0_2[15:0];
    wire signed [39:0] acc0_3 = $signed(16'sd66) * $signed(x_in);
    wire signed [39:0] pre0_3 = (acc0_3 >>> 8) + $signed(16'sd309);
    reg signed [15:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 16'sd0 : (pre0_3 > 32767) ? 32767 : pre0_3[15:0];
    wire signed [39:0] acc0_4 = $signed(16'sd109) * $signed(x_in);
    wire signed [39:0] pre0_4 = (acc0_4 >>> 8) + $signed(-16'sd251);
    reg signed [15:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 16'sd0 : (pre0_4 > 32767) ? 32767 : pre0_4[15:0];
    wire signed [39:0] acc0_5 = $signed(16'sd116) * $signed(x_in);
    wire signed [39:0] pre0_5 = (acc0_5 >>> 8) + $signed(-16'sd10);
    reg signed [15:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 16'sd0 : (pre0_5 > 32767) ? 32767 : pre0_5[15:0];
    wire signed [39:0] acc0_6 = $signed(-16'sd96) * $signed(x_in);
    wire signed [39:0] pre0_6 = (acc0_6 >>> 8) + $signed(16'sd247);
    reg signed [15:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 16'sd0 : (pre0_6 > 32767) ? 32767 : pre0_6[15:0];
    wire signed [39:0] acc0_7 = $signed(-16'sd160) * $signed(x_in);
    wire signed [39:0] pre0_7 = (acc0_7 >>> 8) + $signed(16'sd338);
    reg signed [15:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 16'sd0 : (pre0_7 > 32767) ? 32767 : pre0_7[15:0];
    wire signed [39:0] acc0_8 = $signed(16'sd94) * $signed(x_in);
    wire signed [39:0] pre0_8 = (acc0_8 >>> 8) + $signed(-16'sd84);
    reg signed [15:0] a0_8;
    always @(posedge clk) a0_8 <= (pre0_8 <= 0) ? 16'sd0 : (pre0_8 > 32767) ? 32767 : pre0_8[15:0];
    wire signed [39:0] acc0_9 = $signed(-16'sd226) * $signed(x_in);
    wire signed [39:0] pre0_9 = (acc0_9 >>> 8) + $signed(16'sd116);
    reg signed [15:0] a0_9;
    always @(posedge clk) a0_9 <= (pre0_9 <= 0) ? 16'sd0 : (pre0_9 > 32767) ? 32767 : pre0_9[15:0];
    wire signed [39:0] acc0_10 = $signed(16'sd119) * $signed(x_in);
    wire signed [39:0] pre0_10 = (acc0_10 >>> 8) + $signed(16'sd39);
    reg signed [15:0] a0_10;
    always @(posedge clk) a0_10 <= (pre0_10 <= 0) ? 16'sd0 : (pre0_10 > 32767) ? 32767 : pre0_10[15:0];
    wire signed [39:0] acc0_11 = $signed(16'sd17) * $signed(x_in);
    wire signed [39:0] pre0_11 = (acc0_11 >>> 8) + $signed(-16'sd143);
    reg signed [15:0] a0_11;
    always @(posedge clk) a0_11 <= (pre0_11 <= 0) ? 16'sd0 : (pre0_11 > 32767) ? 32767 : pre0_11[15:0];
    wire signed [39:0] acc0_12 = $signed(-16'sd56) * $signed(x_in);
    wire signed [39:0] pre0_12 = (acc0_12 >>> 8) + $signed(-16'sd145);
    reg signed [15:0] a0_12;
    always @(posedge clk) a0_12 <= (pre0_12 <= 0) ? 16'sd0 : (pre0_12 > 32767) ? 32767 : pre0_12[15:0];
    wire signed [39:0] acc0_13 = $signed(16'sd281) * $signed(x_in);
    wire signed [39:0] pre0_13 = (acc0_13 >>> 8) + $signed(-16'sd128);
    reg signed [15:0] a0_13;
    always @(posedge clk) a0_13 <= (pre0_13 <= 0) ? 16'sd0 : (pre0_13 > 32767) ? 32767 : pre0_13[15:0];
    wire signed [39:0] acc0_14 = $signed(16'sd17) * $signed(x_in);
    wire signed [39:0] pre0_14 = (acc0_14 >>> 8) + $signed(-16'sd233);
    reg signed [15:0] a0_14;
    always @(posedge clk) a0_14 <= (pre0_14 <= 0) ? 16'sd0 : (pre0_14 > 32767) ? 32767 : pre0_14[15:0];
    wire signed [39:0] acc0_15 = $signed(16'sd154) * $signed(x_in);
    wire signed [39:0] pre0_15 = (acc0_15 >>> 8) + $signed(-16'sd218);
    reg signed [15:0] a0_15;
    always @(posedge clk) a0_15 <= (pre0_15 <= 0) ? 16'sd0 : (pre0_15 > 32767) ? 32767 : pre0_15[15:0];

    // ---- layer 1 (ReLU): 16 -> 16 ----
    wire signed [39:0] acc1_0 = $signed(16'sd11) * $signed(a0_0) + $signed(16'sd42) * $signed(a0_1) + $signed(16'sd99) * $signed(a0_2) + $signed(-16'sd58) * $signed(a0_3) + $signed(16'sd28) * $signed(a0_4) + $signed(16'sd22) * $signed(a0_5) + $signed(-16'sd609) * $signed(a0_6) + $signed(-16'sd282) * $signed(a0_7) + $signed(16'sd63) * $signed(a0_8) + $signed(-16'sd130) * $signed(a0_9) + $signed(16'sd56) * $signed(a0_10) + $signed(16'sd25) * $signed(a0_11) + $signed(16'sd13) * $signed(a0_12) + $signed(16'sd112) * $signed(a0_13) + $signed(16'sd27) * $signed(a0_14) + $signed(16'sd220) * $signed(a0_15);
    wire signed [39:0] pre1_0 = (acc1_0 >>> 8) + $signed(16'sd11);
    reg signed [15:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 <= 0) ? 16'sd0 : (pre1_0 > 32767) ? 32767 : pre1_0[15:0];
    wire signed [39:0] acc1_1 = $signed(16'sd72) * $signed(a0_0) + $signed(16'sd5) * $signed(a0_1) + $signed(16'sd117) * $signed(a0_2) + $signed(16'sd108) * $signed(a0_3) + $signed(16'sd46) * $signed(a0_4) + $signed(16'sd118) * $signed(a0_5) + $signed(-16'sd38) * $signed(a0_6) + $signed(-16'sd52) * $signed(a0_7) + $signed(16'sd79) * $signed(a0_8) + $signed(16'sd36) * $signed(a0_9) + $signed(16'sd82) * $signed(a0_10) + $signed(16'sd59) * $signed(a0_11) + $signed(16'sd32) * $signed(a0_12) + $signed(16'sd25) * $signed(a0_13) + $signed(16'sd19) * $signed(a0_14) + $signed(16'sd208) * $signed(a0_15);
    wire signed [39:0] pre1_1 = (acc1_1 >>> 8) + $signed(16'sd20);
    reg signed [15:0] a1_1;
    always @(posedge clk) a1_1 <= (pre1_1 <= 0) ? 16'sd0 : (pre1_1 > 32767) ? 32767 : pre1_1[15:0];
    wire signed [39:0] acc1_2 = $signed(16'sd73) * $signed(a0_0) + $signed(-16'sd1) * $signed(a0_1) + $signed(16'sd21) * $signed(a0_2) + $signed(-16'sd72) * $signed(a0_3) + $signed(-16'sd20) * $signed(a0_4) + $signed(16'sd31) * $signed(a0_5) + $signed(-16'sd94) * $signed(a0_6) + $signed(16'sd34) * $signed(a0_7) + $signed(-16'sd42) * $signed(a0_8) + $signed(-16'sd5) * $signed(a0_9) + $signed(16'sd14) * $signed(a0_10) + $signed(16'sd11) * $signed(a0_11) + $signed(16'sd6) * $signed(a0_12) + $signed(-16'sd60) * $signed(a0_13) + $signed(-16'sd14) * $signed(a0_14) + $signed(-16'sd40) * $signed(a0_15);
    wire signed [39:0] pre1_2 = (acc1_2 >>> 8) + $signed(-16'sd54);
    reg signed [15:0] a1_2;
    always @(posedge clk) a1_2 <= (pre1_2 <= 0) ? 16'sd0 : (pre1_2 > 32767) ? 32767 : pre1_2[15:0];
    wire signed [39:0] acc1_3 = $signed(16'sd30) * $signed(a0_0) + $signed(-16'sd8) * $signed(a0_1) + $signed(-16'sd86) * $signed(a0_2) + $signed(-16'sd10) * $signed(a0_3) + $signed(16'sd28) * $signed(a0_4) + $signed(-16'sd50) * $signed(a0_5) + $signed(-16'sd14) * $signed(a0_6) + $signed(16'sd0) * $signed(a0_7) + $signed(-16'sd61) * $signed(a0_8) + $signed(-16'sd56) * $signed(a0_9) + $signed(-16'sd32) * $signed(a0_10) + $signed(-16'sd45) * $signed(a0_11) + $signed(16'sd39) * $signed(a0_12) + $signed(-16'sd18) * $signed(a0_13) + $signed(16'sd38) * $signed(a0_14) + $signed(16'sd17) * $signed(a0_15);
    wire signed [39:0] pre1_3 = (acc1_3 >>> 8) + $signed(-16'sd18);
    reg signed [15:0] a1_3;
    always @(posedge clk) a1_3 <= (pre1_3 <= 0) ? 16'sd0 : (pre1_3 > 32767) ? 32767 : pre1_3[15:0];
    wire signed [39:0] acc1_4 = $signed(-16'sd27) * $signed(a0_0) + $signed(-16'sd40) * $signed(a0_1) + $signed(-16'sd74) * $signed(a0_2) + $signed(16'sd48) * $signed(a0_3) + $signed(-16'sd23) * $signed(a0_4) + $signed(-16'sd11) * $signed(a0_5) + $signed(-16'sd41) * $signed(a0_6) + $signed(16'sd83) * $signed(a0_7) + $signed(16'sd12) * $signed(a0_8) + $signed(16'sd23) * $signed(a0_9) + $signed(16'sd40) * $signed(a0_10) + $signed(16'sd48) * $signed(a0_11) + $signed(-16'sd63) * $signed(a0_12) + $signed(-16'sd26) * $signed(a0_13) + $signed(16'sd59) * $signed(a0_14) + $signed(-16'sd201) * $signed(a0_15);
    wire signed [39:0] pre1_4 = (acc1_4 >>> 8) + $signed(16'sd75);
    reg signed [15:0] a1_4;
    always @(posedge clk) a1_4 <= (pre1_4 <= 0) ? 16'sd0 : (pre1_4 > 32767) ? 32767 : pre1_4[15:0];
    wire signed [39:0] acc1_5 = $signed(16'sd46) * $signed(a0_0) + $signed(-16'sd3) * $signed(a0_1) + $signed(16'sd41) * $signed(a0_2) + $signed(16'sd43) * $signed(a0_3) + $signed(-16'sd9) * $signed(a0_4) + $signed(16'sd124) * $signed(a0_5) + $signed(-16'sd24) * $signed(a0_6) + $signed(-16'sd4) * $signed(a0_7) + $signed(16'sd138) * $signed(a0_8) + $signed(16'sd31) * $signed(a0_9) + $signed(16'sd19) * $signed(a0_10) + $signed(16'sd48) * $signed(a0_11) + $signed(16'sd42) * $signed(a0_12) + $signed(16'sd39) * $signed(a0_13) + $signed(-16'sd23) * $signed(a0_14) + $signed(16'sd243) * $signed(a0_15);
    wire signed [39:0] pre1_5 = (acc1_5 >>> 8) + $signed(16'sd19);
    reg signed [15:0] a1_5;
    always @(posedge clk) a1_5 <= (pre1_5 <= 0) ? 16'sd0 : (pre1_5 > 32767) ? 32767 : pre1_5[15:0];
    wire signed [39:0] acc1_6 = $signed(16'sd0) * $signed(a0_0) + $signed(-16'sd56) * $signed(a0_1) + $signed(16'sd50) * $signed(a0_2) + $signed(16'sd83) * $signed(a0_3) + $signed(-16'sd26) * $signed(a0_4) + $signed(16'sd21) * $signed(a0_5) + $signed(-16'sd4) * $signed(a0_6) + $signed(-16'sd21) * $signed(a0_7) + $signed(16'sd110) * $signed(a0_8) + $signed(-16'sd57) * $signed(a0_9) + $signed(16'sd140) * $signed(a0_10) + $signed(-16'sd5) * $signed(a0_11) + $signed(-16'sd61) * $signed(a0_12) + $signed(16'sd71) * $signed(a0_13) + $signed(16'sd42) * $signed(a0_14) + $signed(16'sd185) * $signed(a0_15);
    wire signed [39:0] pre1_6 = (acc1_6 >>> 8) + $signed(16'sd122);
    reg signed [15:0] a1_6;
    always @(posedge clk) a1_6 <= (pre1_6 <= 0) ? 16'sd0 : (pre1_6 > 32767) ? 32767 : pre1_6[15:0];
    wire signed [39:0] acc1_7 = $signed(-16'sd1) * $signed(a0_0) + $signed(16'sd45) * $signed(a0_1) + $signed(-16'sd58) * $signed(a0_2) + $signed(16'sd44) * $signed(a0_3) + $signed(16'sd64) * $signed(a0_4) + $signed(-16'sd39) * $signed(a0_5) + $signed(16'sd14) * $signed(a0_6) + $signed(-16'sd10) * $signed(a0_7) + $signed(-16'sd54) * $signed(a0_8) + $signed(-16'sd1) * $signed(a0_9) + $signed(-16'sd21) * $signed(a0_10) + $signed(-16'sd55) * $signed(a0_11) + $signed(-16'sd47) * $signed(a0_12) + $signed(16'sd1) * $signed(a0_13) + $signed(16'sd59) * $signed(a0_14) + $signed(16'sd23) * $signed(a0_15);
    wire signed [39:0] pre1_7 = (acc1_7 >>> 8) + $signed(-16'sd55);
    reg signed [15:0] a1_7;
    always @(posedge clk) a1_7 <= (pre1_7 <= 0) ? 16'sd0 : (pre1_7 > 32767) ? 32767 : pre1_7[15:0];
    wire signed [39:0] acc1_8 = $signed(-16'sd43) * $signed(a0_0) + $signed(16'sd44) * $signed(a0_1) + $signed(16'sd5) * $signed(a0_2) + $signed(-16'sd63) * $signed(a0_3) + $signed(16'sd3) * $signed(a0_4) + $signed(16'sd41) * $signed(a0_5) + $signed(-16'sd38) * $signed(a0_6) + $signed(-16'sd3) * $signed(a0_7) + $signed(-16'sd32) * $signed(a0_8) + $signed(-16'sd50) * $signed(a0_9) + $signed(-16'sd36) * $signed(a0_10) + $signed(16'sd6) * $signed(a0_11) + $signed(16'sd41) * $signed(a0_12) + $signed(-16'sd12) * $signed(a0_13) + $signed(-16'sd58) * $signed(a0_14) + $signed(-16'sd1) * $signed(a0_15);
    wire signed [39:0] pre1_8 = (acc1_8 >>> 8) + $signed(16'sd35);
    reg signed [15:0] a1_8;
    always @(posedge clk) a1_8 <= (pre1_8 <= 0) ? 16'sd0 : (pre1_8 > 32767) ? 32767 : pre1_8[15:0];
    wire signed [39:0] acc1_9 = $signed(16'sd8) * $signed(a0_0) + $signed(16'sd4) * $signed(a0_1) + $signed(16'sd143) * $signed(a0_2) + $signed(16'sd90) * $signed(a0_3) + $signed(-16'sd39) * $signed(a0_4) + $signed(16'sd66) * $signed(a0_5) + $signed(-16'sd29) * $signed(a0_6) + $signed(-16'sd52) * $signed(a0_7) + $signed(16'sd30) * $signed(a0_8) + $signed(-16'sd51) * $signed(a0_9) + $signed(16'sd56) * $signed(a0_10) + $signed(16'sd24) * $signed(a0_11) + $signed(16'sd57) * $signed(a0_12) + $signed(16'sd112) * $signed(a0_13) + $signed(16'sd24) * $signed(a0_14) + $signed(16'sd104) * $signed(a0_15);
    wire signed [39:0] pre1_9 = (acc1_9 >>> 8) + $signed(16'sd88);
    reg signed [15:0] a1_9;
    always @(posedge clk) a1_9 <= (pre1_9 <= 0) ? 16'sd0 : (pre1_9 > 32767) ? 32767 : pre1_9[15:0];
    wire signed [39:0] acc1_10 = $signed(-16'sd5) * $signed(a0_0) + $signed(16'sd23) * $signed(a0_1) + $signed(-16'sd27) * $signed(a0_2) + $signed(-16'sd12) * $signed(a0_3) + $signed(16'sd18) * $signed(a0_4) + $signed(-16'sd162) * $signed(a0_5) + $signed(16'sd29) * $signed(a0_6) + $signed(16'sd47) * $signed(a0_7) + $signed(-16'sd49) * $signed(a0_8) + $signed(-16'sd67) * $signed(a0_9) + $signed(-16'sd37) * $signed(a0_10) + $signed(-16'sd55) * $signed(a0_11) + $signed(-16'sd7) * $signed(a0_12) + $signed(16'sd10) * $signed(a0_13) + $signed(16'sd24) * $signed(a0_14) + $signed(-16'sd27) * $signed(a0_15);
    wire signed [39:0] pre1_10 = (acc1_10 >>> 8) + $signed(-16'sd9);
    reg signed [15:0] a1_10;
    always @(posedge clk) a1_10 <= (pre1_10 <= 0) ? 16'sd0 : (pre1_10 > 32767) ? 32767 : pre1_10[15:0];
    wire signed [39:0] acc1_11 = $signed(16'sd51) * $signed(a0_0) + $signed(-16'sd28) * $signed(a0_1) + $signed(16'sd35) * $signed(a0_2) + $signed(16'sd30) * $signed(a0_3) + $signed(16'sd4) * $signed(a0_4) + $signed(16'sd52) * $signed(a0_5) + $signed(-16'sd342) * $signed(a0_6) + $signed(-16'sd128) * $signed(a0_7) + $signed(16'sd109) * $signed(a0_8) + $signed(-16'sd70) * $signed(a0_9) + $signed(16'sd88) * $signed(a0_10) + $signed(16'sd59) * $signed(a0_11) + $signed(16'sd3) * $signed(a0_12) + $signed(16'sd44) * $signed(a0_13) + $signed(16'sd59) * $signed(a0_14) + $signed(16'sd189) * $signed(a0_15);
    wire signed [39:0] pre1_11 = (acc1_11 >>> 8) + $signed(16'sd66);
    reg signed [15:0] a1_11;
    always @(posedge clk) a1_11 <= (pre1_11 <= 0) ? 16'sd0 : (pre1_11 > 32767) ? 32767 : pre1_11[15:0];
    wire signed [39:0] acc1_12 = $signed(-16'sd28) * $signed(a0_0) + $signed(-16'sd29) * $signed(a0_1) + $signed(-16'sd38) * $signed(a0_2) + $signed(16'sd33) * $signed(a0_3) + $signed(16'sd33) * $signed(a0_4) + $signed(-16'sd49) * $signed(a0_5) + $signed(16'sd15) * $signed(a0_6) + $signed(-16'sd6) * $signed(a0_7) + $signed(16'sd2) * $signed(a0_8) + $signed(-16'sd6) * $signed(a0_9) + $signed(-16'sd57) * $signed(a0_10) + $signed(-16'sd2) * $signed(a0_11) + $signed(-16'sd18) * $signed(a0_12) + $signed(-16'sd38) * $signed(a0_13) + $signed(-16'sd32) * $signed(a0_14) + $signed(-16'sd39) * $signed(a0_15);
    wire signed [39:0] pre1_12 = (acc1_12 >>> 8) + $signed(-16'sd33);
    reg signed [15:0] a1_12;
    always @(posedge clk) a1_12 <= (pre1_12 <= 0) ? 16'sd0 : (pre1_12 > 32767) ? 32767 : pre1_12[15:0];
    wire signed [39:0] acc1_13 = $signed(-16'sd30) * $signed(a0_0) + $signed(16'sd25) * $signed(a0_1) + $signed(-16'sd54) * $signed(a0_2) + $signed(-16'sd61) * $signed(a0_3) + $signed(16'sd55) * $signed(a0_4) + $signed(16'sd23) * $signed(a0_5) + $signed(16'sd35) * $signed(a0_6) + $signed(16'sd28) * $signed(a0_7) + $signed(-16'sd24) * $signed(a0_8) + $signed(-16'sd40) * $signed(a0_9) + $signed(-16'sd44) * $signed(a0_10) + $signed(-16'sd4) * $signed(a0_11) + $signed(16'sd16) * $signed(a0_12) + $signed(-16'sd60) * $signed(a0_13) + $signed(-16'sd49) * $signed(a0_14) + $signed(16'sd36) * $signed(a0_15);
    wire signed [39:0] pre1_13 = (acc1_13 >>> 8) + $signed(-16'sd48);
    reg signed [15:0] a1_13;
    always @(posedge clk) a1_13 <= (pre1_13 <= 0) ? 16'sd0 : (pre1_13 > 32767) ? 32767 : pre1_13[15:0];
    wire signed [39:0] acc1_14 = $signed(16'sd73) * $signed(a0_0) + $signed(16'sd42) * $signed(a0_1) + $signed(16'sd152) * $signed(a0_2) + $signed(16'sd105) * $signed(a0_3) + $signed(-16'sd14) * $signed(a0_4) + $signed(16'sd52) * $signed(a0_5) + $signed(-16'sd7) * $signed(a0_6) + $signed(16'sd11) * $signed(a0_7) + $signed(16'sd29) * $signed(a0_8) + $signed(16'sd16) * $signed(a0_9) + $signed(16'sd29) * $signed(a0_10) + $signed(-16'sd51) * $signed(a0_11) + $signed(16'sd23) * $signed(a0_12) + $signed(16'sd117) * $signed(a0_13) + $signed(16'sd22) * $signed(a0_14) + $signed(16'sd179) * $signed(a0_15);
    wire signed [39:0] pre1_14 = (acc1_14 >>> 8) + $signed(16'sd104);
    reg signed [15:0] a1_14;
    always @(posedge clk) a1_14 <= (pre1_14 <= 0) ? 16'sd0 : (pre1_14 > 32767) ? 32767 : pre1_14[15:0];
    wire signed [39:0] acc1_15 = $signed(-16'sd19) * $signed(a0_0) + $signed(16'sd2) * $signed(a0_1) + $signed(-16'sd57) * $signed(a0_2) + $signed(-16'sd64) * $signed(a0_3) + $signed(16'sd1) * $signed(a0_4) + $signed(-16'sd15) * $signed(a0_5) + $signed(-16'sd35) * $signed(a0_6) + $signed(16'sd10) * $signed(a0_7) + $signed(16'sd24) * $signed(a0_8) + $signed(-16'sd39) * $signed(a0_9) + $signed(-16'sd21) * $signed(a0_10) + $signed(-16'sd46) * $signed(a0_11) + $signed(16'sd33) * $signed(a0_12) + $signed(-16'sd45) * $signed(a0_13) + $signed(16'sd20) * $signed(a0_14) + $signed(-16'sd12) * $signed(a0_15);
    wire signed [39:0] pre1_15 = (acc1_15 >>> 8) + $signed(-16'sd41);
    reg signed [15:0] a1_15;
    always @(posedge clk) a1_15 <= (pre1_15 <= 0) ? 16'sd0 : (pre1_15 > 32767) ? 32767 : pre1_15[15:0];

    // ---- layer 2 (linear out): 16 -> 1 ----
    wire signed [39:0] acc2_0 = $signed(16'sd141) * $signed(a1_0) + $signed(16'sd155) * $signed(a1_1) + $signed(16'sd35) * $signed(a1_2) + $signed(-16'sd27) * $signed(a1_3) + $signed(-16'sd86) * $signed(a1_4) + $signed(16'sd73) * $signed(a1_5) + $signed(16'sd118) * $signed(a1_6) + $signed(-16'sd47) * $signed(a1_7) + $signed(-16'sd47) * $signed(a1_8) + $signed(16'sd105) * $signed(a1_9) + $signed(-16'sd128) * $signed(a1_10) + $signed(16'sd144) * $signed(a1_11) + $signed(-16'sd29) * $signed(a1_12) + $signed(-16'sd38) * $signed(a1_13) + $signed(16'sd102) * $signed(a1_14) + $signed(16'sd35) * $signed(a1_15);
    wire signed [39:0] pre2_0 = (acc2_0 >>> 8) + $signed(16'sd30);
    reg signed [15:0] a2_0;
    always @(posedge clk) a2_0 <= (pre2_0 > 32767) ? 32767 : (pre2_0 < -32768) ? -32768 : pre2_0[15:0];
    assign y_out = a2_0;
endmodule
