// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_exp_h4_d2': 3 Linear layers, latency 3 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_exp_h4_d2 (
    input clk,
    input  signed [15:0] x_in,    // Q8.8, one sample per clock
    output signed [15:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 3;

    // ---- layer 0 (ReLU): 1 -> 4 ----
    wire signed [39:0] acc0_0 = $signed(16'sd18) * $signed(x_in);
    wire signed [39:0] pre0_0 = (acc0_0 >>> 8) + $signed(-16'sd137);
    reg signed [15:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 16'sd0 : (pre0_0 > 32767) ? 32767 : pre0_0[15:0];
    wire signed [39:0] acc0_1 = $signed(-16'sd194) * $signed(x_in);
    wire signed [39:0] pre0_1 = (acc0_1 >>> 8) + $signed(16'sd402);
    reg signed [15:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 16'sd0 : (pre0_1 > 32767) ? 32767 : pre0_1[15:0];
    wire signed [39:0] acc0_2 = $signed(16'sd222) * $signed(x_in);
    wire signed [39:0] pre0_2 = (acc0_2 >>> 8) + $signed(-16'sd113);
    reg signed [15:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 16'sd0 : (pre0_2 > 32767) ? 32767 : pre0_2[15:0];
    wire signed [39:0] acc0_3 = $signed(16'sd180) * $signed(x_in);
    wire signed [39:0] pre0_3 = (acc0_3 >>> 8) + $signed(16'sd115);
    reg signed [15:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 16'sd0 : (pre0_3 > 32767) ? 32767 : pre0_3[15:0];

    // ---- layer 1 (ReLU): 4 -> 4 ----
    wire signed [39:0] acc1_0 = $signed(-16'sd34) * $signed(a0_0) + $signed(-16'sd39) * $signed(a0_1) + $signed(16'sd289) * $signed(a0_2) + $signed(16'sd141) * $signed(a0_3);
    wire signed [39:0] pre1_0 = (acc1_0 >>> 8) + $signed(16'sd115);
    reg signed [15:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 <= 0) ? 16'sd0 : (pre1_0 > 32767) ? 32767 : pre1_0[15:0];
    wire signed [39:0] acc1_1 = $signed(-16'sd55) * $signed(a0_0) + $signed(-16'sd96) * $signed(a0_1) + $signed(-16'sd14) * $signed(a0_2) + $signed(-16'sd55) * $signed(a0_3);
    wire signed [39:0] pre1_1 = (acc1_1 >>> 8) + $signed(16'sd3);
    reg signed [15:0] a1_1;
    always @(posedge clk) a1_1 <= (pre1_1 <= 0) ? 16'sd0 : (pre1_1 > 32767) ? 32767 : pre1_1[15:0];
    wire signed [39:0] acc1_2 = $signed(16'sd56) * $signed(a0_0) + $signed(-16'sd664) * $signed(a0_1) + $signed(16'sd296) * $signed(a0_2) + $signed(-16'sd9) * $signed(a0_3);
    wire signed [39:0] pre1_2 = (acc1_2 >>> 8) + $signed(16'sd155);
    reg signed [15:0] a1_2;
    always @(posedge clk) a1_2 <= (pre1_2 <= 0) ? 16'sd0 : (pre1_2 > 32767) ? 32767 : pre1_2[15:0];
    wire signed [39:0] acc1_3 = $signed(16'sd98) * $signed(a0_0) + $signed(-16'sd51) * $signed(a0_1) + $signed(16'sd266) * $signed(a0_2) + $signed(16'sd183) * $signed(a0_3);
    wire signed [39:0] pre1_3 = (acc1_3 >>> 8) + $signed(16'sd152);
    reg signed [15:0] a1_3;
    always @(posedge clk) a1_3 <= (pre1_3 <= 0) ? 16'sd0 : (pre1_3 > 32767) ? 32767 : pre1_3[15:0];

    // ---- layer 2 (linear out): 4 -> 1 ----
    wire signed [39:0] acc2_0 = $signed(16'sd238) * $signed(a1_0) + $signed(-16'sd80) * $signed(a1_1) + $signed(16'sd249) * $signed(a1_2) + $signed(16'sd192) * $signed(a1_3);
    wire signed [39:0] pre2_0 = (acc2_0 >>> 8) + $signed(16'sd44);
    reg signed [15:0] a2_0;
    always @(posedge clk) a2_0 <= (pre2_0 > 32767) ? 32767 : (pre2_0 < -32768) ? -32768 : pre2_0[15:0];
    assign y_out = a2_0;
endmodule
