// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_ln_h32_d1': 2 Linear layers, latency 2 cycles,
// fully streaming (one sample per clock). Format Q10.12 (22 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_ln_h32_d1 (
    input clk,
    input  signed [21:0] x_in,    // Q10.12, one sample per clock
    output signed [21:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 2;

    // ---- layer 0 (ReLU): 1 -> 32 ----
    wire signed [51:0] acc0_0 = $signed(22'sd958) * $signed(x_in);
    wire signed [51:0] pre0_0 = (acc0_0 >>> 12) + $signed(22'sd2163);
    reg signed [21:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 22'sd0 : (pre0_0 > 2097151) ? 2097151 : pre0_0[21:0];
    wire signed [51:0] acc0_1 = $signed(-22'sd727) * $signed(x_in);
    wire signed [51:0] pre0_1 = (acc0_1 >>> 12) + $signed(22'sd4762);
    reg signed [21:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 22'sd0 : (pre0_1 > 2097151) ? 2097151 : pre0_1[21:0];
    wire signed [51:0] acc0_2 = $signed(22'sd1102) * $signed(x_in);
    wire signed [51:0] pre0_2 = (acc0_2 >>> 12) + $signed(22'sd1408);
    reg signed [21:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 22'sd0 : (pre0_2 > 2097151) ? 2097151 : pre0_2[21:0];
    wire signed [51:0] acc0_3 = $signed(-22'sd209) * $signed(x_in);
    wire signed [51:0] pre0_3 = (acc0_3 >>> 12) + $signed(-22'sd1878);
    reg signed [21:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 22'sd0 : (pre0_3 > 2097151) ? 2097151 : pre0_3[21:0];
    wire signed [51:0] acc0_4 = $signed(22'sd1456) * $signed(x_in);
    wire signed [51:0] pre0_4 = (acc0_4 >>> 12) + $signed(22'sd1409);
    reg signed [21:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 22'sd0 : (pre0_4 > 2097151) ? 2097151 : pre0_4[21:0];
    wire signed [51:0] acc0_5 = $signed(22'sd1028) * $signed(x_in);
    wire signed [51:0] pre0_5 = (acc0_5 >>> 12) + $signed(-22'sd635);
    reg signed [21:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 22'sd0 : (pre0_5 > 2097151) ? 2097151 : pre0_5[21:0];
    wire signed [51:0] acc0_6 = $signed(-22'sd471) * $signed(x_in);
    wire signed [51:0] pre0_6 = (acc0_6 >>> 12) + $signed(-22'sd907);
    reg signed [21:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 22'sd0 : (pre0_6 > 2097151) ? 2097151 : pre0_6[21:0];
    wire signed [51:0] acc0_7 = $signed(-22'sd3311) * $signed(x_in);
    wire signed [51:0] pre0_7 = (acc0_7 >>> 12) + $signed(-22'sd2245);
    reg signed [21:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 22'sd0 : (pre0_7 > 2097151) ? 2097151 : pre0_7[21:0];
    wire signed [51:0] acc0_8 = $signed(22'sd644) * $signed(x_in);
    wire signed [51:0] pre0_8 = (acc0_8 >>> 12) + $signed(-22'sd3085);
    reg signed [21:0] a0_8;
    always @(posedge clk) a0_8 <= (pre0_8 <= 0) ? 22'sd0 : (pre0_8 > 2097151) ? 2097151 : pre0_8[21:0];
    wire signed [51:0] acc0_9 = $signed(-22'sd3626) * $signed(x_in);
    wire signed [51:0] pre0_9 = (acc0_9 >>> 12) + $signed(-22'sd3795);
    reg signed [21:0] a0_9;
    always @(posedge clk) a0_9 <= (pre0_9 <= 0) ? 22'sd0 : (pre0_9 > 2097151) ? 2097151 : pre0_9[21:0];
    wire signed [51:0] acc0_10 = $signed(-22'sd120) * $signed(x_in);
    wire signed [51:0] pre0_10 = (acc0_10 >>> 12) + $signed(22'sd4369);
    reg signed [21:0] a0_10;
    always @(posedge clk) a0_10 <= (pre0_10 <= 0) ? 22'sd0 : (pre0_10 > 2097151) ? 2097151 : pre0_10[21:0];
    wire signed [51:0] acc0_11 = $signed(22'sd74) * $signed(x_in);
    wire signed [51:0] pre0_11 = (acc0_11 >>> 12) + $signed(22'sd3629);
    reg signed [21:0] a0_11;
    always @(posedge clk) a0_11 <= (pre0_11 <= 0) ? 22'sd0 : (pre0_11 > 2097151) ? 2097151 : pre0_11[21:0];
    wire signed [51:0] acc0_12 = $signed(-22'sd1887) * $signed(x_in);
    wire signed [51:0] pre0_12 = (acc0_12 >>> 12) + $signed(22'sd2871);
    reg signed [21:0] a0_12;
    always @(posedge clk) a0_12 <= (pre0_12 <= 0) ? 22'sd0 : (pre0_12 > 2097151) ? 2097151 : pre0_12[21:0];
    wire signed [51:0] acc0_13 = $signed(22'sd3225) * $signed(x_in);
    wire signed [51:0] pre0_13 = (acc0_13 >>> 12) + $signed(22'sd1065);
    reg signed [21:0] a0_13;
    always @(posedge clk) a0_13 <= (pre0_13 <= 0) ? 22'sd0 : (pre0_13 > 2097151) ? 2097151 : pre0_13[21:0];
    wire signed [51:0] acc0_14 = $signed(-22'sd405) * $signed(x_in);
    wire signed [51:0] pre0_14 = (acc0_14 >>> 12) + $signed(22'sd4055);
    reg signed [21:0] a0_14;
    always @(posedge clk) a0_14 <= (pre0_14 <= 0) ? 22'sd0 : (pre0_14 > 2097151) ? 2097151 : pre0_14[21:0];
    wire signed [51:0] acc0_15 = $signed(22'sd1556) * $signed(x_in);
    wire signed [51:0] pre0_15 = (acc0_15 >>> 12) + $signed(-22'sd794);
    reg signed [21:0] a0_15;
    always @(posedge clk) a0_15 <= (pre0_15 <= 0) ? 22'sd0 : (pre0_15 > 2097151) ? 2097151 : pre0_15[21:0];
    wire signed [51:0] acc0_16 = $signed(22'sd1760) * $signed(x_in);
    wire signed [51:0] pre0_16 = (acc0_16 >>> 12) + $signed(22'sd1580);
    reg signed [21:0] a0_16;
    always @(posedge clk) a0_16 <= (pre0_16 <= 0) ? 22'sd0 : (pre0_16 > 2097151) ? 2097151 : pre0_16[21:0];
    wire signed [51:0] acc0_17 = $signed(-22'sd4439) * $signed(x_in);
    wire signed [51:0] pre0_17 = (acc0_17 >>> 12) + $signed(22'sd2005);
    reg signed [21:0] a0_17;
    always @(posedge clk) a0_17 <= (pre0_17 <= 0) ? 22'sd0 : (pre0_17 > 2097151) ? 2097151 : pre0_17[21:0];
    wire signed [51:0] acc0_18 = $signed(-22'sd1523) * $signed(x_in);
    wire signed [51:0] pre0_18 = (acc0_18 >>> 12) + $signed(22'sd3511);
    reg signed [21:0] a0_18;
    always @(posedge clk) a0_18 <= (pre0_18 <= 0) ? 22'sd0 : (pre0_18 > 2097151) ? 2097151 : pre0_18[21:0];
    wire signed [51:0] acc0_19 = $signed(22'sd3885) * $signed(x_in);
    wire signed [51:0] pre0_19 = (acc0_19 >>> 12) + $signed(22'sd4077);
    reg signed [21:0] a0_19;
    always @(posedge clk) a0_19 <= (pre0_19 <= 0) ? 22'sd0 : (pre0_19 > 2097151) ? 2097151 : pre0_19[21:0];
    wire signed [51:0] acc0_20 = $signed(-22'sd6107) * $signed(x_in);
    wire signed [51:0] pre0_20 = (acc0_20 >>> 12) + $signed(22'sd4359);
    reg signed [21:0] a0_20;
    always @(posedge clk) a0_20 <= (pre0_20 <= 0) ? 22'sd0 : (pre0_20 > 2097151) ? 2097151 : pre0_20[21:0];
    wire signed [51:0] acc0_21 = $signed(-22'sd473) * $signed(x_in);
    wire signed [51:0] pre0_21 = (acc0_21 >>> 12) + $signed(22'sd2235);
    reg signed [21:0] a0_21;
    always @(posedge clk) a0_21 <= (pre0_21 <= 0) ? 22'sd0 : (pre0_21 > 2097151) ? 2097151 : pre0_21[21:0];
    wire signed [51:0] acc0_22 = $signed(-22'sd325) * $signed(x_in);
    wire signed [51:0] pre0_22 = (acc0_22 >>> 12) + $signed(-22'sd999);
    reg signed [21:0] a0_22;
    always @(posedge clk) a0_22 <= (pre0_22 <= 0) ? 22'sd0 : (pre0_22 > 2097151) ? 2097151 : pre0_22[21:0];
    wire signed [51:0] acc0_23 = $signed(22'sd2909) * $signed(x_in);
    wire signed [51:0] pre0_23 = (acc0_23 >>> 12) + $signed(22'sd960);
    reg signed [21:0] a0_23;
    always @(posedge clk) a0_23 <= (pre0_23 <= 0) ? 22'sd0 : (pre0_23 > 2097151) ? 2097151 : pre0_23[21:0];
    wire signed [51:0] acc0_24 = $signed(-22'sd389) * $signed(x_in);
    wire signed [51:0] pre0_24 = (acc0_24 >>> 12) + $signed(-22'sd832);
    reg signed [21:0] a0_24;
    always @(posedge clk) a0_24 <= (pre0_24 <= 0) ? 22'sd0 : (pre0_24 > 2097151) ? 2097151 : pre0_24[21:0];
    wire signed [51:0] acc0_25 = $signed(22'sd863) * $signed(x_in);
    wire signed [51:0] pre0_25 = (acc0_25 >>> 12) + $signed(22'sd1824);
    reg signed [21:0] a0_25;
    always @(posedge clk) a0_25 <= (pre0_25 <= 0) ? 22'sd0 : (pre0_25 > 2097151) ? 2097151 : pre0_25[21:0];
    wire signed [51:0] acc0_26 = $signed(-22'sd347) * $signed(x_in);
    wire signed [51:0] pre0_26 = (acc0_26 >>> 12) + $signed(22'sd545);
    reg signed [21:0] a0_26;
    always @(posedge clk) a0_26 <= (pre0_26 <= 0) ? 22'sd0 : (pre0_26 > 2097151) ? 2097151 : pre0_26[21:0];
    wire signed [51:0] acc0_27 = $signed(-22'sd1392) * $signed(x_in);
    wire signed [51:0] pre0_27 = (acc0_27 >>> 12) + $signed(22'sd4998);
    reg signed [21:0] a0_27;
    always @(posedge clk) a0_27 <= (pre0_27 <= 0) ? 22'sd0 : (pre0_27 > 2097151) ? 2097151 : pre0_27[21:0];
    wire signed [51:0] acc0_28 = $signed(-22'sd5707) * $signed(x_in);
    wire signed [51:0] pre0_28 = (acc0_28 >>> 12) + $signed(22'sd1966);
    reg signed [21:0] a0_28;
    always @(posedge clk) a0_28 <= (pre0_28 <= 0) ? 22'sd0 : (pre0_28 > 2097151) ? 2097151 : pre0_28[21:0];
    wire signed [51:0] acc0_29 = $signed(-22'sd1990) * $signed(x_in);
    wire signed [51:0] pre0_29 = (acc0_29 >>> 12) + $signed(-22'sd3501);
    reg signed [21:0] a0_29;
    always @(posedge clk) a0_29 <= (pre0_29 <= 0) ? 22'sd0 : (pre0_29 > 2097151) ? 2097151 : pre0_29[21:0];
    wire signed [51:0] acc0_30 = $signed(-22'sd11169) * $signed(x_in);
    wire signed [51:0] pre0_30 = (acc0_30 >>> 12) + $signed(22'sd2430);
    reg signed [21:0] a0_30;
    always @(posedge clk) a0_30 <= (pre0_30 <= 0) ? 22'sd0 : (pre0_30 > 2097151) ? 2097151 : pre0_30[21:0];
    wire signed [51:0] acc0_31 = $signed(-22'sd4657) * $signed(x_in);
    wire signed [51:0] pre0_31 = (acc0_31 >>> 12) + $signed(22'sd4951);
    reg signed [21:0] a0_31;
    always @(posedge clk) a0_31 <= (pre0_31 <= 0) ? 22'sd0 : (pre0_31 > 2097151) ? 2097151 : pre0_31[21:0];

    // ---- layer 1 (linear out): 32 -> 1 ----
    wire signed [51:0] acc1_0 = $signed(22'sd896) * $signed(a0_0) + $signed(-22'sd1476) * $signed(a0_1) + $signed(22'sd391) * $signed(a0_2) + $signed(-22'sd679) * $signed(a0_3) + $signed(-22'sd18) * $signed(a0_4) + $signed(22'sd180) * $signed(a0_5) + $signed(-22'sd660) * $signed(a0_6) + $signed(22'sd631) * $signed(a0_7) + $signed(-22'sd855) * $signed(a0_8) + $signed(22'sd229) * $signed(a0_9) + $signed(22'sd572) * $signed(a0_10) + $signed(22'sd783) * $signed(a0_11) + $signed(-22'sd2187) * $signed(a0_12) + $signed(-22'sd532) * $signed(a0_13) + $signed(22'sd788) * $signed(a0_14) + $signed(-22'sd398) * $signed(a0_15) + $signed(22'sd755) * $signed(a0_16) + $signed(-22'sd3587) * $signed(a0_17) + $signed(-22'sd2099) * $signed(a0_18) + $signed(22'sd359) * $signed(a0_19) + $signed(-22'sd1740) * $signed(a0_20) + $signed(-22'sd267) * $signed(a0_21) + $signed(-22'sd68) * $signed(a0_22) + $signed(22'sd395) * $signed(a0_23) + $signed(-22'sd451) * $signed(a0_24) + $signed(-22'sd54) * $signed(a0_25) + $signed(-22'sd331) * $signed(a0_26) + $signed(-22'sd1421) * $signed(a0_27) + $signed(-22'sd1531) * $signed(a0_28) + $signed(22'sd59) * $signed(a0_29) + $signed(-22'sd4971) * $signed(a0_30) + $signed(-22'sd1183) * $signed(a0_31);
    wire signed [51:0] pre1_0 = (acc1_0 >>> 12) + $signed(22'sd516);
    reg signed [21:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 > 2097151) ? 2097151 : (pre1_0 < -2097152) ? -2097152 : pre1_0[21:0];
    assign y_out = a1_0;
endmodule
