// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_exp_h32_d1': 2 Linear layers, latency 2 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_exp_h32_d1 (
    input clk,
    input  signed [15:0] x_in,    // Q8.8, one sample per clock
    output signed [15:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 2;

    // ---- layer 0 (ReLU): 1 -> 32 ----
    wire signed [39:0] acc0_0 = $signed(16'sd210) * $signed(x_in);
    wire signed [39:0] pre0_0 = (acc0_0 >>> 8) + $signed(-16'sd310);
    reg signed [15:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 16'sd0 : (pre0_0 > 32767) ? 32767 : pre0_0[15:0];
    wire signed [39:0] acc0_1 = $signed(-16'sd229) * $signed(x_in);
    wire signed [39:0] pre0_1 = (acc0_1 >>> 8) + $signed(16'sd305);
    reg signed [15:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 16'sd0 : (pre0_1 > 32767) ? 32767 : pre0_1[15:0];
    wire signed [39:0] acc0_2 = $signed(16'sd298) * $signed(x_in);
    wire signed [39:0] pre0_2 = (acc0_2 >>> 8) + $signed(16'sd118);
    reg signed [15:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 16'sd0 : (pre0_2 > 32767) ? 32767 : pre0_2[15:0];
    wire signed [39:0] acc0_3 = $signed(16'sd236) * $signed(x_in);
    wire signed [39:0] pre0_3 = (acc0_3 >>> 8) + $signed(16'sd114);
    reg signed [15:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 16'sd0 : (pre0_3 > 32767) ? 32767 : pre0_3[15:0];
    wire signed [39:0] acc0_4 = $signed(16'sd280) * $signed(x_in);
    wire signed [39:0] pre0_4 = (acc0_4 >>> 8) + $signed(16'sd239);
    reg signed [15:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 16'sd0 : (pre0_4 > 32767) ? 32767 : pre0_4[15:0];
    wire signed [39:0] acc0_5 = $signed(-16'sd219) * $signed(x_in);
    wire signed [39:0] pre0_5 = (acc0_5 >>> 8) + $signed(-16'sd190);
    reg signed [15:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 16'sd0 : (pre0_5 > 32767) ? 32767 : pre0_5[15:0];
    wire signed [39:0] acc0_6 = $signed(-16'sd205) * $signed(x_in);
    wire signed [39:0] pre0_6 = (acc0_6 >>> 8) + $signed(16'sd329);
    reg signed [15:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 16'sd0 : (pre0_6 > 32767) ? 32767 : pre0_6[15:0];
    wire signed [39:0] acc0_7 = $signed(16'sd102) * $signed(x_in);
    wire signed [39:0] pre0_7 = (acc0_7 >>> 8) + $signed(16'sd211);
    reg signed [15:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 16'sd0 : (pre0_7 > 32767) ? 32767 : pre0_7[15:0];
    wire signed [39:0] acc0_8 = $signed(-16'sd362) * $signed(x_in);
    wire signed [39:0] pre0_8 = (acc0_8 >>> 8) + $signed(16'sd625);
    reg signed [15:0] a0_8;
    always @(posedge clk) a0_8 <= (pre0_8 <= 0) ? 16'sd0 : (pre0_8 > 32767) ? 32767 : pre0_8[15:0];
    wire signed [39:0] acc0_9 = $signed(16'sd321) * $signed(x_in);
    wire signed [39:0] pre0_9 = (acc0_9 >>> 8) + $signed(-16'sd139);
    reg signed [15:0] a0_9;
    always @(posedge clk) a0_9 <= (pre0_9 <= 0) ? 16'sd0 : (pre0_9 > 32767) ? 32767 : pre0_9[15:0];
    wire signed [39:0] acc0_10 = $signed(16'sd54) * $signed(x_in);
    wire signed [39:0] pre0_10 = (acc0_10 >>> 8) + $signed(-16'sd231);
    reg signed [15:0] a0_10;
    always @(posedge clk) a0_10 <= (pre0_10 <= 0) ? 16'sd0 : (pre0_10 > 32767) ? 32767 : pre0_10[15:0];
    wire signed [39:0] acc0_11 = $signed(16'sd94) * $signed(x_in);
    wire signed [39:0] pre0_11 = (acc0_11 >>> 8) + $signed(16'sd119);
    reg signed [15:0] a0_11;
    always @(posedge clk) a0_11 <= (pre0_11 <= 0) ? 16'sd0 : (pre0_11 > 32767) ? 32767 : pre0_11[15:0];
    wire signed [39:0] acc0_12 = $signed(-16'sd258) * $signed(x_in);
    wire signed [39:0] pre0_12 = (acc0_12 >>> 8) + $signed(16'sd203);
    reg signed [15:0] a0_12;
    always @(posedge clk) a0_12 <= (pre0_12 <= 0) ? 16'sd0 : (pre0_12 > 32767) ? 32767 : pre0_12[15:0];
    wire signed [39:0] acc0_13 = $signed(16'sd136) * $signed(x_in);
    wire signed [39:0] pre0_13 = (acc0_13 >>> 8) + $signed(16'sd211);
    reg signed [15:0] a0_13;
    always @(posedge clk) a0_13 <= (pre0_13 <= 0) ? 16'sd0 : (pre0_13 > 32767) ? 32767 : pre0_13[15:0];
    wire signed [39:0] acc0_14 = $signed(16'sd103) * $signed(x_in);
    wire signed [39:0] pre0_14 = (acc0_14 >>> 8) + $signed(16'sd168);
    reg signed [15:0] a0_14;
    always @(posedge clk) a0_14 <= (pre0_14 <= 0) ? 16'sd0 : (pre0_14 > 32767) ? 32767 : pre0_14[15:0];
    wire signed [39:0] acc0_15 = $signed(16'sd132) * $signed(x_in);
    wire signed [39:0] pre0_15 = (acc0_15 >>> 8) + $signed(-16'sd45);
    reg signed [15:0] a0_15;
    always @(posedge clk) a0_15 <= (pre0_15 <= 0) ? 16'sd0 : (pre0_15 > 32767) ? 32767 : pre0_15[15:0];
    wire signed [39:0] acc0_16 = $signed(16'sd271) * $signed(x_in);
    wire signed [39:0] pre0_16 = (acc0_16 >>> 8) + $signed(16'sd97);
    reg signed [15:0] a0_16;
    always @(posedge clk) a0_16 <= (pre0_16 <= 0) ? 16'sd0 : (pre0_16 > 32767) ? 32767 : pre0_16[15:0];
    wire signed [39:0] acc0_17 = $signed(16'sd296) * $signed(x_in);
    wire signed [39:0] pre0_17 = (acc0_17 >>> 8) + $signed(-16'sd319);
    reg signed [15:0] a0_17;
    always @(posedge clk) a0_17 <= (pre0_17 <= 0) ? 16'sd0 : (pre0_17 > 32767) ? 32767 : pre0_17[15:0];
    wire signed [39:0] acc0_18 = $signed(-16'sd338) * $signed(x_in);
    wire signed [39:0] pre0_18 = (acc0_18 >>> 8) + $signed(16'sd677);
    reg signed [15:0] a0_18;
    always @(posedge clk) a0_18 <= (pre0_18 <= 0) ? 16'sd0 : (pre0_18 > 32767) ? 32767 : pre0_18[15:0];
    wire signed [39:0] acc0_19 = $signed(16'sd295) * $signed(x_in);
    wire signed [39:0] pre0_19 = (acc0_19 >>> 8) + $signed(-16'sd47);
    reg signed [15:0] a0_19;
    always @(posedge clk) a0_19 <= (pre0_19 <= 0) ? 16'sd0 : (pre0_19 > 32767) ? 32767 : pre0_19[15:0];
    wire signed [39:0] acc0_20 = $signed(16'sd170) * $signed(x_in);
    wire signed [39:0] pre0_20 = (acc0_20 >>> 8) + $signed(-16'sd123);
    reg signed [15:0] a0_20;
    always @(posedge clk) a0_20 <= (pre0_20 <= 0) ? 16'sd0 : (pre0_20 > 32767) ? 32767 : pre0_20[15:0];
    wire signed [39:0] acc0_21 = $signed(-16'sd160) * $signed(x_in);
    wire signed [39:0] pre0_21 = (acc0_21 >>> 8) + $signed(-16'sd68);
    reg signed [15:0] a0_21;
    always @(posedge clk) a0_21 <= (pre0_21 <= 0) ? 16'sd0 : (pre0_21 > 32767) ? 32767 : pre0_21[15:0];
    wire signed [39:0] acc0_22 = $signed(-16'sd220) * $signed(x_in);
    wire signed [39:0] pre0_22 = (acc0_22 >>> 8) + $signed(16'sd442);
    reg signed [15:0] a0_22;
    always @(posedge clk) a0_22 <= (pre0_22 <= 0) ? 16'sd0 : (pre0_22 > 32767) ? 32767 : pre0_22[15:0];
    wire signed [39:0] acc0_23 = $signed(16'sd186) * $signed(x_in);
    wire signed [39:0] pre0_23 = (acc0_23 >>> 8) + $signed(16'sd15);
    reg signed [15:0] a0_23;
    always @(posedge clk) a0_23 <= (pre0_23 <= 0) ? 16'sd0 : (pre0_23 > 32767) ? 32767 : pre0_23[15:0];
    wire signed [39:0] acc0_24 = $signed(16'sd333) * $signed(x_in);
    wire signed [39:0] pre0_24 = (acc0_24 >>> 8) + $signed(16'sd126);
    reg signed [15:0] a0_24;
    always @(posedge clk) a0_24 <= (pre0_24 <= 0) ? 16'sd0 : (pre0_24 > 32767) ? 32767 : pre0_24[15:0];
    wire signed [39:0] acc0_25 = $signed(-16'sd245) * $signed(x_in);
    wire signed [39:0] pre0_25 = (acc0_25 >>> 8) + $signed(-16'sd105);
    reg signed [15:0] a0_25;
    always @(posedge clk) a0_25 <= (pre0_25 <= 0) ? 16'sd0 : (pre0_25 > 32767) ? 32767 : pre0_25[15:0];
    wire signed [39:0] acc0_26 = $signed(16'sd14) * $signed(x_in);
    wire signed [39:0] pre0_26 = (acc0_26 >>> 8) + $signed(-16'sd136);
    reg signed [15:0] a0_26;
    always @(posedge clk) a0_26 <= (pre0_26 <= 0) ? 16'sd0 : (pre0_26 > 32767) ? 32767 : pre0_26[15:0];
    wire signed [39:0] acc0_27 = $signed(16'sd143) * $signed(x_in);
    wire signed [39:0] pre0_27 = (acc0_27 >>> 8) + $signed(16'sd175);
    reg signed [15:0] a0_27;
    always @(posedge clk) a0_27 <= (pre0_27 <= 0) ? 16'sd0 : (pre0_27 > 32767) ? 32767 : pre0_27[15:0];
    wire signed [39:0] acc0_28 = $signed(-16'sd116) * $signed(x_in);
    wire signed [39:0] pre0_28 = (acc0_28 >>> 8) + $signed(-16'sd176);
    reg signed [15:0] a0_28;
    always @(posedge clk) a0_28 <= (pre0_28 <= 0) ? 16'sd0 : (pre0_28 > 32767) ? 32767 : pre0_28[15:0];
    wire signed [39:0] acc0_29 = $signed(-16'sd56) * $signed(x_in);
    wire signed [39:0] pre0_29 = (acc0_29 >>> 8) + $signed(-16'sd146);
    reg signed [15:0] a0_29;
    always @(posedge clk) a0_29 <= (pre0_29 <= 0) ? 16'sd0 : (pre0_29 > 32767) ? 32767 : pre0_29[15:0];
    wire signed [39:0] acc0_30 = $signed(-16'sd166) * $signed(x_in);
    wire signed [39:0] pre0_30 = (acc0_30 >>> 8) + $signed(-16'sd72);
    reg signed [15:0] a0_30;
    always @(posedge clk) a0_30 <= (pre0_30 <= 0) ? 16'sd0 : (pre0_30 > 32767) ? 32767 : pre0_30[15:0];
    wire signed [39:0] acc0_31 = $signed(-16'sd175) * $signed(x_in);
    wire signed [39:0] pre0_31 = (acc0_31 >>> 8) + $signed(16'sd62);
    reg signed [15:0] a0_31;
    always @(posedge clk) a0_31 <= (pre0_31 <= 0) ? 16'sd0 : (pre0_31 > 32767) ? 32767 : pre0_31[15:0];

    // ---- layer 1 (linear out): 32 -> 1 ----
    wire signed [39:0] acc1_0 = $signed(16'sd190) * $signed(a0_0) + $signed(16'sd177) * $signed(a0_1) + $signed(16'sd46) * $signed(a0_2) + $signed(16'sd61) * $signed(a0_3) + $signed(16'sd69) * $signed(a0_4) + $signed(-16'sd41) * $signed(a0_5) + $signed(16'sd199) * $signed(a0_6) + $signed(16'sd4) * $signed(a0_7) + $signed(16'sd168) * $signed(a0_8) + $signed(16'sd107) * $signed(a0_9) + $signed(16'sd42) * $signed(a0_10) + $signed(16'sd67) * $signed(a0_11) + $signed(16'sd71) * $signed(a0_12) + $signed(16'sd70) * $signed(a0_13) + $signed(16'sd12) * $signed(a0_14) + $signed(16'sd49) * $signed(a0_15) + $signed(16'sd25) * $signed(a0_16) + $signed(16'sd218) * $signed(a0_17) + $signed(-16'sd217) * $signed(a0_18) + $signed(16'sd88) * $signed(a0_19) + $signed(16'sd138) * $signed(a0_20) + $signed(-16'sd61) * $signed(a0_21) + $signed(-16'sd197) * $signed(a0_22) + $signed(16'sd31) * $signed(a0_23) + $signed(16'sd48) * $signed(a0_24) + $signed(-16'sd47) * $signed(a0_25) + $signed(-16'sd28) * $signed(a0_26) + $signed(16'sd19) * $signed(a0_27) + $signed(-16'sd62) * $signed(a0_28) + $signed(16'sd1) * $signed(a0_29) + $signed(-16'sd39) * $signed(a0_30) + $signed(-16'sd58) * $signed(a0_31);
    wire signed [39:0] pre1_0 = (acc1_0 >>> 8) + $signed(-16'sd7);
    reg signed [15:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 > 32767) ? 32767 : (pre1_0 < -32768) ? -32768 : pre1_0[15:0];
    assign y_out = a1_0;
endmodule
