// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_ln_h16_d1': 2 Linear layers, latency 2 cycles,
// fully streaming (one sample per clock). Format Q10.12 (22 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_ln_h16_d1 (
    input clk,
    input  signed [21:0] x_in,    // Q10.12, one sample per clock
    output signed [21:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 2;

    // ---- layer 0 (ReLU): 1 -> 16 ----
    wire signed [51:0] acc0_0 = $signed(22'sd329) * $signed(x_in);
    wire signed [51:0] pre0_0 = (acc0_0 >>> 12) + $signed(22'sd3643);
    reg signed [21:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 22'sd0 : (pre0_0 > 2097151) ? 2097151 : pre0_0[21:0];
    wire signed [51:0] acc0_1 = $signed(-22'sd2467) * $signed(x_in);
    wire signed [51:0] pre0_1 = (acc0_1 >>> 12) + $signed(-22'sd3498);
    reg signed [21:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 22'sd0 : (pre0_1 > 2097151) ? 2097151 : pre0_1[21:0];
    wire signed [51:0] acc0_2 = $signed(22'sd1432) * $signed(x_in);
    wire signed [51:0] pre0_2 = (acc0_2 >>> 12) + $signed(22'sd5350);
    reg signed [21:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 22'sd0 : (pre0_2 > 2097151) ? 2097151 : pre0_2[21:0];
    wire signed [51:0] acc0_3 = $signed(22'sd1477) * $signed(x_in);
    wire signed [51:0] pre0_3 = (acc0_3 >>> 12) + $signed(-22'sd2078);
    reg signed [21:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 22'sd0 : (pre0_3 > 2097151) ? 2097151 : pre0_3[21:0];
    wire signed [51:0] acc0_4 = $signed(-22'sd3625) * $signed(x_in);
    wire signed [51:0] pre0_4 = (acc0_4 >>> 12) + $signed(22'sd5270);
    reg signed [21:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 22'sd0 : (pre0_4 > 2097151) ? 2097151 : pre0_4[21:0];
    wire signed [51:0] acc0_5 = $signed(-22'sd614) * $signed(x_in);
    wire signed [51:0] pre0_5 = (acc0_5 >>> 12) + $signed(-22'sd711);
    reg signed [21:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 22'sd0 : (pre0_5 > 2097151) ? 2097151 : pre0_5[21:0];
    wire signed [51:0] acc0_6 = $signed(-22'sd6386) * $signed(x_in);
    wire signed [51:0] pre0_6 = (acc0_6 >>> 12) + $signed(22'sd3900);
    reg signed [21:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 22'sd0 : (pre0_6 > 2097151) ? 2097151 : pre0_6[21:0];
    wire signed [51:0] acc0_7 = $signed(22'sd745) * $signed(x_in);
    wire signed [51:0] pre0_7 = (acc0_7 >>> 12) + $signed(22'sd870);
    reg signed [21:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 22'sd0 : (pre0_7 > 2097151) ? 2097151 : pre0_7[21:0];
    wire signed [51:0] acc0_8 = $signed(-22'sd1293) * $signed(x_in);
    wire signed [51:0] pre0_8 = (acc0_8 >>> 12) + $signed(-22'sd22);
    reg signed [21:0] a0_8;
    always @(posedge clk) a0_8 <= (pre0_8 <= 0) ? 22'sd0 : (pre0_8 > 2097151) ? 2097151 : pre0_8[21:0];
    wire signed [51:0] acc0_9 = $signed(22'sd2555) * $signed(x_in);
    wire signed [51:0] pre0_9 = (acc0_9 >>> 12) + $signed(22'sd21);
    reg signed [21:0] a0_9;
    always @(posedge clk) a0_9 <= (pre0_9 <= 0) ? 22'sd0 : (pre0_9 > 2097151) ? 2097151 : pre0_9[21:0];
    wire signed [51:0] acc0_10 = $signed(22'sd2580) * $signed(x_in);
    wire signed [51:0] pre0_10 = (acc0_10 >>> 12) + $signed(22'sd2409);
    reg signed [21:0] a0_10;
    always @(posedge clk) a0_10 <= (pre0_10 <= 0) ? 22'sd0 : (pre0_10 > 2097151) ? 2097151 : pre0_10[21:0];
    wire signed [51:0] acc0_11 = $signed(22'sd584) * $signed(x_in);
    wire signed [51:0] pre0_11 = (acc0_11 >>> 12) + $signed(22'sd2397);
    reg signed [21:0] a0_11;
    always @(posedge clk) a0_11 <= (pre0_11 <= 0) ? 22'sd0 : (pre0_11 > 2097151) ? 2097151 : pre0_11[21:0];
    wire signed [51:0] acc0_12 = $signed(-22'sd9440) * $signed(x_in);
    wire signed [51:0] pre0_12 = (acc0_12 >>> 12) + $signed(22'sd2670);
    reg signed [21:0] a0_12;
    always @(posedge clk) a0_12 <= (pre0_12 <= 0) ? 22'sd0 : (pre0_12 > 2097151) ? 2097151 : pre0_12[21:0];
    wire signed [51:0] acc0_13 = $signed(-22'sd2406) * $signed(x_in);
    wire signed [51:0] pre0_13 = (acc0_13 >>> 12) + $signed(-22'sd3168);
    reg signed [21:0] a0_13;
    always @(posedge clk) a0_13 <= (pre0_13 <= 0) ? 22'sd0 : (pre0_13 > 2097151) ? 2097151 : pre0_13[21:0];
    wire signed [51:0] acc0_14 = $signed(-22'sd989) * $signed(x_in);
    wire signed [51:0] pre0_14 = (acc0_14 >>> 12) + $signed(22'sd5425);
    reg signed [21:0] a0_14;
    always @(posedge clk) a0_14 <= (pre0_14 <= 0) ? 22'sd0 : (pre0_14 > 2097151) ? 2097151 : pre0_14[21:0];
    wire signed [51:0] acc0_15 = $signed(-22'sd1267) * $signed(x_in);
    wire signed [51:0] pre0_15 = (acc0_15 >>> 12) + $signed(22'sd3757);
    reg signed [21:0] a0_15;
    always @(posedge clk) a0_15 <= (pre0_15 <= 0) ? 22'sd0 : (pre0_15 > 2097151) ? 2097151 : pre0_15[21:0];

    // ---- layer 1 (linear out): 16 -> 1 ----
    wire signed [51:0] acc1_0 = $signed(22'sd967) * $signed(a0_0) + $signed(22'sd141) * $signed(a0_1) + $signed(22'sd1015) * $signed(a0_2) + $signed(22'sd670) * $signed(a0_3) + $signed(-22'sd2782) * $signed(a0_4) + $signed(-22'sd570) * $signed(a0_5) + $signed(-22'sd3931) * $signed(a0_6) + $signed(-22'sd238) * $signed(a0_7) + $signed(22'sd321) * $signed(a0_8) + $signed(-22'sd254) * $signed(a0_9) + $signed(-22'sd201) * $signed(a0_10) + $signed(22'sd1394) * $signed(a0_11) + $signed(-22'sd4489) * $signed(a0_12) + $signed(22'sd118) * $signed(a0_13) + $signed(-22'sd1866) * $signed(a0_14) + $signed(-22'sd2854) * $signed(a0_15);
    wire signed [51:0] pre1_0 = (acc1_0 >>> 12) + $signed(22'sd1614);
    reg signed [21:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 > 2097151) ? 2097151 : (pre1_0 < -2097152) ? -2097152 : pre1_0[21:0];
    assign y_out = a1_0;
endmodule
