// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_ln_h8_d1': 2 Linear layers, latency 2 cycles,
// fully streaming (one sample per clock). Format Q10.12 (22 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_ln_h8_d1 (
    input clk,
    input  signed [21:0] x_in,    // Q10.12, one sample per clock
    output signed [21:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 2;

    // ---- layer 0 (ReLU): 1 -> 8 ----
    wire signed [51:0] acc0_0 = $signed(-22'sd835) * $signed(x_in);
    wire signed [51:0] pre0_0 = (acc0_0 >>> 12) + $signed(22'sd3612);
    reg signed [21:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 22'sd0 : (pre0_0 > 2097151) ? 2097151 : pre0_0[21:0];
    wire signed [51:0] acc0_1 = $signed(-22'sd3816) * $signed(x_in);
    wire signed [51:0] pre0_1 = (acc0_1 >>> 12) + $signed(22'sd5173);
    reg signed [21:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 22'sd0 : (pre0_1 > 2097151) ? 2097151 : pre0_1[21:0];
    wire signed [51:0] acc0_2 = $signed(-22'sd1754) * $signed(x_in);
    wire signed [51:0] pre0_2 = (acc0_2 >>> 12) + $signed(-22'sd401);
    reg signed [21:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 22'sd0 : (pre0_2 > 2097151) ? 2097151 : pre0_2[21:0];
    wire signed [51:0] acc0_3 = $signed(-22'sd9999) * $signed(x_in);
    wire signed [51:0] pre0_3 = (acc0_3 >>> 12) + $signed(22'sd4335);
    reg signed [21:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 22'sd0 : (pre0_3 > 2097151) ? 2097151 : pre0_3[21:0];
    wire signed [51:0] acc0_4 = $signed(-22'sd233) * $signed(x_in);
    wire signed [51:0] pre0_4 = (acc0_4 >>> 12) + $signed(-22'sd2869);
    reg signed [21:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 22'sd0 : (pre0_4 > 2097151) ? 2097151 : pre0_4[21:0];
    wire signed [51:0] acc0_5 = $signed(-22'sd3604) * $signed(x_in);
    wire signed [51:0] pre0_5 = (acc0_5 >>> 12) + $signed(-22'sd807);
    reg signed [21:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 22'sd0 : (pre0_5 > 2097151) ? 2097151 : pre0_5[21:0];
    wire signed [51:0] acc0_6 = $signed(22'sd2844) * $signed(x_in);
    wire signed [51:0] pre0_6 = (acc0_6 >>> 12) + $signed(22'sd276);
    reg signed [21:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 22'sd0 : (pre0_6 > 2097151) ? 2097151 : pre0_6[21:0];
    wire signed [51:0] acc0_7 = $signed(22'sd1418) * $signed(x_in);
    wire signed [51:0] pre0_7 = (acc0_7 >>> 12) + $signed(-22'sd3321);
    reg signed [21:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 22'sd0 : (pre0_7 > 2097151) ? 2097151 : pre0_7[21:0];

    // ---- layer 1 (linear out): 8 -> 1 ----
    wire signed [51:0] acc1_0 = $signed(-22'sd3978) * $signed(a0_0) + $signed(-22'sd3188) * $signed(a0_1) + $signed(22'sd1006) * $signed(a0_2) + $signed(-22'sd4985) * $signed(a0_3) + $signed(22'sd430) * $signed(a0_4) + $signed(-22'sd826) * $signed(a0_5) + $signed(22'sd1548) * $signed(a0_6) + $signed(-22'sd1372) * $signed(a0_7);
    wire signed [51:0] pre1_0 = (acc1_0 >>> 12) + $signed(22'sd2433);
    reg signed [21:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 > 2097151) ? 2097151 : (pre1_0 < -2097152) ? -2097152 : pre1_0[21:0];
    assign y_out = a1_0;
endmodule
