// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_ln_h8_d2': 3 Linear layers, latency 3 cycles,
// fully streaming (one sample per clock). Format Q10.12 (22 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_ln_h8_d2 (
    input clk,
    input  signed [21:0] x_in,    // Q10.12, one sample per clock
    output signed [21:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 3;

    // ---- layer 0 (ReLU): 1 -> 8 ----
    wire signed [51:0] acc0_0 = $signed(22'sd717) * $signed(x_in);
    wire signed [51:0] pre0_0 = (acc0_0 >>> 12) + $signed(22'sd3094);
    reg signed [21:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 22'sd0 : (pre0_0 > 2097151) ? 2097151 : pre0_0[21:0];
    wire signed [51:0] acc0_1 = $signed(22'sd142) * $signed(x_in);
    wire signed [51:0] pre0_1 = (acc0_1 >>> 12) + $signed(-22'sd3019);
    reg signed [21:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 22'sd0 : (pre0_1 > 2097151) ? 2097151 : pre0_1[21:0];
    wire signed [51:0] acc0_2 = $signed(22'sd3605) * $signed(x_in);
    wire signed [51:0] pre0_2 = (acc0_2 >>> 12) + $signed(22'sd829);
    reg signed [21:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 22'sd0 : (pre0_2 > 2097151) ? 2097151 : pre0_2[21:0];
    wire signed [51:0] acc0_3 = $signed(22'sd1131) * $signed(x_in);
    wire signed [51:0] pre0_3 = (acc0_3 >>> 12) + $signed(22'sd1386);
    reg signed [21:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 22'sd0 : (pre0_3 > 2097151) ? 2097151 : pre0_3[21:0];
    wire signed [51:0] acc0_4 = $signed(-22'sd4096) * $signed(x_in);
    wire signed [51:0] pre0_4 = (acc0_4 >>> 12) + $signed(22'sd4302);
    reg signed [21:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 22'sd0 : (pre0_4 > 2097151) ? 2097151 : pre0_4[21:0];
    wire signed [51:0] acc0_5 = $signed(-22'sd1946) * $signed(x_in);
    wire signed [51:0] pre0_5 = (acc0_5 >>> 12) + $signed(22'sd4906);
    reg signed [21:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 22'sd0 : (pre0_5 > 2097151) ? 2097151 : pre0_5[21:0];
    wire signed [51:0] acc0_6 = $signed(22'sd1808) * $signed(x_in);
    wire signed [51:0] pre0_6 = (acc0_6 >>> 12) + $signed(22'sd403);
    reg signed [21:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 22'sd0 : (pre0_6 > 2097151) ? 2097151 : pre0_6[21:0];
    wire signed [51:0] acc0_7 = $signed(22'sd1737) * $signed(x_in);
    wire signed [51:0] pre0_7 = (acc0_7 >>> 12) + $signed(22'sd6040);
    reg signed [21:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 22'sd0 : (pre0_7 > 2097151) ? 2097151 : pre0_7[21:0];

    // ---- layer 1 (ReLU): 8 -> 8 ----
    wire signed [51:0] acc1_0 = $signed(22'sd948) * $signed(a0_0) + $signed(22'sd198) * $signed(a0_1) + $signed(-22'sd498) * $signed(a0_2) + $signed(-22'sd821) * $signed(a0_3) + $signed(-22'sd973) * $signed(a0_4) + $signed(-22'sd628) * $signed(a0_5) + $signed(-22'sd438) * $signed(a0_6) + $signed(22'sd860) * $signed(a0_7);
    wire signed [51:0] pre1_0 = (acc1_0 >>> 12) + $signed(-22'sd1246);
    reg signed [21:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 <= 0) ? 22'sd0 : (pre1_0 > 2097151) ? 2097151 : pre1_0[21:0];
    wire signed [51:0] acc1_1 = $signed(22'sd340) * $signed(a0_0) + $signed(-22'sd312) * $signed(a0_1) + $signed(-22'sd904) * $signed(a0_2) + $signed(22'sd977) * $signed(a0_3) + $signed(-22'sd837) * $signed(a0_4) + $signed(-22'sd208) * $signed(a0_5) + $signed(-22'sd7) * $signed(a0_6) + $signed(-22'sd1350) * $signed(a0_7);
    wire signed [51:0] pre1_1 = (acc1_1 >>> 12) + $signed(-22'sd336);
    reg signed [21:0] a1_1;
    always @(posedge clk) a1_1 <= (pre1_1 <= 0) ? 22'sd0 : (pre1_1 > 2097151) ? 2097151 : pre1_1[21:0];
    wire signed [51:0] acc1_2 = $signed(22'sd1881) * $signed(a0_0) + $signed(-22'sd913) * $signed(a0_1) + $signed(22'sd1019) * $signed(a0_2) + $signed(22'sd942) * $signed(a0_3) + $signed(-22'sd299) * $signed(a0_4) + $signed(-22'sd552) * $signed(a0_5) + $signed(22'sd1137) * $signed(a0_6) + $signed(22'sd115) * $signed(a0_7);
    wire signed [51:0] pre1_2 = (acc1_2 >>> 12) + $signed(22'sd1785);
    reg signed [21:0] a1_2;
    always @(posedge clk) a1_2 <= (pre1_2 <= 0) ? 22'sd0 : (pre1_2 > 2097151) ? 2097151 : pre1_2[21:0];
    wire signed [51:0] acc1_3 = $signed(22'sd1539) * $signed(a0_0) + $signed(-22'sd225) * $signed(a0_1) + $signed(22'sd577) * $signed(a0_2) + $signed(22'sd505) * $signed(a0_3) + $signed(-22'sd754) * $signed(a0_4) + $signed(22'sd661) * $signed(a0_5) + $signed(-22'sd1079) * $signed(a0_6) + $signed(22'sd1054) * $signed(a0_7);
    wire signed [51:0] pre1_3 = (acc1_3 >>> 12) + $signed(22'sd2116);
    reg signed [21:0] a1_3;
    always @(posedge clk) a1_3 <= (pre1_3 <= 0) ? 22'sd0 : (pre1_3 > 2097151) ? 2097151 : pre1_3[21:0];
    wire signed [51:0] acc1_4 = $signed(-22'sd210) * $signed(a0_0) + $signed(-22'sd629) * $signed(a0_1) + $signed(-22'sd3847) * $signed(a0_2) + $signed(-22'sd2249) * $signed(a0_3) + $signed(22'sd8082) * $signed(a0_4) + $signed(22'sd1951) * $signed(a0_5) + $signed(-22'sd13724) * $signed(a0_6) + $signed(-22'sd1323) * $signed(a0_7);
    wire signed [51:0] pre1_4 = (acc1_4 >>> 12) + $signed(22'sd1254);
    reg signed [21:0] a1_4;
    always @(posedge clk) a1_4 <= (pre1_4 <= 0) ? 22'sd0 : (pre1_4 > 2097151) ? 2097151 : pre1_4[21:0];
    wire signed [51:0] acc1_5 = $signed(-22'sd75) * $signed(a0_0) + $signed(22'sd574) * $signed(a0_1) + $signed(-22'sd725) * $signed(a0_2) + $signed(-22'sd956) * $signed(a0_3) + $signed(22'sd6861) * $signed(a0_4) + $signed(22'sd5023) * $signed(a0_5) + $signed(-22'sd1058) * $signed(a0_6) + $signed(22'sd920) * $signed(a0_7);
    wire signed [51:0] pre1_5 = (acc1_5 >>> 12) + $signed(22'sd4429);
    reg signed [21:0] a1_5;
    always @(posedge clk) a1_5 <= (pre1_5 <= 0) ? 22'sd0 : (pre1_5 > 2097151) ? 2097151 : pre1_5[21:0];
    wire signed [51:0] acc1_6 = $signed(-22'sd542) * $signed(a0_0) + $signed(22'sd119) * $signed(a0_1) + $signed(22'sd679) * $signed(a0_2) + $signed(-22'sd637) * $signed(a0_3) + $signed(-22'sd447) * $signed(a0_4) + $signed(-22'sd675) * $signed(a0_5) + $signed(22'sd37) * $signed(a0_6) + $signed(-22'sd1097) * $signed(a0_7);
    wire signed [51:0] pre1_6 = (acc1_6 >>> 12) + $signed(-22'sd978);
    reg signed [21:0] a1_6;
    always @(posedge clk) a1_6 <= (pre1_6 <= 0) ? 22'sd0 : (pre1_6 > 2097151) ? 2097151 : pre1_6[21:0];
    wire signed [51:0] acc1_7 = $signed(22'sd879) * $signed(a0_0) + $signed(22'sd769) * $signed(a0_1) + $signed(-22'sd1612) * $signed(a0_2) + $signed(-22'sd957) * $signed(a0_3) + $signed(22'sd812) * $signed(a0_4) + $signed(-22'sd970) * $signed(a0_5) + $signed(-22'sd1353) * $signed(a0_6) + $signed(22'sd470) * $signed(a0_7);
    wire signed [51:0] pre1_7 = (acc1_7 >>> 12) + $signed(-22'sd527);
    reg signed [21:0] a1_7;
    always @(posedge clk) a1_7 <= (pre1_7 <= 0) ? 22'sd0 : (pre1_7 > 2097151) ? 2097151 : pre1_7[21:0];

    // ---- layer 2 (linear out): 8 -> 1 ----
    wire signed [51:0] acc2_0 = $signed(-22'sd392) * $signed(a1_0) + $signed(-22'sd359) * $signed(a1_1) + $signed(22'sd963) * $signed(a1_2) + $signed(22'sd365) * $signed(a1_3) + $signed(-22'sd2795) * $signed(a1_4) + $signed(-22'sd2162) * $signed(a1_5) + $signed(-22'sd842) * $signed(a1_6) + $signed(22'sd1055) * $signed(a1_7);
    wire signed [51:0] pre2_0 = (acc2_0 >>> 12) + $signed(22'sd2603);
    reg signed [21:0] a2_0;
    always @(posedge clk) a2_0 <= (pre2_0 > 2097151) ? 2097151 : (pre2_0 < -2097152) ? -2097152 : pre2_0[21:0];
    assign y_out = a2_0;
endmodule
