// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_exp_h16_d1': 2 Linear layers, latency 2 cycles,
// fully streaming (one sample per clock). Format Q8.8 (16 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_exp_h16_d1 (
    input clk,
    input  signed [15:0] x_in,    // Q8.8, one sample per clock
    output signed [15:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 2;

    // ---- layer 0 (ReLU): 1 -> 16 ----
    wire signed [39:0] acc0_0 = $signed(16'sd141) * $signed(x_in);
    wire signed [39:0] pre0_0 = (acc0_0 >>> 8) + $signed(16'sd266);
    reg signed [15:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 16'sd0 : (pre0_0 > 32767) ? 32767 : pre0_0[15:0];
    wire signed [39:0] acc0_1 = $signed(-16'sd11) * $signed(x_in);
    wire signed [39:0] pre0_1 = (acc0_1 >>> 8) + $signed(16'sd23);
    reg signed [15:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 16'sd0 : (pre0_1 > 32767) ? 32767 : pre0_1[15:0];
    wire signed [39:0] acc0_2 = $signed(16'sd347) * $signed(x_in);
    wire signed [39:0] pre0_2 = (acc0_2 >>> 8) + $signed(-16'sd8);
    reg signed [15:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 16'sd0 : (pre0_2 > 32767) ? 32767 : pre0_2[15:0];
    wire signed [39:0] acc0_3 = $signed(16'sd55) * $signed(x_in);
    wire signed [39:0] pre0_3 = (acc0_3 >>> 8) + $signed(-16'sd126);
    reg signed [15:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 16'sd0 : (pre0_3 > 32767) ? 32767 : pre0_3[15:0];
    wire signed [39:0] acc0_4 = $signed(-16'sd263) * $signed(x_in);
    wire signed [39:0] pre0_4 = (acc0_4 >>> 8) + $signed(16'sd443);
    reg signed [15:0] a0_4;
    always @(posedge clk) a0_4 <= (pre0_4 <= 0) ? 16'sd0 : (pre0_4 > 32767) ? 32767 : pre0_4[15:0];
    wire signed [39:0] acc0_5 = $signed(-16'sd26) * $signed(x_in);
    wire signed [39:0] pre0_5 = (acc0_5 >>> 8) + $signed(-16'sd111);
    reg signed [15:0] a0_5;
    always @(posedge clk) a0_5 <= (pre0_5 <= 0) ? 16'sd0 : (pre0_5 > 32767) ? 32767 : pre0_5[15:0];
    wire signed [39:0] acc0_6 = $signed(16'sd180) * $signed(x_in);
    wire signed [39:0] pre0_6 = (acc0_6 >>> 8) + $signed(-16'sd65);
    reg signed [15:0] a0_6;
    always @(posedge clk) a0_6 <= (pre0_6 <= 0) ? 16'sd0 : (pre0_6 > 32767) ? 32767 : pre0_6[15:0];
    wire signed [39:0] acc0_7 = $signed(16'sd150) * $signed(x_in);
    wire signed [39:0] pre0_7 = (acc0_7 >>> 8) + $signed(16'sd183);
    reg signed [15:0] a0_7;
    always @(posedge clk) a0_7 <= (pre0_7 <= 0) ? 16'sd0 : (pre0_7 > 32767) ? 32767 : pre0_7[15:0];
    wire signed [39:0] acc0_8 = $signed(16'sd148) * $signed(x_in);
    wire signed [39:0] pre0_8 = (acc0_8 >>> 8) + $signed(16'sd115);
    reg signed [15:0] a0_8;
    always @(posedge clk) a0_8 <= (pre0_8 <= 0) ? 16'sd0 : (pre0_8 > 32767) ? 32767 : pre0_8[15:0];
    wire signed [39:0] acc0_9 = $signed(-16'sd275) * $signed(x_in);
    wire signed [39:0] pre0_9 = (acc0_9 >>> 8) + $signed(16'sd390);
    reg signed [15:0] a0_9;
    always @(posedge clk) a0_9 <= (pre0_9 <= 0) ? 16'sd0 : (pre0_9 > 32767) ? 32767 : pre0_9[15:0];
    wire signed [39:0] acc0_10 = $signed(-16'sd73) * $signed(x_in);
    wire signed [39:0] pre0_10 = (acc0_10 >>> 8) + $signed(-16'sd172);
    reg signed [15:0] a0_10;
    always @(posedge clk) a0_10 <= (pre0_10 <= 0) ? 16'sd0 : (pre0_10 > 32767) ? 32767 : pre0_10[15:0];
    wire signed [39:0] acc0_11 = $signed(16'sd109) * $signed(x_in);
    wire signed [39:0] pre0_11 = (acc0_11 >>> 8) + $signed(16'sd236);
    reg signed [15:0] a0_11;
    always @(posedge clk) a0_11 <= (pre0_11 <= 0) ? 16'sd0 : (pre0_11 > 32767) ? 32767 : pre0_11[15:0];
    wire signed [39:0] acc0_12 = $signed(16'sd68) * $signed(x_in);
    wire signed [39:0] pre0_12 = (acc0_12 >>> 8) + $signed(-16'sd148);
    reg signed [15:0] a0_12;
    always @(posedge clk) a0_12 <= (pre0_12 <= 0) ? 16'sd0 : (pre0_12 > 32767) ? 32767 : pre0_12[15:0];
    wire signed [39:0] acc0_13 = $signed(16'sd250) * $signed(x_in);
    wire signed [39:0] pre0_13 = (acc0_13 >>> 8) + $signed(-16'sd165);
    reg signed [15:0] a0_13;
    always @(posedge clk) a0_13 <= (pre0_13 <= 0) ? 16'sd0 : (pre0_13 > 32767) ? 32767 : pre0_13[15:0];
    wire signed [39:0] acc0_14 = $signed(-16'sd266) * $signed(x_in);
    wire signed [39:0] pre0_14 = (acc0_14 >>> 8) + $signed(16'sd533);
    reg signed [15:0] a0_14;
    always @(posedge clk) a0_14 <= (pre0_14 <= 0) ? 16'sd0 : (pre0_14 > 32767) ? 32767 : pre0_14[15:0];
    wire signed [39:0] acc0_15 = $signed(16'sd282) * $signed(x_in);
    wire signed [39:0] pre0_15 = (acc0_15 >>> 8) + $signed(-16'sd285);
    reg signed [15:0] a0_15;
    always @(posedge clk) a0_15 <= (pre0_15 <= 0) ? 16'sd0 : (pre0_15 > 32767) ? 32767 : pre0_15[15:0];

    // ---- layer 1 (linear out): 16 -> 1 ----
    wire signed [39:0] acc1_0 = $signed(16'sd132) * $signed(a0_0) + $signed(-16'sd17) * $signed(a0_1) + $signed(16'sd122) * $signed(a0_2) + $signed(16'sd25) * $signed(a0_3) + $signed(16'sd328) * $signed(a0_4) + $signed(-16'sd33) * $signed(a0_5) + $signed(16'sd150) * $signed(a0_6) + $signed(16'sd46) * $signed(a0_7) + $signed(16'sd152) * $signed(a0_8) + $signed(16'sd320) * $signed(a0_9) + $signed(16'sd49) * $signed(a0_10) + $signed(16'sd126) * $signed(a0_11) + $signed(-16'sd18) * $signed(a0_12) + $signed(16'sd106) * $signed(a0_13) + $signed(-16'sd588) * $signed(a0_14) + $signed(16'sd303) * $signed(a0_15);
    wire signed [39:0] pre1_0 = (acc1_0 >>> 8) + $signed(16'sd61);
    reg signed [15:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 > 32767) ? 32767 : (pre1_0 < -32768) ? -32768 : pre1_0[15:0];
    assign y_out = a1_0;
endmodule
