// Generated by mlp/verilog_gen_mlp.py -- do not edit by hand.
// Quantized MLP 'mlp_ln_h4_d2': 3 Linear layers, latency 3 cycles,
// fully streaming (one sample per clock). Format Q10.12 (22 bits).
// Weights are constants; ReLU on every layer but the output. Arithmetic mirrors
// mlp/fixed_point_mlp.py::QuantMLP op-for-op (acc>>>F + bias, saturate, ReLU).

module mlp_ln_h4_d2 (
    input clk,
    input  signed [21:0] x_in,    // Q10.12, one sample per clock
    output signed [21:0] y_out    // valid LATENCY cycles after its x_in
);
    localparam LATENCY = 3;

    // ---- layer 0 (ReLU): 1 -> 4 ----
    wire signed [51:0] acc0_0 = $signed(22'sd1358) * $signed(x_in);
    wire signed [51:0] pre0_0 = (acc0_0 >>> 12) + $signed(-22'sd2946);
    reg signed [21:0] a0_0;
    always @(posedge clk) a0_0 <= (pre0_0 <= 0) ? 22'sd0 : (pre0_0 > 2097151) ? 2097151 : pre0_0[21:0];
    wire signed [51:0] acc0_1 = $signed(22'sd1252) * $signed(x_in);
    wire signed [51:0] pre0_1 = (acc0_1 >>> 12) + $signed(-22'sd2718);
    reg signed [21:0] a0_1;
    always @(posedge clk) a0_1 <= (pre0_1 <= 0) ? 22'sd0 : (pre0_1 > 2097151) ? 2097151 : pre0_1[21:0];
    wire signed [51:0] acc0_2 = $signed(-22'sd2768) * $signed(x_in);
    wire signed [51:0] pre0_2 = (acc0_2 >>> 12) + $signed(22'sd6671);
    reg signed [21:0] a0_2;
    always @(posedge clk) a0_2 <= (pre0_2 <= 0) ? 22'sd0 : (pre0_2 > 2097151) ? 2097151 : pre0_2[21:0];
    wire signed [51:0] acc0_3 = $signed(-22'sd7792) * $signed(x_in);
    wire signed [51:0] pre0_3 = (acc0_3 >>> 12) + $signed(22'sd4101);
    reg signed [21:0] a0_3;
    always @(posedge clk) a0_3 <= (pre0_3 <= 0) ? 22'sd0 : (pre0_3 > 2097151) ? 2097151 : pre0_3[21:0];

    // ---- layer 1 (ReLU): 4 -> 4 ----
    wire signed [51:0] acc1_0 = $signed(22'sd1147) * $signed(a0_0) + $signed(22'sd2569) * $signed(a0_1) + $signed(-22'sd1669) * $signed(a0_2) + $signed(-22'sd44) * $signed(a0_3);
    wire signed [51:0] pre1_0 = (acc1_0 >>> 12) + $signed(22'sd2641);
    reg signed [21:0] a1_0;
    always @(posedge clk) a1_0 <= (pre1_0 <= 0) ? 22'sd0 : (pre1_0 > 2097151) ? 2097151 : pre1_0[21:0];
    wire signed [51:0] acc1_1 = $signed(22'sd1967) * $signed(a0_0) + $signed(-22'sd98) * $signed(a0_1) + $signed(22'sd3438) * $signed(a0_2) + $signed(22'sd6203) * $signed(a0_3);
    wire signed [51:0] pre1_1 = (acc1_1 >>> 12) + $signed(-22'sd1875);
    reg signed [21:0] a1_1;
    always @(posedge clk) a1_1 <= (pre1_1 <= 0) ? 22'sd0 : (pre1_1 > 2097151) ? 2097151 : pre1_1[21:0];
    wire signed [51:0] acc1_2 = $signed(22'sd1751) * $signed(a0_0) + $signed(-22'sd542) * $signed(a0_1) + $signed(-22'sd1536) * $signed(a0_2) + $signed(22'sd543) * $signed(a0_3);
    wire signed [51:0] pre1_2 = (acc1_2 >>> 12) + $signed(22'sd1936);
    reg signed [21:0] a1_2;
    always @(posedge clk) a1_2 <= (pre1_2 <= 0) ? 22'sd0 : (pre1_2 > 2097151) ? 2097151 : pre1_2[21:0];
    wire signed [51:0] acc1_3 = $signed(22'sd767) * $signed(a0_0) + $signed(-22'sd103) * $signed(a0_1) + $signed(-22'sd856) * $signed(a0_2) + $signed(-22'sd222) * $signed(a0_3);
    wire signed [51:0] pre1_3 = (acc1_3 >>> 12) + $signed(22'sd1517);
    reg signed [21:0] a1_3;
    always @(posedge clk) a1_3 <= (pre1_3 <= 0) ? 22'sd0 : (pre1_3 > 2097151) ? 2097151 : pre1_3[21:0];

    // ---- layer 2 (linear out): 4 -> 1 ----
    wire signed [51:0] acc2_0 = $signed(22'sd2599) * $signed(a1_0) + $signed(-22'sd3858) * $signed(a1_1) + $signed(22'sd2595) * $signed(a1_2) + $signed(22'sd2333) * $signed(a1_3);
    wire signed [51:0] pre2_0 = (acc2_0 >>> 12) + $signed(-22'sd243);
    reg signed [21:0] a2_0;
    always @(posedge clk) a2_0 <= (pre2_0 > 2097151) ? 2097151 : (pre2_0 < -2097152) ? -2097152 : pre2_0[21:0];
    assign y_out = a2_0;
endmodule
