// Generated by mlp/rom_baseline.py -- do not edit by hand.
// Direct ROM for exp over [-2.0, 2.0], Q8.8
// (16 bits). 2048 entries x 16 b = 32768 bit ~= 8 EBR.
// Bit-exact to quantize(exp(x)); latency 2 (registered addr+data). Exhaustively
// verifiable: the 2048-entry table IS the spec.

module rom_exp (
    input clk,
    input  signed [15:0] x_in,
    output signed [15:0] y_out    // valid 2 cycles after x_in
);
    localparam LATENCY = 2;          // registered address + registered data (BRAM)
    (* rom_style = "block" *) reg [15:0] rom [0:2047];
    initial $readmemh("rom_exp.hex", rom);

    // saturate to the domain, then offset to a 0-based table index
    wire signed [15:0] xs =
        (x_in < -512) ? -512 : (x_in > 1535) ? 1535 : x_in;
    wire [10:0] idx = (xs - -512);

    reg [10:0] idx_r;
    reg [15:0] y_r;
    always @(posedge clk) begin
        idx_r <= idx;                // stage 1: register the address
        y_r   <= rom[idx_r];         // stage 2: registered synchronous read
    end
    assign y_out = y_r;
endmodule
