// Generated by mlp/symbolic_2in.py -- do not edit by hand.
// 2-input symbolic unit: f(x,y) = exp(x) - ln(y), the native EML gate at arity 2.
// Format Q8.8 (16 bits). Datapath = two interpolated LUT legs +
// saturating subtract (ADDITIVE in arity; cf. the 2-D ROM in mlp/rom_baseline.py,
// whose size is MULTIPLICATIVE: 2^(Wx+Wy) entries).

// ---------------------------------------------------------------- exp(a) ----
module eml_exp #(parameter W = 16, parameter F = 8) (
    input  signed [W-1:0] a,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 4;
    localparam signed [W-1:0] XMIN = -(8 <<< F), XMAX = (8 <<< F);

    reg signed [W-1:0] lut [0:(1<<LUTB)];
    initial $readmemh("symbolic_exp_ln_2in_exp_lut.hex", lut);

    wire signed [W-1:0] r = (a < XMIN) ? XMIN : (a > XMAX) ? XMAX : a;
    wire [W:0] u = r - XMIN;                       // 0 .. 2^(F+4), needs W+1 bits
    wire [LUTB:0] idx = u >> (F - 4);              // 0 .. 256
    wire [IB-1:0] fr = u >> (F - 4 - IB);
    wire signed [W-1:0] y0 = lut[idx];
    wire signed [W-1:0] y1 = (idx >= (1 << LUTB)) ? lut[1 << LUTB] : lut[idx + 1];
    wire signed [W+IB:0] d = (y1 - y0) * $signed({1'b0, fr});
    assign y = (idx >= (1 << LUTB)) ? lut[1 << LUTB] : y0 + (d >>> IB);
endmodule

// ----------------------------------------------------------------- ln(b) ----
// ln(m * 2^k) = ln_lut[m] + k*ln2, m in [1,2) via leading-one detect.
module eml_ln #(parameter W = 16, parameter F = 8) (
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    localparam LUTB = 8, IB = 4;
    localparam signed [W-1:0] LN2 = 16'sd177;

    reg signed [W-1:0] lut [0:(1<<LUTB)];
    initial $readmemh("symbolic_exp_ln_2in_ln_lut.hex", lut);

    wire [W-1:0] r = (b <= 0) ? 16'd1 : b[W-1:0];   // clamp to smallest positive

    // leading-one position p
    integer i;
    reg [$clog2(W)-1:0] p;
    always @* begin
        p = 0;
        for (i = 0; i < W; i = i + 1)
            if (r[i]) p = i[$clog2(W)-1:0];
    end

    // top LUTB+IB mantissa bits below the leading one
    wire [2*W-1:0] rext = r;
    wire [2*W-1:0] shifted = (rext << W) >> p;       // mantissa fraction in bits [W-1:0]
    wire [LUTB+IB-1:0] mant = shifted[W-1 -: LUTB+IB];
    wire [LUTB-1:0] idx = mant[LUTB+IB-1:IB];
    wire [IB-1:0] fr = mant[IB-1:0];

    wire signed [W-1:0] y0 = lut[idx];
    wire signed [W-1:0] y1 = lut[idx + 1];
    wire signed [W+IB:0] d = (y1 - y0) * $signed({1'b0, fr});
    wire signed [W-1:0] ln_m = y0 + (d >>> IB);

    wire signed [$clog2(W):0] k = $signed({1'b0, p}) - F;
    assign y = ln_m + k * LN2;
endmodule

// -------------------------------------------------------------- eml gate ----
module eml_gate #(parameter W = 16, parameter F = 8) (
    input  signed [W-1:0] a,
    input  signed [W-1:0] b,
    output signed [W-1:0] y
);
    wire signed [W-1:0] ea, lb;
    eml_exp #(.W(W), .F(F)) u_exp (.a(a), .y(ea));
    eml_ln  #(.W(W), .F(F)) u_ln  (.b(b), .y(lb));
    wire signed [W:0] s = ea - lb;
    localparam signed [W:0] SMAX = (1 <<< (W-1)) - 1, SMIN = -(1 <<< (W-1));
    assign y = (s > SMAX) ? SMAX[W-1:0] : (s < SMIN) ? SMIN[W-1:0] : s[W-1:0];
endmodule

// ------------------------------------------------------------- top level ----
module symbolic_exp_ln_2in (
    input  signed [15:0] x_in,    // Q8.8, exp leg
    input  signed [15:0] y_in,    // Q8.8, ln  leg
    output signed [15:0] y_out    // Q8.8
);
    eml_gate #(.W(16), .F(8)) u_gate (.a(x_in), .b(y_in), .y(y_out));
endmodule
